package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Location;
import com.avaruusstudios.vmdb.data.LocationDataAccess;
import com.avaruusstudios.vmdb.data.DeleteDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link LocationDataAccess} interface for managing
 * {@link Location} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Location} entities (e.g., finding by unique location name
 * or by address components).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Location IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of a location is enforced through a combination of `LocationName`, `Address`,
 * `City`, `State`, and `ZipCode` at the database level.</li>
 * <li>Deletion of location records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0
 * Created On: 2025-07-20
 * Updated On: 2025-07-22
 *
 * @see LocationDataAccess
 * @see Location
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class LocationImplementation implements LocationDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code LocationImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(LocationImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new location record. Loaded from `location/insertLocation.sql`. */
    private static final String SQL_CREATE_LOCATION_RECORD;
    /** SQL query to select a location record by its unique ID. Loaded from `location/selectLocationById.sql`. */
    private static final String SQL_READ_LOCATION_RECORD;
    /** SQL query to select all location records. Loaded from `location/selectAllLocations.sql`. */
    private static final String SQL_READ_ALL_LOCATION_RECORDS;
    /** SQL query to count the total number of location records. Loaded from `location/countLocations.sql`. */
    private static final String SQL_COUNT_LOCATION_RECORDS;
    /** SQL query to check if a location record with a given ID exists. Loaded from `location/existsLocationById.sql`. */
    private static final String SQL_EXISTS_LOCATION_BY_ID;
    /** SQL query to update an existing location record. Loaded from `location/updateLocation.sql`. */
    private static final String SQL_UPDATE_LOCATION_RECORD;
    /** SQL query to soft-delete a location record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `location/deleteLocationSoft.sql`. */
    private static final String SQL_DELETE_LOCATION_SOFT;
    /** SQL query to select a location record by its unique name. Loaded from `location/selectLocationByName.sql`. */
    private static final String SQL_SELECT_LOCATION_BY_NAME;
    /** SQL query to select a location record by a combination of street address, city, state, and zip code. Loaded from `location/selectLocationByAddress.sql`. */
    private static final String SQL_SELECT_LOCATION_BY_ADDRESS;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            SQL_CREATE_LOCATION_RECORD = QueryLoader.getQuery("location/insertLocation.sql");
            SQL_READ_LOCATION_RECORD = QueryLoader.getQuery("location/selectLocationById.sql");
            SQL_READ_ALL_LOCATION_RECORDS = QueryLoader.getQuery("location/selectAllLocations.sql");
            SQL_COUNT_LOCATION_RECORDS = QueryLoader.getQuery("location/countLocations.sql");
            SQL_EXISTS_LOCATION_BY_ID = QueryLoader.getQuery("location/existsLocationById.sql");
            SQL_UPDATE_LOCATION_RECORD = QueryLoader.getQuery("location/updateLocation.sql");
            SQL_DELETE_LOCATION_SOFT = QueryLoader.getQuery("location/deleteLocationSoft.sql");
            SQL_SELECT_LOCATION_BY_NAME = QueryLoader.getQuery("location/selectLocationByName.sql");
            SQL_SELECT_LOCATION_BY_ADDRESS = QueryLoader.getQuery("location/selectLocationByAddress.sql");
            logger.info("All SQL queries for LocationImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for LocationImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Location} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code Location} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `LocationID` and setting it via the package-private `_setLocationID` method.</li>
     * <li>String fields (e.g., `LocationName`, `Address`, `City`, `State`, `ZipCode`, `Notes`).</li>
     * <li>Double fields (e.g., `Latitude`, `Longitude`).</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` `TEXT` field, parsing it into
     * {@link LocalDateTime} objects using {@link #CUSTOM_DATETIME_FORMATTER} if present.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing location data.
     * @return A fully populated {@link Location} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private Location mapResultSetToLocation(ResultSet rs) throws SQLException {
        Location location = new Location();
        Integer locationId = rs.getInt("LocationID");
        if (locationId > 0) { // SQLite getInt returns 0 for NULL, check for positive valid ID
            location._setLocationID(locationId);
        }

        location.setLocationName(rs.getString("LocationName"));
        location.setAddress(rs.getString("Address"));
        location.setCity(rs.getString("City"));
        location.setState(rs.getString("State"));
        location.setZipCode(rs.getString("ZipCode"));

        Double latitude = rs.getObject("Latitude", Double.class);
        location.setLatitude(latitude);

        Double longitude = rs.getObject("Longitude", Double.class);
        location.setLongitude(longitude);

        location.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        location.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ?
                LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        location.setNotes(rs.getString("Notes"));

        return location;
    }

    /**
     * <p>
     * Inserts a new {@link Location} record into the SQLite database.
     * The database's `AUTOINCREMENT` feature automatically assigns a unique `LocationID`.
     * </p>
     * <p>
     * This method validates the provided {@code Location} object and its mandatory fields
     * (`LocationName`, `Address`, `City`, `State`, `ZipCode`) before attempting the insertion.
     * It handles potential database errors, including unique constraint violations.
     * Upon successful insertion, the database-generated `LocationID` is injected back into the
     * provided `Location` object.
     * </p>
     *
     * @param location The {@link Location} object to be created. Its `LocationID` will be ignored if present,
     * as it's auto-generated by the database.
     * @return The created {@link Location} object, updated with its database-assigned `LocationID`.
     * @throws DatabaseAccessException  if a database access error occurs during creation,
     * e.g., a unique constraint violation, or other SQL errors.
     * @throws NullPointerException     if the provided {@code location} object or any of its
     * required `NOT NULL` fields (`LocationName`, `Address`, `City`, `State`, `ZipCode`) are {@code null}.
     * @throws IllegalArgumentException if any mandatory string fields are empty after trimming.
     * @throws IllegalStateException    if the `Location` object's internal state is invalid
     * (e.g., `_setLocationID` is called on an already set ID, though this should ideally not happen here).
     */
    @Override
    public Location createRecord(Location location) throws DatabaseAccessException {
        Objects.requireNonNull(location, "Location object cannot be null for creation.");
        Objects.requireNonNull(location.getLocationName(), "Location name cannot be null for creation.");
        Objects.requireNonNull(location.getAddress(), "Address cannot be null for creation.");
        Objects.requireNonNull(location.getCity(), "City cannot be null for creation.");
        Objects.requireNonNull(location.getState(), "State cannot be null for creation.");
        Objects.requireNonNull(location.getZipCode(), "Zip Code cannot be null for creation.");

        if (location.getLocationName().trim().isEmpty() ||
                location.getAddress().trim().isEmpty() ||
                location.getCity().trim().isEmpty() ||
                location.getState().trim().isEmpty() ||
                location.getZipCode().trim().isEmpty()) {
            throw new IllegalArgumentException("Mandatory string fields (name, address, city, state, zip code) cannot be empty for location creation.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_CREATE_LOCATION_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, location.getLocationName().trim());
            pstmt.setString(2, location.getAddress().trim());
            pstmt.setString(3, location.getCity().trim());
            pstmt.setString(4, location.getState().trim());
            pstmt.setString(5, location.getZipCode().trim());

            if (location.getLatitude() != null) {
                pstmt.setDouble(6, location.getLatitude());
            } else {
                pstmt.setNull(6, Types.REAL);
            }

            if (location.getLongitude() != null) {
                pstmt.setDouble(7, location.getLongitude());
            } else {
                pstmt.setNull(7, Types.REAL);
            }

            pstmt.setInt(8, location.getIsActive() ? 1 : 0);

            if (location.getDeletedAt() != null) {
                pstmt.setString(9, location.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(9, Types.VARCHAR);
            }

            pstmt.setString(10, location.getNotes() != null ? location.getNotes().trim() : null);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.error("Creating location failed, no rows affected for name: {}.", location.getLocationName());
                throw new DatabaseAccessException("Creating location failed, no rows affected.");
            }

            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    location._setLocationID(generatedKeys.getInt(1));
                    logger.info("Location created successfully with ID: {}.", location.getLocationID());
                } else {
                    logger.error("Creating location failed, no ID obtained for name: {}.", location.getLocationName());
                    throw new DatabaseAccessException("Creating location failed, no ID obtained.");
                }
            }
            return location;

        } catch (SQLException e) {
            logger.error("Error creating location '{}': {}", location.getLocationName(), e.getMessage(), e);
            if (e.getErrorCode() == 19) { // SQLite unique constraint violation
                String errorMessage = "Failed to create location. It might already exist or a unique constraint was violated.";
                // Attempt to provide more specific messages if possible based on common unique constraints
                if (e.getMessage().contains("UNIQUE constraint failed: Locations.LocationName")) {
                    errorMessage = "Location with name '" + location.getLocationName() + "' already exists. Location names must be unique.";
                } else if (e.getMessage().contains("UNIQUE constraint failed: Locations.LocationName, Locations.Address, Locations.City, Locations.State, Locations.ZipCode")) {
                    errorMessage = "Location with the same name and address details already exists.";
                }
                throw new DatabaseAccessException(errorMessage, e);
            }
            throw new DatabaseAccessException("Failed to create location: " + e.getMessage(), e);
        } catch (IllegalArgumentException | IllegalStateException e) {
            logger.error("Location validation/state error during creation for name '{}': {}", location.getLocationName(), e.getMessage(), e);
            throw new DatabaseAccessException("Location data is invalid or in an illegal state for creation: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Retrieves a single {@link Location} record from the database by its unique identifier (`LocationID`).
     * </p>
     *
     * @param id The unique integer ID of the location to retrieve. Must not be {@code null} and must be positive.
     * @return An {@link Optional} containing the {@link Location} object if a location with the given ID is found,
     * or an empty {@link Optional} if no such location exists.
     * @throws DatabaseAccessException  if a database access error occurs during retrieval.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public Optional<Location> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for retrieval.");
        if (id <= 0) {
            throw new IllegalArgumentException("Location ID must be positive for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_LOCATION_RECORD)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToLocation(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving location by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve location by ID " + id + ": " + e.getMessage(), e);
        }
        return Optional.empty();
    }

    /**
     * <p>
     * Retrieves all {@link Location} records currently stored in the database.
     * </p>
     *
     * @return A {@link List} of {@link Location} objects. The list will be empty if no locations are found.
     * @throws DatabaseAccessException if a database access error occurs during retrieval.
     */
    @Override
    public List<Location> readRecordAll() throws DatabaseAccessException {
        List<Location> locations = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_READ_ALL_LOCATION_RECORDS)) {

            while (rs.next()) {
                locations.add(mapResultSetToLocation(rs));
            }
        } catch (SQLException e) {
            logger.error("Error retrieving all locations: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve all locations: " + e.getMessage(), e);
        }
        return locations;
    }

    /**
     * <p>
     * Counts the total number of location records in the database.
     * </p>
     *
     * @return The total count of locations as a {@code long}. Returns 0 if no locations are found
     * or if an error occurs.
     * @throws DatabaseAccessException if a database access error occurs during counting.
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_COUNT_LOCATION_RECORDS)) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            logger.error("Error counting locations: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to count locations: " + e.getMessage(), e);
        }
        return 0;
    }

    /**
     * <p>
     * Checks if a location record with the specified ID exists in the database.
     * </p>
     *
     * @param id The unique integer ID of the location to check for existence. Must not be {@code null} and must be positive.
     * @return {@code true} if a location with the given ID exists, {@code false} otherwise.
     * @throws DatabaseAccessException  if a database access error occurs during the existence check.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for existence check.");
        if (id <= 0) {
            throw new IllegalArgumentException("Location ID must be positive for existence check.");
        }
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_EXISTS_LOCATION_BY_ID)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of location by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to check existence of location by ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Updates an existing {@link Location} record in the database. The update operation is
     * based on the `LocationID` of the provided {@link Location} object.
     * </p>
     * <p>
     * This method validates the provided {@code Location} object and its mandatory fields
     * (`LocationID`, `LocationName`, `Address`, `City`, `State`, `ZipCode`) before execution.
     * It specifically handles unique constraint violations if the updated location details
     * conflict with an existing location's unique attributes.
     * </p>
     *
     * @param location The {@link Location} object containing the updated data.
     * Its `LocationID` must not be {@code null} and must be positive to identify the record to update.
     * @throws DatabaseAccessException  if a database access error occurs during the update,
     * e.g., a unique constraint violation, or other SQL errors.
     * @throws NullPointerException     if the provided {@code location} object itself, its `LocationID`,
     * or any of its required `NOT NULL` fields are {@code null}.
     * @throws IllegalArgumentException if the `LocationID` is non-positive, or if any
     * mandatory string fields are empty after trimming.
     */
    @Override
    public void updateRecord(Location location) throws DatabaseAccessException {
        Objects.requireNonNull(location, "Location object cannot be null for update.");
        Objects.requireNonNull(location.getLocationID(), "Location ID cannot be null for update.");
        if (location.getLocationID() <= 0) {
            throw new IllegalArgumentException("Location ID must be positive for update.");
        }
        Objects.requireNonNull(location.getLocationName(), "Location name cannot be null for update.");
        Objects.requireNonNull(location.getAddress(), "Address cannot be null for update.");
        Objects.requireNonNull(location.getCity(), "City cannot be null for update.");
        Objects.requireNonNull(location.getState(), "State cannot be null for update.");
        Objects.requireNonNull(location.getZipCode(), "Zip Code cannot be null for update.");

        if (location.getLocationName().trim().isEmpty() ||
                location.getAddress().trim().isEmpty() ||
                location.getCity().trim().isEmpty() ||
                location.getState().trim().isEmpty() ||
                location.getZipCode().trim().isEmpty()) {
            throw new IllegalArgumentException("Mandatory string fields (name, address, city, state, zip code) cannot be empty for location update.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_UPDATE_LOCATION_RECORD)) {

            pstmt.setString(1, location.getLocationName().trim());
            pstmt.setString(2, location.getAddress().trim());
            pstmt.setString(3, location.getCity().trim());
            pstmt.setString(4, location.getState().trim());
            pstmt.setString(5, location.getZipCode().trim());

            if (location.getLatitude() != null) {
                pstmt.setDouble(6, location.getLatitude());
            } else {
                pstmt.setNull(6, Types.REAL);
            }

            if (location.getLongitude() != null) {
                pstmt.setDouble(7, location.getLongitude());
            } else {
                pstmt.setNull(7, Types.REAL);
            }

            pstmt.setInt(8, location.getIsActive() ? 1 : 0);

            if (location.getDeletedAt() != null) {
                pstmt.setString(9, location.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(9, Types.VARCHAR);
            }

            pstmt.setString(10, location.getNotes() != null ? location.getNotes().trim() : null);
            pstmt.setInt(11, location.getLocationID()); // WHERE clause ID

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Update location with ID {} affected 0 rows. Location might not exist or data was identical.", location.getLocationID());
                throw new DatabaseAccessException("Location with ID " + location.getLocationID() + " not found for update or no changes were made.");
            } else {
                logger.info("Location with ID {} updated successfully. Affected rows: {}.", location.getLocationID(), affectedRows);
            }

        } catch (SQLException e) {
            logger.error("Error updating location with ID {}: {}", location.getLocationID(), e.getMessage(), e);
            if (e.getErrorCode() == 19) { // SQLite unique constraint violation
                String errorMessage = "Failed to update location. It might already exist or a unique constraint was violated.";
                if (e.getMessage().contains("UNIQUE constraint failed: Locations.LocationName")) {
                    errorMessage = "Location with name '" + location.getLocationName() + "' already exists. Location names must be unique.";
                } else if (e.getMessage().contains("UNIQUE constraint failed: Locations.LocationName, Locations.Address, Locations.City, Locations.State, Locations.ZipCode")) {
                    errorMessage = "Location with the same name and address details already exists.";
                }
                throw new DatabaseAccessException(errorMessage, e);
            }
            throw new DatabaseAccessException("Failed to update location with ID " + location.getLocationID() + ": " + e.getMessage(), e);
        } catch (IllegalArgumentException e) {
            logger.error("Location validation error during update for location ID {}: {}", location.getLocationID(), e.getMessage(), e);
            throw new DatabaseAccessException("Location data is invalid for update: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Soft-deletes a {@link Location} record from the database by setting its `IsActive` flag
     * to `0` (false) and updating the `DeletedAt` timestamp to the current date and time.
     * This method does not physically remove the record, preserving historical data.
     * </p>
     *
     * @param id The unique integer ID of the location to soft-delete. Must not be {@code null} and must be positive.
     * @throws DatabaseAccessException  if a database access error occurs during the soft-deletion.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for deletion.");
        if (id <= 0) {
            throw new IllegalArgumentException("Location ID must be positive for deletion.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_DELETE_LOCATION_SOFT)) {

            pstmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            pstmt.setInt(2, id);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Soft-delete location with ID {} affected 0 rows. Location might not exist or already soft-deleted.", id);
                throw new DatabaseAccessException("Location with ID " + id + " not found for soft-deletion or already deleted.");
            } else {
                logger.info("Location with ID {} soft-deleted successfully (IsActive=0, DeletedAt={}).", id, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting location with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to soft-delete location with ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Finds a single {@link Location} record by a unique combination of its address components.
     * This could be used for verifying if a specific address already exists in the system.
     * </p>
     *
     * @param streetAddress The street address (e.g., "123 Main St"). Must not be {@code null} or empty.
     * @param city The city (e.g., "Anytown"). Must not be {@code null} or empty.
     * @param state The state (e.g., "CA"). Must not be {@code null} or empty.
     * @param zipCode The zip code (e.g., "90210"). Must not be {@code null} or empty.
     * @return An {@link Optional} containing the {@link Location} if a match is found,
     * or an empty {@link Optional} if no location exists with the given address details.
     * @throws DatabaseAccessException If a database access error occurs during the lookup.
     * @throws NullPointerException If any of the provided address components are {@code null}.
     * @throws IllegalArgumentException If any of the provided address components are empty strings after trimming.
     */
    @Override
    public Optional<Location> findByAddress(String streetAddress, String city, String state, String zipCode) throws DatabaseAccessException {
        Objects.requireNonNull(streetAddress, "Street address cannot be null for address search.");
        Objects.requireNonNull(city, "City cannot be null for address search.");
        Objects.requireNonNull(state, "State cannot be null for address search.");
        Objects.requireNonNull(zipCode, "Zip Code cannot be null for address search.");

        String trimmedStreetAddress = streetAddress.trim();
        String trimmedCity = city.trim();
        String trimmedState = state.trim();
        String trimmedZipCode = zipCode.trim();

        if (trimmedStreetAddress.isEmpty() || trimmedCity.isEmpty() || trimmedState.isEmpty() || trimmedZipCode.isEmpty()) {
            throw new IllegalArgumentException("All address components (street address, city, state, zip code) must be non-empty for address search.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_LOCATION_BY_ADDRESS)) {

            pstmt.setString(1, trimmedStreetAddress);
            pstmt.setString(2, trimmedCity);
            pstmt.setString(3, trimmedState);
            pstmt.setString(4, trimmedZipCode);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToLocation(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving location by address '{}', '{}', '{}', '{}': {}",
                    trimmedStreetAddress, trimmedCity, trimmedState, trimmedZipCode, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve location by address: " + e.getMessage(), e);
        }
        return Optional.empty();
    }

    /**
     * <p>
     * Finds a single {@link Location} record by its unique name.
     * </p>
     *
     * @param locationName The name of the location to find (e.g., "Main Office", "South Parking Lot").
     * Must not be {@code null} or empty.
     * @return An {@link Optional} containing the {@link Location} if found, or an
     * empty {@link Optional} if no location exists with the given name.
     * @throws DatabaseAccessException If a database access error occurs during the lookup.
     * @throws NullPointerException If the provided {@code locationName} is {@code null}.
     * @throws IllegalArgumentException If the provided {@code locationName} is an empty string after trimming.
     */
    @Override
    public Optional<Location> findByLocationName(String locationName) throws DatabaseAccessException {
        Objects.requireNonNull(locationName, "Location name cannot be null for retrieval.");
        String trimmedName = locationName.trim();
        if (trimmedName.isEmpty()) {
            throw new IllegalArgumentException("Location name cannot be empty for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_LOCATION_BY_NAME)) {

            pstmt.setString(1, trimmedName);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToLocation(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving location by name '{}': {}", trimmedName, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve location by name '" + trimmedName + "': " + e.getMessage(), e);
        }
        return Optional.empty();
    }
}