package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Participant;
import com.avaruusstudios.vmdb.model.Location; // Needed for foreign key relationships, though not directly mapped here
import com.avaruusstudios.vmdb.model.Role; // Assuming Role enum is in this package
import com.avaruusstudios.vmdb.model.Program; // New import for Program enum
import com.avaruusstudios.vmdb.data.ParticipantDataAccess;
import com.avaruusstudios.vmdb.data.DeleteDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link ParticipantDataAccess} interface for managing
 * {@link Participant} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Participant} entities (e.g., finding by email, counting/retrieving
 * active participants, or filtering by program/role).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Participant IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `Email` is enforced at the database level.</li>
 * <li>Deletion of participant records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDate` objects (e.g., `JoinDate`) are persisted as `TEXT` in the SQLite database
 * using a "yyyy-MM-dd" format.</li>
 * <li>`LocalDateTime` objects (e.g., `DeletedAt`) are persisted as `TEXT` in the SQLite database
 * using a "dd-MMM-yyyy HH:mm" format.</li>
 * <li>`BigDecimal` objects (e.g., `BenefitAmount`) are stored as `REAL` (floating-point)
 * in the SQLite database. Precision considerations are managed during conversion.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>`Role` enum values are stored as `TEXT` in the SQLite database. Conversion between
 * `String` and `Role` enum uses the robust {@link Role#fromDbValue(String)} method.</li>
 * <li>**NEW**: `Program` enum values are stored as `TEXT` in the SQLite database. Conversion between
 * `String` and `Program` enum uses the robust {@link Program#fromDbValue(String)} method.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.2
 * Created On: 2025-07-22
 * Updated On: 2025-07-22 (Updated Program and Role to Enum handling, fixed method names)
 *
 * @see ParticipantDataAccess
 * @see Participant
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class ParticipantImplementation implements ParticipantDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code ParticipantImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(ParticipantImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database (for `DeletedAt`).
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    /**
     * <p>
     * Date formatter for converting between {@link LocalDate} objects in Java
     * and `TEXT` representation in the SQLite database (for `JoinDate`).
     * </p>
     * <p>
     * The pattern "yyyy-MM-dd" ensures a consistent format (e.g., "2025-07-22").
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new participant record. Loaded from `participant/insertParticipant.sql`. */
    private static final String SQL_CREATE_PARTICIPANT_RECORD;
    /** SQL query to select a participant record by its unique ID. Loaded from `participant/selectParticipantById.sql`. */
    private static final String SQL_READ_PARTICIPANT_RECORD;
    /** SQL query to select all participant records. Loaded from `participant/selectAllParticipants.sql`. */
    private static final String SQL_READ_ALL_PARTICIPANT_RECORDS;
    /** SQL query to count the total number of participant records. Loaded from `participant/countParticipants.sql`. */
    private static final String SQL_COUNT_PARTICIPANT_RECORDS;
    /** SQL query to check if a participant record with a given ID exists. Loaded from `participant/existsParticipantById.sql`. */
    private static final String SQL_EXISTS_PARTICIPANT_BY_ID;
    /** SQL query to update an existing participant record. Loaded from `participant/updateParticipant.sql`. */
    private static final String SQL_UPDATE_PARTICIPANT_RECORD;
    /** SQL query to soft-delete a participant record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `participant/deleteParticipantSoft.sql`. */
    private static final String SQL_DELETE_PARTICIPANT_SOFT;
    /** SQL query to select a participant record by their unique email address. Loaded from `participant/selectParticipantByEmail.sql`. */
    private static final String SQL_SELECT_PARTICIPANT_BY_EMAIL;
    /** SQL query to count the total number of active participant records. Loaded from `participant/countActiveParticipants.sql`. */
    private static final String SQL_COUNT_ACTIVE_PARTICIPANTS;
    /** SQL query to select all active participant records. Loaded from `participant/selectActiveParticipants.sql`. */
    private static final String SQL_SELECT_ACTIVE_PARTICIPANTS;
    /** SQL query to select participant records by their program. Loaded from `participant/selectParticipantsByProgram.sql`. */
    private static final String SQL_SELECT_PARTICIPANTS_BY_PROGRAM;
    /** SQL query to select participant records by their role. Loaded from `participant/selectParticipantsByRole.sql`. */
    private static final String SQL_SELECT_PARTICIPANTS_BY_ROLE;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            SQL_CREATE_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/insertParticipant.sql");
            SQL_READ_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/selectParticipantById.sql");
            SQL_READ_ALL_PARTICIPANT_RECORDS = QueryLoader.getQuery("participant/selectAllParticipants.sql");
            SQL_COUNT_PARTICIPANT_RECORDS = QueryLoader.getQuery("participant/countParticipants.sql");
            SQL_EXISTS_PARTICIPANT_BY_ID = QueryLoader.getQuery("participant/existsParticipantById.sql");
            SQL_UPDATE_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/updateParticipant.sql");
            SQL_DELETE_PARTICIPANT_SOFT = QueryLoader.getQuery("participant/deleteParticipantSoft.sql");
            SQL_SELECT_PARTICIPANT_BY_EMAIL = QueryLoader.getQuery("participant/selectParticipantByEmail.sql");
            SQL_COUNT_ACTIVE_PARTICIPANTS = QueryLoader.getQuery("participant/countActiveParticipants.sql");
            SQL_SELECT_ACTIVE_PARTICIPANTS = QueryLoader.getQuery("participant/selectActiveParticipants.sql");
            SQL_SELECT_PARTICIPANTS_BY_PROGRAM = QueryLoader.getQuery("participant/selectParticipantsByProgram.sql");
            SQL_SELECT_PARTICIPANTS_BY_ROLE = QueryLoader.getQuery("participant/selectParticipantsByRole.sql");
            logger.info("All SQL queries for ParticipantImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for ParticipantImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Participant} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code Participant} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `ParticipantID` and setting it via the `_setParticipantID` method.</li>
     * <li>String fields (e.g., `FirstName`, `MiddleName`, `LastName`, `Email`, `Phone`, `Notes`).</li>
     * <li>`BigDecimal` for `BenefitAmount` and `DistanceMiles`.</li>
     * <li>`LocalDate` for `JoinDate`.</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` `TEXT` field, parsing it into
     * {@link LocalDateTime} objects.</li>
     * <li>Mapping of foreign key IDs (`PickUpLocationID_FK`, `DropOffLocationID_FK`) to {@link Location} objects.</li>
     * <li>Mapping of `Role` enum using {@link Role#fromDbValue(String)}.</li>
     * <li>Mapping of `Program` enum using {@link Program#fromDbValue(String)}.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing participant data.
     * @return A fully populated {@link Participant} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private Participant mapResultSetToParticipant(ResultSet rs) throws SQLException {
        Participant participant = new Participant();
        Integer participantId = rs.getInt("ParticipantID");
        if (participantId > 0) { // SQLite getInt returns 0 for NULL for INTEGER PRIMARY KEY, check for positive valid ID
            participant._setParticipantID(participantId);
        }

        participant.setFirstName(rs.getString("FirstName"));
        participant.setMiddleName(rs.getString("MiddleName"));
        participant.setLastName(rs.getString("LastName"));
        participant.setEmail(rs.getString("Email"));
        participant.setPhone(rs.getString("Phone"));
        participant.setDistanceMiles(BigDecimal.valueOf(rs.getDouble("DistanceMiles"))); // Corrected

        // JoinDate
        String joinDateStr = rs.getString("JoinDate");
        participant.setJoinDate(joinDateStr != null && !joinDateStr.isEmpty() ?
                LocalDate.parse(joinDateStr, CUSTOM_DATE_FORMATTER) : null);

        // BenefitAmount
        participant.setBenefitAmount(BigDecimal.valueOf(rs.getDouble("BenefitAmount")));

        // Role Enum
        String roleStr = rs.getString("Role");
        participant.setRole(roleStr != null && !roleStr.isEmpty() ? Role.fromDbValue(roleStr) : null);

        // Program Enum
        String programStr = rs.getString("Program");
        participant.setProgram(programStr != null && !programStr.isEmpty() ? Program.fromDbValue(programStr) : null);

        // Location FKeys - Map to Location objects
        Integer pickUpLocationId = rs.getObject("PickUpLocationID_FK", Integer.class);
        if (pickUpLocationId != null) {
            Location pickUpLoc = new Location();
            pickUpLoc._setLocationID(pickUpLocationId); // Corrected to use _setLocationID
            participant.setPickUpLocation(pickUpLoc);
        } else {
            participant.setPickUpLocation(null);
        }

        Integer dropOffLocationId = rs.getObject("DropOffLocationID_FK", Integer.class);
        if (dropOffLocationId != null) {
            Location dropOffLoc = new Location();
            dropOffLoc._setLocationID(dropOffLocationId); // Corrected to use _setLocationID
            participant.setDropOffLocation(dropOffLoc);
        } else {
            participant.setDropOffLocation(null);
        }

        participant.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        participant.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ?
                LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        participant.setNotes(rs.getString("Notes"));

        return participant;
    }

    /**
     * <p>
     * Inserts a new {@link Participant} record into the SQLite database.
     * The database's `AUTOINCREMENT` feature automatically assigns a unique `ParticipantID`.
     * </p>
     * <p>
     * This method validates the provided {@code Participant} object and its mandatory fields
     * (`FirstName`, `LastName`, `Email`, `Phone`, `DistanceMiles`, `JoinDate`, `Program`, `Role`)
     * before attempting the insertion. It handles potential database errors, including unique constraint violations
     * for `Email`. Upon successful insertion, the database-generated `ParticipantID` is injected
     * back into the provided `Participant` object.
     * </p>
     *
     * @param participant The {@link Participant} object to be created. Its `ParticipantID` will be ignored if present,
     * as it's auto-generated by the database.
     * @return The created {@link Participant} object, updated with its database-assigned `ParticipantID`.
     * @throws DatabaseAccessException  if a database access error occurs during creation,
     * e.g., a unique constraint violation, or other SQL errors.
     * @throws NullPointerException     if the provided {@code participant} object or any of its
     * required `NOT NULL` fields are {@code null}.
     * @throws IllegalArgumentException if any mandatory string fields are empty after trimming,
     * or if foreign keys are invalid.
     */
    @Override
    public Participant createRecord(Participant participant) throws DatabaseAccessException {
        Objects.requireNonNull(participant, "Participant object cannot be null for creation.");
        Objects.requireNonNull(participant.getFirstName(), "First Name cannot be null for creation.");
        Objects.requireNonNull(participant.getLastName(), "Last Name cannot be null for creation.");
        Objects.requireNonNull(participant.getEmail(), "Email cannot be null for creation.");
        Objects.requireNonNull(participant.getPhone(), "Phone cannot be null for creation.");
        Objects.requireNonNull(participant.getDistanceMiles(), "Distance Miles cannot be null for creation.");
        Objects.requireNonNull(participant.getJoinDate(), "Join Date cannot be null for creation.");
        Objects.requireNonNull(participant.getProgram(), "Program cannot be null for creation.");
        Objects.requireNonNull(participant.getRole(), "Role cannot be null for creation.");
        Objects.requireNonNull(participant.getPickUpLocation(), "Pickup Location cannot be null for creation.");
        Objects.requireNonNull(participant.getDropOffLocation(), "Drop-off Location cannot be null for creation.");
        Objects.requireNonNull(participant.getPickUpLocation().getLocationID(), "Pickup Location ID cannot be null for creation."); // Corrected
        Objects.requireNonNull(participant.getDropOffLocation().getLocationID(), "Drop-off Location ID cannot be null for creation."); // Corrected


        if (participant.getFirstName().trim().isEmpty() ||
                participant.getLastName().trim().isEmpty() ||
                participant.getEmail().trim().isEmpty() ||
                participant.getPhone().trim().isEmpty()) {
            throw new IllegalArgumentException("Mandatory string fields (first name, last name, email, phone) cannot be empty for participant creation.");
        }
        // Removed redundant BigDecimal validation here, it's handled in Participant model setter

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_CREATE_PARTICIPANT_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, participant.getFirstName().trim());
            pstmt.setString(2, participant.getMiddleName() != null ? participant.getMiddleName().trim() : null);
            pstmt.setString(3, participant.getLastName().trim());
            pstmt.setString(4, participant.getEmail().trim());
            pstmt.setString(5, participant.getPhone().trim());
            pstmt.setDouble(6, participant.getDistanceMiles().doubleValue()); // Corrected
            pstmt.setString(7, participant.getJoinDate().format(CUSTOM_DATE_FORMATTER));
            // Corrected: Ensure benefit amount is handled as double for DB
            pstmt.setDouble(8, participant.getBenefitAmount() != null ? participant.getBenefitAmount().doubleValue() : 0.0);
            pstmt.setString(9, participant.getRole().name()); // Store enum name
            pstmt.setString(10, participant.getProgram().name()); // Store Program enum name

            // Location FKeys
            if (participant.getPickUpLocation() != null && participant.getPickUpLocation().getLocationID() != null) { // Corrected
                pstmt.setInt(11, participant.getPickUpLocation().getLocationID()); // Corrected
            } else {
                pstmt.setNull(11, Types.INTEGER);
            }

            if (participant.getDropOffLocation() != null && participant.getDropOffLocation().getLocationID() != null) { // Corrected
                pstmt.setInt(12, participant.getDropOffLocation().getLocationID()); // Corrected
            } else {
                pstmt.setNull(12, Types.INTEGER);
            }

            pstmt.setInt(13, participant.getIsActive() ? 1 : 0);

            if (participant.getDeletedAt() != null) {
                pstmt.setString(14, participant.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(14, Types.VARCHAR);
            }

            pstmt.setString(15, participant.getNotes() != null ? participant.getNotes().trim() : null);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.error("Creating participant failed, no rows affected for email: {}.");
                throw new DatabaseAccessException("Creating participant failed, no rows affected.");
            }

            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    participant._setParticipantID(generatedKeys.getInt(1));
                    logger.info("Participant created successfully with ID: {}.", participant.getParticipantID());
                } else {
                    logger.error("Creating participant failed, no ID obtained for email: {}.");
                    throw new DatabaseAccessException("Creating participant failed, no ID obtained.");
                }
            }
            return participant;

        } catch (SQLException e) {
            logger.error("Error creating participant '{}': {}", participant.getEmail(), e.getMessage(), e);
            if (e.getErrorCode() == 19) { // SQLite unique constraint violation
                String errorMessage = "Failed to create participant. It might already exist or a unique constraint was violated.";
                if (e.getMessage().contains("UNIQUE constraint failed: Participants.Email")) {
                    errorMessage = "Participant with email '" + participant.getEmail() + "' already exists. Email addresses must be unique.";
                }
                throw new DatabaseAccessException(errorMessage, e);
            }
            throw new DatabaseAccessException("Failed to create participant: " + e.getMessage(), e);
        } catch (IllegalArgumentException | IllegalStateException e) {
            logger.error("Participant validation/state error during creation for email '{}': {}", participant.getEmail(), e.getMessage(), e);
            throw new DatabaseAccessException("Participant data is invalid or in an illegal state for creation: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Retrieves a single {@link Participant} record from the database by its unique identifier (`ParticipantID`).
     * </p>
     *
     * @param id The unique integer ID of the participant to retrieve. Must not be {@code null} and must be positive.
     * @return An {@link Optional} containing the {@link Participant} object if a participant with the given ID is found,
     * or an empty {@link Optional} if no such participant exists.
     * @throws DatabaseAccessException  if a database access error occurs during retrieval.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public Optional<Participant> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for retrieval.");
        if (id <= 0) {
            throw new IllegalArgumentException("Participant ID must be positive for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_PARTICIPANT_RECORD)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToParticipant(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving participant by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve participant by ID " + id + ": " + e.getMessage(), e);
        }
        return Optional.empty();
    }

    /**
     * <p>
     * Retrieves all {@link Participant} records currently stored in the database.
     * </p>
     *
     * @return A {@link List} of {@link Participant} objects. The list will be empty if no participants are found.
     * @throws DatabaseAccessException if a database access error occurs during retrieval.
     */
    @Override
    public List<Participant> readRecordAll() throws DatabaseAccessException {
        List<Participant> participants = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_READ_ALL_PARTICIPANT_RECORDS)) {

            while (rs.next()) {
                participants.add(mapResultSetToParticipant(rs));
            }
        } catch (SQLException e) {
            logger.error("Error retrieving all participants: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve all participants: " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * <p>
     * Counts the total number of participant records in the database.
     * </p>
     *
     * @return The total count of participants as a {@code long}. Returns 0 if no participants are found
     * or if an error occurs.
     * @throws DatabaseAccessException if a database access error occurs during counting.
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_COUNT_PARTICIPANT_RECORDS)) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            logger.error("Error counting participants: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to count participants: " + e.getMessage(), e);
        }
        return 0;
    }

    /**
     * <p>
     * Checks if a participant record with the specified ID exists in the database.
     * </p>
     *
     * @param id The unique integer ID of the participant to check for existence. Must not be {@code null} and must be positive.
     * @return {@code true} if a participant with the given ID exists, {@code false} otherwise.
     * @throws DatabaseAccessException  if a database access error occurs during the existence check.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for existence check.");
        if (id <= 0) {
            throw new IllegalArgumentException("Participant ID must be positive for existence check.");
        }
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_EXISTS_PARTICIPANT_BY_ID)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next();
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of participant by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to check existence of participant by ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Updates an existing {@link Participant} record in the database. The update operation is
     * based on the `ParticipantID` of the provided {@link Participant} object.
     * </p>
     * <p>
     * This method validates the provided {@code Participant} object and its mandatory fields
     * before execution. It specifically handles unique constraint violations if the updated
     * participant details (e.g., `Email`) conflict with an existing record's unique attributes.
     * </p>
     *
     * @param participant The {@link Participant} object containing the updated data.
     * Its `ParticipantID` must not be {@code null} and must be positive to identify the record to update.
     * @throws DatabaseAccessException  if a database access error occurs during the update.
     * @throws NullPointerException     if the provided {@code participant} object itself, its `ParticipantID`,
     * or any of its required `NOT NULL` fields are {@code null}.
     * @throws IllegalArgumentException if the `ParticipantID` is non-positive, if any
     * mandatory string fields are empty after trimming, or if foreign keys are invalid.
     */
    @Override
    public void updateRecord(Participant participant) throws DatabaseAccessException {
        Objects.requireNonNull(participant, "Participant object cannot be null for update.");
        Objects.requireNonNull(participant.getParticipantID(), "Participant ID cannot be null for update.");
        if (participant.getParticipantID() <= 0) {
            throw new IllegalArgumentException("Participant ID must be positive for update.");
        }
        Objects.requireNonNull(participant.getFirstName(), "First Name cannot be null for update.");
        Objects.requireNonNull(participant.getLastName(), "Last Name cannot be null for update.");
        Objects.requireNonNull(participant.getEmail(), "Email cannot be null for update.");
        Objects.requireNonNull(participant.getPhone(), "Phone cannot be null for update.");
        Objects.requireNonNull(participant.getDistanceMiles(), "Distance Miles cannot be null for update.");
        Objects.requireNonNull(participant.getJoinDate(), "Join Date cannot be null for update.");
        Objects.requireNonNull(participant.getProgram(), "Program cannot be null for update.");
        Objects.requireNonNull(participant.getRole(), "Role cannot be null for update.");
        Objects.requireNonNull(participant.getPickUpLocation(), "Pickup Location cannot be null for update.");
        Objects.requireNonNull(participant.getDropOffLocation(), "Drop-off Location cannot be null for update.");
        Objects.requireNonNull(participant.getPickUpLocation().getLocationID(), "Pickup Location ID cannot be null for update."); // Corrected
        Objects.requireNonNull(participant.getDropOffLocation().getLocationID(), "Drop-off Location ID cannot be null for update."); // Corrected


        if (participant.getFirstName().trim().isEmpty() ||
                participant.getLastName().trim().isEmpty() ||
                participant.getEmail().trim().isEmpty() ||
                participant.getPhone().trim().isEmpty()) {
            throw new IllegalArgumentException("Mandatory string fields (first name, last name, email, phone) cannot be empty for participant update.");
        }
        // Removed redundant BigDecimal validation here, it's handled in Participant model setter

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_UPDATE_PARTICIPANT_RECORD)) {

            pstmt.setString(1, participant.getFirstName().trim());
            pstmt.setString(2, participant.getMiddleName() != null ? participant.getMiddleName().trim() : null);
            pstmt.setString(3, participant.getLastName().trim());
            pstmt.setString(4, participant.getEmail().trim());
            pstmt.setString(5, participant.getPhone().trim());
            pstmt.setDouble(6, participant.getDistanceMiles().doubleValue()); // Corrected
            pstmt.setString(7, participant.getJoinDate().format(CUSTOM_DATE_FORMATTER));
            // Corrected: Ensure benefit amount is handled as double for DB
            pstmt.setDouble(8, participant.getBenefitAmount() != null ? participant.getBenefitAmount().doubleValue() : 0.0);
            pstmt.setString(9, participant.getRole().name()); // Store enum name
            pstmt.setString(10, participant.getProgram().name()); // Store Program enum name

            // Location FKeys
            if (participant.getPickUpLocation() != null && participant.getPickUpLocation().getLocationID() != null) { // Corrected
                pstmt.setInt(11, participant.getPickUpLocation().getLocationID()); // Corrected
            } else {
                pstmt.setNull(11, Types.INTEGER);
            }

            if (participant.getDropOffLocation() != null && participant.getDropOffLocation().getLocationID() != null) { // Corrected
                pstmt.setInt(12, participant.getDropOffLocation().getLocationID()); // Corrected
            } else {
                pstmt.setNull(12, Types.INTEGER);
            }

            pstmt.setInt(13, participant.getIsActive() ? 1 : 0);

            if (participant.getDeletedAt() != null) {
                pstmt.setString(14, participant.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(14, Types.VARCHAR);
            }

            pstmt.setString(15, participant.getNotes() != null ? participant.getNotes().trim() : null);
            pstmt.setInt(16, participant.getParticipantID()); // WHERE clause ID

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Update participant with ID {} affected 0 rows. Participant might not exist or data was identical.", participant.getParticipantID());
                throw new DatabaseAccessException("Participant with ID " + participant.getParticipantID() + " not found for update or no changes were made.");
            } else {
                logger.info("Participant with ID {} updated successfully. Affected rows: {}.", participant.getParticipantID(), affectedRows);
            }

        } catch (SQLException e) {
            logger.error("Error updating participant with ID {}: {}", participant.getParticipantID(), e.getMessage(), e);
            if (e.getErrorCode() == 19) { // SQLite unique constraint violation
                String errorMessage = "Failed to update participant. It might already exist or a unique constraint was violated.";
                if (e.getMessage().contains("UNIQUE constraint failed: Participants.Email")) {
                    errorMessage = "Participant with email '" + participant.getEmail() + "' already exists. Email addresses must be unique.";
                }
                throw new DatabaseAccessException(errorMessage, e);
            }
            throw new DatabaseAccessException("Failed to update participant with ID " + participant.getParticipantID() + ": " + e.getMessage(), e);
        } catch (IllegalArgumentException e) {
            logger.error("Participant validation error during update for participant ID {}: {}", participant.getParticipantID(), e.getMessage(), e);
            throw new DatabaseAccessException("Participant data is invalid for update: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Soft-deletes a {@link Participant} record from the database by setting its `IsActive` flag
     * to `0` (false) and updating the `DeletedAt` timestamp to the current date and time.
     * This method does not physically remove the record, preserving historical data.
     * </p>
     *
     * @param id The unique integer ID of the participant to soft-delete. Must not be {@code null} and must be positive.
     * @throws DatabaseAccessException  if a database access error occurs during the soft-deletion.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for deletion.");
        if (id <= 0) {
            throw new IllegalArgumentException("Participant ID must be positive for deletion.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_DELETE_PARTICIPANT_SOFT)) {

            pstmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            pstmt.setInt(2, id);

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Soft-delete participant with ID {} affected 0 rows. Participant might not exist or already soft-deleted.", id);
                throw new DatabaseAccessException("Participant with ID " + id + " not found for soft-deletion or already deleted.");
            } else {
                logger.info("Participant with ID {} soft-deleted successfully (IsActive=0, DeletedAt={}).", id, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting participant with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to soft-delete participant with ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Finds a single {@link Participant} record by their unique email address.
     * </p>
     *
     * @param email The unique email address string to search for. Must not be {@code null} or empty.
     * @return An {@link Optional} containing the {@link Participant} object if a participant with the given email is found,
     * or an empty {@link Optional} if no such participant exists.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code email} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code email} is an empty string after trimming.
     */
    @Override
    public Optional<Participant> findByEmail(String email) throws DatabaseAccessException {
        Objects.requireNonNull(email, "Email cannot be null for retrieval.");
        String trimmedEmail = email.trim();
        if (trimmedEmail.isEmpty()) {
            throw new IllegalArgumentException("Email cannot be empty for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_PARTICIPANT_BY_EMAIL)) {

            pstmt.setString(1, trimmedEmail);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToParticipant(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving participant by email '{}': {}", trimmedEmail, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve participant by email '" + trimmedEmail + "': " + e.getMessage(), e);
        }
        return Optional.empty();
    }

    /**
     * <p>
     * Counts the total number of active participant records in the database.
     * Active participants are those with `IsActive` flag set to `1`.
     * </p>
     *
     * @return The total count of active participants as a {@code long}. Returns 0 if no active participants are found
     * or if an error occurs.
     * @throws DatabaseAccessException If a database access error occurs during counting.
     */
    @Override
    public long countActiveParticipants() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_COUNT_ACTIVE_PARTICIPANTS)) {

            if (rs.next()) {
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            logger.error("Error counting active participants: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to count active participants: " + e.getMessage(), e);
        }
        return 0;
    }

    /**
     * <p>
     * Retrieves a list of all participants who are currently marked as active (`IsActive = 1`).
     * </p>
     *
     * @return A {@link List} of active {@link Participant} objects. Returns an empty list
     * if no active participants are found.
     * @throws DatabaseAccessException If a database access error occurs during retrieval.
     */
    @Override
    public List<Participant> findActiveParticipants() throws DatabaseAccessException {
        List<Participant> participants = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(SQL_SELECT_ACTIVE_PARTICIPANTS)) {

            while (rs.next()) {
                participants.add(mapResultSetToParticipant(rs));
            }
        } catch (SQLException e) {
            logger.error("Error retrieving all active participants: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve all active participants: " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * <p>
     * Retrieves a list of participants associated with a specific program.
     * </p>
     *
     * @param program The {@link Program} enum to filter by (e.g., `Program.TRANSPORTATION_INCENTIVE_PROGRAM`, `Program.DAILY`, `Program.NONE`).
     * Must not be {@code null}.
     * @return A {@link List} of {@link Participant} objects in the specified program.
     * @throws DatabaseAccessException If a database access error occurs during retrieval.
     * @throws NullPointerException If the provided {@code program} is {@code null}.
     */
    @Override
    public List<Participant> findByProgram(Program program) throws DatabaseAccessException {
        Objects.requireNonNull(program, "Program cannot be null for retrieval.");

        List<Participant> participants = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_PARTICIPANTS_BY_PROGRAM)) {

            pstmt.setString(1, program.name()); // Store enum name
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    participants.add(mapResultSetToParticipant(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving participants by program '{}': {}", program.name(), e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve participants by program '" + program.name() + "': " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * <p>
     * Retrieves a list of participants based on their role within the vanpool.
     * </p>
     *
     * @param role The role enum to filter by (e.g., `Role.PARTICIPANT`, `Role.COORDINATOR`).
     * Must not be {@code null}.
     * @return A {@link List} of {@link Participant} objects with the specified role.
     * @throws DatabaseAccessException If a database access error occurs during retrieval.
     * @throws NullPointerException If the provided {@code role} is {@code null}.
     */
    @Override
    public List<Participant> findByRole(Role role) throws DatabaseAccessException {
        Objects.requireNonNull(role, "Role cannot be null for retrieval.");

        List<Participant> participants = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_PARTICIPANTS_BY_ROLE)) {

            pstmt.setString(1, role.name()); // Store enum name
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    participants.add(mapResultSetToParticipant(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving participants by role '{}': {}", role.name(), e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve participants by role '" + role.name() + "': " + e.getMessage(), e);
        }
        return participants;
    }
}