package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Participant;
import com.avaruusstudios.vmdb.model.Location; // Needed for foreign key relationships, though not directly mapped here
import com.avaruusstudios.vmdb.model.Role; // Assuming Role enum is in this package
import com.avaruusstudios.vmdb.model.Program; // New import for Program enum
import com.avaruusstudios.vmdb.data.ParticipantDataAccess;
import com.avaruusstudios.vmdb.data.DeleteDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link ParticipantDataAccess} interface for managing
 * {@link Participant} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Participant} entities (e.g., finding by email, counting/retrieving
 * active participants, or filtering by program/role).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Participant IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `Email` is enforced at the database level.</li>
 * <li>Deletion of participant records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDate` objects (e.g., `JoinDate`) are persisted as `TEXT` in the SQLite database
 * using a "yyyy-MM-dd" format.</li>
 * <li>`LocalDateTime` objects (e.g., `DeletedAt`) are persisted as `TEXT` in the SQLite database
 * using a "dd-MMM-yyyy HH:mm" format.</li>
 * <li>`BigDecimal` objects (e.g., `BenefitAmount`) are stored as `REAL` (floating-point)
 * in the SQLite database. Precision considerations are managed during conversion.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>`Role` enum values are stored as `TEXT` in the SQLite database. Conversion between
 * `String` and `Role` enum uses the robust {@link Role#fromDbValue(String)} method.</li>
 * <li>**NEW**: `Program` enum values are stored as `TEXT` in the SQLite database. Conversion between
 * `String` and `Program` enum uses the robust {@link Program#fromDbValue(String)} method.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.2
 * Created On: 2025-07-22
 * Updated On: 2025-07-22 (Updated Program and Role to Enum handling, fixed method names)
 *
 * @see ParticipantDataAccess
 * @see Participant
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class ParticipantImplementation implements ParticipantDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code ParticipantImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(ParticipantImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database (for `DeletedAt`).
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    /**
     * <p>
     * Date formatter for converting between {@link LocalDate} objects in Java
     * and `TEXT` representation in the SQLite database (for `JoinDate`).
     * </p>
     * <p>
     * The pattern "yyyy-MM-dd" ensures a consistent format (e.g., "2025-07-22").
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new participant record. Loaded from `participant/insertParticipant.sql`. */
    private static final String SQL_CREATE_PARTICIPANT_RECORD;
    /** SQL query to select a participant record by its unique ID. Loaded from `participant/selectParticipantById.sql`. */
    private static final String SQL_READ_PARTICIPANT_RECORD;
    /** SQL query to select all participant records. Loaded from `participant/selectAllParticipants.sql`. */
    private static final String SQL_READ_ALL_PARTICIPANT_RECORDS;
    /** SQL query to count the total number of participant records. Loaded from `participant/countParticipants.sql`. */
    private static final String SQL_COUNT_PARTICIPANT_RECORDS;
    /** SQL query to check if a participant record with a given ID exists. Loaded from `participant/existsParticipantById.sql`. */
    private static final String SQL_EXISTS_PARTICIPANT_BY_ID;
    /** SQL query to update an existing participant record. Loaded from `participant/updateParticipant.sql`. */
    private static final String SQL_UPDATE_PARTICIPANT_RECORD;
    /** SQL query to soft-delete a participant record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `participant/deleteParticipantSoft.sql`. */
    private static final String SQL_DELETE_PARTICIPANT_SOFT;
    /** SQL query to select a participant record by their unique email address. Loaded from `participant/selectParticipantByEmail.sql`. */
    private static final String SQL_SELECT_PARTICIPANT_BY_EMAIL;
    /** SQL query to count the total number of active participant records. Loaded from `participant/countActiveParticipants.sql`. */
    private static final String SQL_COUNT_ACTIVE_PARTICIPANTS;
    /** SQL query to select all active participant records. Loaded from `participant/selectActiveParticipants.sql`. */
    private static final String SQL_SELECT_ACTIVE_PARTICIPANTS;
    /** SQL query to select participant records by their program. Loaded from `participant/selectParticipantsByProgram.sql`. */
    private static final String SQL_SELECT_PARTICIPANTS_BY_PROGRAM;
    /** SQL query to select participant records by their role. Loaded from `participant/selectParticipantsByRole.sql`. */
    private static final String SQL_SELECT_PARTICIPANTS_BY_ROLE;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            SQL_CREATE_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/insertParticipant.sql");
            SQL_READ_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/selectParticipantById.sql");
            SQL_READ_ALL_PARTICIPANT_RECORDS = QueryLoader.getQuery("participant/selectAllParticipants.sql");
            SQL_COUNT_PARTICIPANT_RECORDS = QueryLoader.getQuery("participant/countParticipants.sql");
            SQL_EXISTS_PARTICIPANT_BY_ID = QueryLoader.getQuery("participant/existsParticipantById.sql");
            SQL_UPDATE_PARTICIPANT_RECORD = QueryLoader.getQuery("participant/updateParticipant.sql");
            SQL_DELETE_PARTICIPANT_SOFT = QueryLoader.getQuery("participant/deleteParticipantSoft.sql");
            SQL_SELECT_PARTICIPANT_BY_EMAIL = QueryLoader.getQuery("participant/selectParticipantByEmail.sql");
            SQL_COUNT_ACTIVE_PARTICIPANTS = QueryLoader.getQuery("participant/countActiveParticipants.sql");
            SQL_SELECT_ACTIVE_PARTICIPANTS = QueryLoader.getQuery("participant/selectActiveParticipants.sql");
            SQL_SELECT_PARTICIPANTS_BY_PROGRAM = QueryLoader.getQuery("participant/selectParticipantsByProgram.sql");
            SQL_SELECT_PARTICIPANTS_BY_ROLE = QueryLoader.getQuery("participant/selectParticipantsByRole.sql");
            logger.info("All SQL queries for ParticipantImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for ParticipantImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Participant} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code Participant} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `ParticipantID` and setting it via the `_setParticipantID` method.</li>
     * <li>String fields (e.g., `FirstName`, `MiddleName`, `LastName`, `Email`, `Phone`, `Notes`).</li>
     * <li>`BigDecimal` for `BenefitAmount` and `DistanceMiles`.</li>
     * <li>`LocalDate` for `JoinDate`.</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` `TEXT` field, parsing it into
     * {@link LocalDateTime} objects.</li>
     * <li>Mapping of foreign key IDs (`PickUpLocationID_FK`, `DropOffLocationID_FK`) to {@link Location} objects.</li>
     * <li>Mapping of `Role` enum using {@link Role#fromDbValue(String)}.</li>
     * <li>Mapping of `Program` enum using {@link Program#fromDbValue(String)}.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing participant data.
     * @return A fully populated {@link Participant} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private Participant mapResultSetToParticipant(ResultSet rs) throws SQLException {
        Participant participant = new Participant();
        Integer participantId = rs.getInt("ParticipantID");
        if (participantId > 0) { // SQLite getInt returns 0 for NULL for INTEGER PRIMARY KEY, check for positive valid ID
            participant._setParticipantID(participantId);
        }

        participant.setFirstName(rs.getString("FirstName"));
        participant.setMiddleName(rs.getString("MiddleName"));
        participant.setLastName(rs.getString("LastName"));
        participant.setEmail(rs.getString("Email"));
        participant.setPhone(rs.getString("Phone"));
        participant.setDistanceMiles(BigDecimal.valueOf(rs.getDouble("DistanceMiles"))); // Corrected

        // JoinDate
        String joinDateStr = rs.getString("JoinDate");
        participant.setJoinDate(joinDateStr != null && !joinDateStr.isEmpty() ? LocalDate.parse(joinDateStr, CUSTOM_DATE_FORMATTER) : null);

        // BenefitAmount
        participant.setBenefitAmount(BigDecimal.valueOf(rs.getDouble("BenefitAmount")));

        // Role Enum
        String roleStr = rs.getString("Role");
        participant.setRole(roleStr != null && !roleStr.isEmpty() ? Role.fromDbValue(roleStr) : null);

        // Program Enum
        String programStr = rs.getString("Program");
        participant.setProgram(programStr != null && !programStr.isEmpty() ? Program.fromDbValue(programStr) : null);

        // Location FKeys - Map to Location objects
        Integer pickUpLocationId = rs.getObject("PickUpLocationID_FK", Integer.class);
        if (pickUpLocationId != null) {
            Location pickUpLoc = new Location();
            pickUpLoc._setLocationID(pickUpLocationId); // Corrected to use _setLocationID
            participant.setPickUpLocation(pickUpLoc);
        } else {
            participant.setPickUpLocation(null);
        }

        Integer dropOffLocationId = rs.getObject("DropOffLocationID_FK", Integer.class);
        if (dropOffLocationId != null) {
            Location dropOffLoc = new Location();
            dropOffLoc._setLocationID(dropOffLocationId); // Corrected to use _setLocationID
            participant.setDropOffLocation(dropOffLoc);
        } else {
            participant.setDropOffLocation(null);
        }

        participant.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        participant.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ? LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        participant.setNotes(rs.getString("Notes"));

        return participant;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Participant createRecord(Participant participant) throws DatabaseAccessException {
        Objects.requireNonNull(participant, "Participant object cannot be null for creation.");
        if (participant.getParticipantID() != null) {
            throw new IllegalArgumentException("Participant ID must be null for new participant creation (auto-generated).");
        }

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_CREATE_PARTICIPANT_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, participant.getFirstName());
            stmt.setString(2, participant.getMiddleName());
            stmt.setString(3, participant.getLastName());
            stmt.setString(4, participant.getEmail());
            stmt.setString(5, participant.getPhone());

            if (participant.getDistanceMiles() != null) {
                stmt.setDouble(6, participant.getDistanceMiles().doubleValue());
            } else {
                stmt.setNull(6, Types.REAL);
            }

            stmt.setString(7, participant.getJoinDate() != null ? participant.getJoinDate().format(CUSTOM_DATE_FORMATTER) : null);

            if (participant.getBenefitAmount() != null) {
                stmt.setDouble(8, participant.getBenefitAmount().doubleValue());
            } else {
                stmt.setNull(8, Types.REAL);
            }

            stmt.setString(9, participant.getRole() != null ? participant.getRole().getDbValue() : null);
            stmt.setString(10, participant.getProgram() != null ? participant.getProgram().getDbValue() : null);

            if (participant.getPickUpLocation() != null && participant.getPickUpLocation().getLocationID() != null) {
                stmt.setInt(11, participant.getPickUpLocation().getLocationID());
            } else {
                stmt.setNull(11, Types.INTEGER);
            }

            if (participant.getDropOffLocation() != null && participant.getDropOffLocation().getLocationID() != null) {
                stmt.setInt(12, participant.getDropOffLocation().getLocationID());
            } else {
                stmt.setNull(12, Types.INTEGER);
            }

            stmt.setInt(13, participant.getIsActive() ? 1 : 0); // true = 1, false = 0
            stmt.setString(14, participant.getDeletedAt() != null ? participant.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(15, participant.getNotes());

            logger.debug("Executing insert participant query for participant: {} {}", participant.getFirstName(), participant.getLastName());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.error("Creating participant failed, no rows affected for participant: {} {}", participant.getFirstName(), participant.getLastName());
                throw new DatabaseAccessException("Creating participant failed, no rows affected.");
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    Integer generatedId = generatedKeys.getInt(1);
                    participant._setParticipantID(generatedId); // Set the auto-generated ID
                    logger.info("Successfully created participant with ID: {}", generatedId);
                    return participant;
                } else {
                    logger.error("Creating participant failed, no ID obtained for participant: {} {}", participant.getFirstName(), participant.getLastName());
                    throw new DatabaseAccessException("Creating participant failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            logger.error("Error creating participant record: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error creating participant record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For this application, implementations of this method are expected to perform a
     * **soft-delete** rather than physically removing the record from the database.
     * This typically involves updating an `IsActive` flag to `0` and/or setting a
     * `DeletedAt` timestamp to the current time. This strategy preserves data integrity
     * for historical, auditing, and referential purposes, and allows for potential recovery.
     * </p>
     *
     * <p>
     * If no record matches the provided ID, the operation will typically complete
     * without throwing an error, but no rows will be affected. Implementations
     * might log a warning or return a boolean indicating success if desired.
     * </p>
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for deletion.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_DELETE_PARTICIPANT_SOFT)) {

            stmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // Set DeletedAt
            stmt.setInt(2, id); // Where ParticipantID = ?

            logger.debug("Executing soft-delete participant query for ID: {}", id);
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No participant found with ID: {} for soft-deletion.", id);
            } else {
                logger.info("Successfully soft-deleted participant with ID: {}", id);
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting participant record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error soft-deleting participant record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The result is wrapped in an {@code Optional<Participant>} to clearly indicate whether
     * an entity matching the given ID was found. This prevents {@code NullPointerExceptions}
     * and encourages explicit handling of cases where the record might not exist.
     * </p>
     */
    @Override
    public Optional<Participant> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for reading.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_PARTICIPANT_RECORD)) {

            stmt.setInt(1, id);
            logger.debug("Executing read participant query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Participant participant = mapResultSetToParticipant(rs);
                    logger.info("Found participant with ID: {}", id);
                    return Optional.of(participant);
                } else {
                    logger.info("No participant found with ID: {}", id);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error reading participant record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error reading participant record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The order of the returned records is dependent on the underlying database and
     * the SQL query used by the concrete implementation (e.g., if no specific
     * ORDER BY clause is applied, the order might not be guaranteed).
     * </p>
     */
    @Override
    public List<Participant> readRecordAll() throws DatabaseAccessException {
        List<Participant> participants = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_ALL_PARTICIPANT_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing read all participants query.");
            while (rs.next()) {
                participants.add(mapResultSetToParticipant(rs));
            }
            logger.info("Found {} total participants.", participants.size());
        } catch (SQLException e) {
            logger.error("Error reading all participant records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error reading all participant records: " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_PARTICIPANT_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total participant record count: {}", count);
                return count;
            }
            return 0; // Should not happen if query returns 0, but as a safeguard
        } catch (SQLException e) {
            logger.error("Error counting participant records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting participant records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Participant ID cannot be null for existence check.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_EXISTS_PARTICIPANT_BY_ID)) {

            stmt.setInt(1, id);
            logger.debug("Executing existsById participant query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                boolean exists = rs.next();
                logger.info("Participant with ID {} exists: {}", id, exists);
                return exists;
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of participant record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error checking existence of participant record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For the update operation to succeed, the {@code participant} object passed as a parameter
     * *must* have its primary key field set. This ID is used to identify which existing
     * record in the database should be updated. All other fields in the {@code participant}
     * object will be used to update the corresponding columns in the database.
     * </p>
     */
    @Override
    public void updateRecord(Participant participant) throws DatabaseAccessException {
        Objects.requireNonNull(participant, "Participant object cannot be null for update.");
        Objects.requireNonNull(participant.getParticipantID(), "Participant ID must not be null for update.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_UPDATE_PARTICIPANT_RECORD)) {

            stmt.setString(1, participant.getFirstName());
            stmt.setString(2, participant.getMiddleName());
            stmt.setString(3, participant.getLastName());
            stmt.setString(4, participant.getEmail());
            stmt.setString(5, participant.getPhone());

            if (participant.getDistanceMiles() != null) {
                stmt.setDouble(6, participant.getDistanceMiles().doubleValue());
            } else {
                stmt.setNull(6, Types.REAL);
            }

            stmt.setString(7, participant.getJoinDate() != null ? participant.getJoinDate().format(CUSTOM_DATE_FORMATTER) : null);

            if (participant.getBenefitAmount() != null) {
                stmt.setDouble(8, participant.getBenefitAmount().doubleValue());
            } else {
                stmt.setNull(8, Types.REAL);
            }

            stmt.setString(9, participant.getRole() != null ? participant.getRole().getDbValue() : null);
            stmt.setString(10, participant.getProgram() != null ? participant.getProgram().getDbValue() : null);

            if (participant.getPickUpLocation() != null && participant.getPickUpLocation().getLocationID() != null) {
                stmt.setInt(11, participant.getPickUpLocation().getLocationID());
            } else {
                stmt.setNull(11, Types.INTEGER);
            }

            if (participant.getDropOffLocation() != null && participant.getDropOffLocation().getLocationID() != null) {
                stmt.setInt(12, participant.getDropOffLocation().getLocationID());
            } else {
                stmt.setNull(12, Types.INTEGER);
            }

            stmt.setInt(13, participant.getIsActive() ? 1 : 0);
            stmt.setString(14, participant.getDeletedAt() != null ? participant.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(15, participant.getNotes());
            stmt.setInt(16, participant.getParticipantID()); // WHERE clause

            logger.debug("Executing update participant query for ID: {}", participant.getParticipantID());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No participant found with ID: {} for update. Update operation resulted in 0 affected rows.", participant.getParticipantID());
                throw new DatabaseAccessException("Participant with ID " + participant.getParticipantID() + " not found for update.");
            } else {
                logger.info("Successfully updated participant with ID: {}", participant.getParticipantID());
            }
        } catch (SQLException e) {
            logger.error("Error updating participant record with ID {}: {}", participant.getParticipantID(), e.getMessage(), e);
            throw new DatabaseAccessException("Error updating participant record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Participant> findByEmail(String email) throws DatabaseAccessException {
        Objects.requireNonNull(email, "Email cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_PARTICIPANT_BY_EMAIL)) {

            stmt.setString(1, email);
            logger.debug("Executing query: {} with email: {}", SQL_SELECT_PARTICIPANT_BY_EMAIL, email);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Participant participant = mapResultSetToParticipant(rs);
                    logger.info("Found participant with email: {}", email);
                    return Optional.of(participant);
                } else {
                    logger.info("No participant found with email: {}", email);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding participant by email {}: {}", email, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding participant by email: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long countActiveParticipants() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_ACTIVE_PARTICIPANTS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total active participant record count: {}", count);
                return count;
            }
            return 0;
        } catch (SQLException e) {
            logger.error("Error counting active participant records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting active participant records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Participant> findActiveParticipants() throws DatabaseAccessException {
        List<Participant> participants = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_ACTIVE_PARTICIPANTS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing find active participants query.");
            while (rs.next()) {
                participants.add(mapResultSetToParticipant(rs));
            }
            logger.info("Found {} active participants.", participants.size());
        } catch (SQLException e) {
            logger.error("Error finding active participant records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error finding active participant records: " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Participant> findByProgram(Program program) throws DatabaseAccessException {
        Objects.requireNonNull(program, "Program cannot be null for finding participants by program.");
        List<Participant> participants = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_PARTICIPANTS_BY_PROGRAM)) {

            stmt.setString(1, program.getDbValue());
            logger.debug("Executing find participants by program query for program: {}", program.getDbValue());
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    participants.add(mapResultSetToParticipant(rs));
                }
            }
            logger.info("Found {} participants for program: {}", participants.size(), program.getDbValue());
        } catch (SQLException e) {
            logger.error("Error finding participants by program {}: {}", program.getDbValue(), e.getMessage(), e);
            throw new DatabaseAccessException("Error finding participants by program: " + e.getMessage(), e);
        }
        return participants;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Participant> findByRole(Role role) throws DatabaseAccessException {
        Objects.requireNonNull(role, "Role cannot be null for finding participants by role.");
        List<Participant> participants = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_PARTICIPANTS_BY_ROLE)) {

            stmt.setString(1, role.getDbValue());
            logger.debug("Executing find participants by role query for role: {}", role.getDbValue());
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    participants.add(mapResultSetToParticipant(rs));
                }
            }
            logger.info("Found {} participants for role: {}", participants.size(), role.getDbValue());
        } catch (SQLException e) {
            logger.error("Error finding participants by role {}: {}", role.getDbValue(), e.getMessage(), e);
            throw new DatabaseAccessException("Error finding participants by role: " + e.getMessage(), e);
        }
        return participants;
    }
}