package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.User;
import com.avaruusstudios.vmdb.model.Role;
import com.avaruusstudios.vmdb.data.UserDataAccess;
import com.avaruusstudios.vmdb.data.DeleteDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link UserDataAccess} interface for managing
 * {@link User} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via {@link DeleteDataAccess}, along with
 * specific queries for {@code User} entities (e.g., finding by Windows username or role).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>User IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `WindowsUsername` is enforced at the database level via a unique constraint.</li>
 * <li>Deletion of user records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0
 * Created On: 2025-07-14
 * Updated On: 2025-07-14
 *
 * @see UserDataAccess
 * @see User
 * @see Role
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see DeleteDataAccess
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 */
public class UserImplementation implements UserDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code UserImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(UserImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new user record. Loaded from `user/insertUser.sql`. */
    private static final String SQL_CREATE_USER_RECORD;
    /** SQL query to select a user record by its unique ID. Loaded from `user/selectUserById.sql`. */
    private static final String SQL_READ_USER_RECORD;
    /** SQL query to select all user records. Loaded from `user/selectAllUsers.sql`. */
    private static final String SQL_READ_ALL_USER_RECORDS;
    /** SQL query to count the total number of user records. Loaded from `user/countUsers.sql`. */
    private static final String SQL_COUNT_USER_RECORDS;
    /** SQL query to check if a user record with a given ID exists. Loaded from `user/existsUserById.sql`. */
    private static final String SQL_EXISTS_USER_BY_ID;
    /** SQL query to update an existing user record. Loaded from `user/updateUser.sql`. */
    private static final String SQL_UPDATE_USER_RECORD;
    /** SQL query to soft-delete a user record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `user/deleteUserSoft.sql`. */
    private static final String SQL_DELETE_USER_SOFT;
    /** SQL query to select a user record by their unique Windows username. Loaded from `user/selectUserByWindowsUsername.sql`. */
    private static final String SQL_SELECT_USER_BY_WINDOWS_USERNAME;
    /** SQL query to select all user records that belong to a specific role. Loaded from `user/selectUsersByRole.sql`. */
    private static final String SQL_SELECT_USERS_BY_ROLE;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            // SQL filenames adhere to the 'lowercaseFirstWordCamelCase.sql' convention
            SQL_CREATE_USER_RECORD = QueryLoader.getQuery("user/insertUser.sql");
            SQL_READ_USER_RECORD = QueryLoader.getQuery("user/selectUserById.sql");
            SQL_READ_ALL_USER_RECORDS = QueryLoader.getQuery("user/selectAllUsers.sql");
            SQL_COUNT_USER_RECORDS = QueryLoader.getQuery("user/countUsers.sql");
            SQL_EXISTS_USER_BY_ID = QueryLoader.getQuery("user/existsUserById.sql");
            SQL_UPDATE_USER_RECORD = QueryLoader.getQuery("user/updateUser.sql");
            SQL_DELETE_USER_SOFT = QueryLoader.getQuery("user/deleteUserSoft.sql");
            SQL_SELECT_USER_BY_WINDOWS_USERNAME = QueryLoader.getQuery("user/selectUserByWindowsUsername.sql");
            SQL_SELECT_USERS_BY_ROLE = QueryLoader.getQuery("user/selectUsersByRole.sql");
            logger.info("All SQL queries for UserImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for UserImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link User} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code User} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `UserID` and setting it via the package-private `_setUserId` method.</li>
     * <li>String fields (e.g., `WindowsUsername`, `FirstName`, `LastName`, `Email`).</li>
     * <li>Conversion of `UserRole` from `TEXT` in DB to the {@link Role} enum.</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` and `DateCreated` `TEXT` fields, parsing them into
     * {@link LocalDateTime} objects using {@link #CUSTOM_DATETIME_FORMATTER} if present.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing user data.
     * @return A fully populated {@link User} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private User mapResultSetToUser(ResultSet rs) throws SQLException {
        User user = new User();
        Integer userId = rs.getInt("UserID");
        if (userId > 0) { // SQLite getInt returns 0 for NULL for INTEGER PRIMARY KEY, check for positive valid ID
            user._setUserId(userId);
        }

        user.setWindowsUsername(rs.getString("WindowsUsername"));
        user.setFirstName(rs.getString("FirstName"));
        user.setLastName(rs.getString("LastName"));
        user.setEmail(rs.getString("Email"));

        // Role Enum
        String roleStr = rs.getString("UserRole");
        user.setRole(roleStr != null && !roleStr.isEmpty() ? Role.fromDbValue(roleStr) : null);

        user.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        user.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ? LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        String dateCreatedStr = rs.getString("DateCreated");
        user.setDateCreated(dateCreatedStr != null && !dateCreatedStr.isEmpty() ? LocalDateTime.parse(dateCreatedStr, CUSTOM_DATETIME_FORMATTER) : null);

        return user;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User createRecord(User user) throws DatabaseAccessException {
        Objects.requireNonNull(user, "User object cannot be null for creation.");
        if (user.getUserId() != null) {
            throw new IllegalArgumentException("User ID must be null for new user creation (auto-generated).");
        }
        Objects.requireNonNull(user.getWindowsUsername(), "WindowsUsername cannot be null for user creation.");
        Objects.requireNonNull(user.getRole(), "UserRole cannot be null for user creation.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_CREATE_USER_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, user.getWindowsUsername());
            stmt.setString(2, user.getFirstName());
            stmt.setString(3, user.getLastName());
            stmt.setString(4, user.getEmail());
            stmt.setString(5, user.getRole().getDbValue()); // Convert enum to string for DB
            stmt.setInt(6, user.isActive() ? 1 : 0); // true = 1, false = 0
            stmt.setString(7, user.getDeletedAt() != null ? user.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(8, user.getDateCreated() != null ? user.getDateCreated().format(CUSTOM_DATETIME_FORMATTER) : null);


            logger.debug("Executing insert user query for WindowsUsername: {}", user.getWindowsUsername());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.error("Creating user failed, no rows affected for WindowsUsername: {}", user.getWindowsUsername());
                throw new DatabaseAccessException("Creating user failed, no rows affected.");
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    Integer generatedId = generatedKeys.getInt(1);
                    user._setUserId(generatedId); // Set the auto-generated ID
                    logger.info("Successfully created user with ID: {}", generatedId);
                    return user;
                } else {
                    logger.error("Creating user failed, no ID obtained for WindowsUsername: {}", user.getWindowsUsername());
                    throw new DatabaseAccessException("Creating user failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            logger.error("Error creating user record: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error creating user record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For this application, implementations of this method are expected to perform a
     * **soft-delete** rather than physically removing the record from the database.
     * This typically involves updating an `IsActive` flag to `0` and/or setting a
     * `DeletedAt` timestamp to the current time. This strategy preserves data integrity
     * for historical, auditing, and referential purposes, and allows for potential recovery.
     * </p>
     *
     * <p>
     * If no record matches the provided ID, the operation will typically complete
     * without throwing an error, but no rows will be affected. Implementations
     * might log a warning or return a boolean indicating success if desired.
     * </p>
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for deletion.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_DELETE_USER_SOFT)) {

            stmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // Set DeletedAt
            stmt.setInt(2, id); // Where UserID = ?

            logger.debug("Executing soft-delete user query for ID: {}", id);
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No user found with ID: {} for soft-deletion.", id);
            } else {
                logger.info("Successfully soft-deleted user with ID: {}", id);
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting user record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error soft-deleting user record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The result is wrapped in an {@code Optional<User>} to clearly indicate whether
     * an entity matching the given ID was found. This prevents {@code NullPointerExceptions}
     * and encourages explicit handling of cases where the record might not exist.
     * </p>
     */
    @Override
    public Optional<User> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for reading.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_USER_RECORD)) {

            stmt.setInt(1, id);
            logger.debug("Executing read user query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    User user = mapResultSetToUser(rs);
                    logger.info("Found user with ID: {}", id);
                    return Optional.of(user);
                } else {
                    logger.info("No user found with ID: {}", id);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error reading user record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error reading user record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The order of the returned records is dependent on the underlying database and
     * the SQL query used by the concrete implementation (e.g., if no specific
     * ORDER BY clause is applied, the order might not be guaranteed).
     * </p>
     */
    @Override
    public List<User> readRecordAll() throws DatabaseAccessException {
        List<User> users = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_ALL_USER_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing read all users query.");
            while (rs.next()) {
                users.add(mapResultSetToUser(rs));
            }
            logger.info("Found {} total users.", users.size());
        } catch (SQLException e) {
            logger.error("Error reading all user records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error reading all user records: " + e.getMessage(), e);
        }
        return users;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_USER_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total user record count: {}", count);
                return count;
            }
            return 0; // Should not happen if query returns 0, but as a safeguard
        } catch (SQLException e) {
            logger.error("Error counting user records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting user records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for existence check.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_EXISTS_USER_BY_ID)) {

            stmt.setInt(1, id);
            logger.debug("Executing existsById user query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                boolean exists = rs.next();
                logger.info("User with ID {} exists: {}", id, exists);
                return exists;
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of user record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error checking existence of user record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For the update operation to succeed, the {@code user} object passed as a parameter
     * *must* have its primary key field set. This ID is used to identify which existing
     * record in the database should be updated. All other fields in the {@code user}
     * object will be used to update the corresponding columns in the database.
     * </p>
     */
    @Override
    public void updateRecord(User user) throws DatabaseAccessException {
        Objects.requireNonNull(user, "User object cannot be null for update.");
        Objects.requireNonNull(user.getUserId(), "User ID must not be null for update.");
        Objects.requireNonNull(user.getWindowsUsername(), "WindowsUsername cannot be null for user update.");
        Objects.requireNonNull(user.getRole(), "UserRole cannot be null for user update.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_UPDATE_USER_RECORD)) {

            stmt.setString(1, user.getWindowsUsername());
            stmt.setString(2, user.getFirstName());
            stmt.setString(3, user.getLastName());
            stmt.setString(4, user.getEmail());
            stmt.setString(5, user.getRole().getDbValue());
            stmt.setInt(6, user.isActive() ? 1 : 0);
            stmt.setString(7, user.getDeletedAt() != null ? user.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(8, user.getDateCreated() != null ? user.getDateCreated().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setInt(9, user.getUserId()); // WHERE clause

            logger.debug("Executing update user query for ID: {}", user.getUserId());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No user found with ID: {} for update. Update operation resulted in 0 affected rows.", user.getUserId());
                throw new DatabaseAccessException("User with ID " + user.getUserId() + " not found for update.");
            } else {
                logger.info("Successfully updated user with ID: {}", user.getUserId());
            }
        } catch (SQLException e) {
            logger.error("Error updating user record with ID {}: {}", user.getUserId(), e.getMessage(), e);
            throw new DatabaseAccessException("Error updating user record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<User> getUserByWindowsUsername(String windowsUsername) throws DatabaseAccessException {
        Objects.requireNonNull(windowsUsername, "Windows username cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_USER_BY_WINDOWS_USERNAME)) {

            stmt.setString(1, windowsUsername);
            logger.debug("Executing query: {} with Windows username: {}", SQL_SELECT_USER_BY_WINDOWS_USERNAME, windowsUsername);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    User user = mapResultSetToUser(rs);
                    logger.info("Found user with Windows username: {}", windowsUsername);
                    return Optional.of(user);
                } else {
                    logger.info("No user found with Windows username: {}", windowsUsername);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding user by Windows username {}: {}", windowsUsername, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding user by Windows username: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<User> getUsersByRole(Role role) throws DatabaseAccessException {
        Objects.requireNonNull(role, "Role cannot be null for finding users by role.");
        List<User> users = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_USERS_BY_ROLE)) {

            stmt.setString(1, role.getDbValue());
            logger.debug("Executing find users by role query for role: {}", role.getDbValue());
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    users.add(mapResultSetToUser(rs));
                }
            }
            logger.info("Found {} users for role: {}", users.size(), role.getDbValue());
        } catch (SQLException e) {
            logger.error("Error finding users by role {}: {}", role.getDbValue(), e.getMessage(), e);
            throw new DatabaseAccessException("Error finding users by role: " + e.getMessage(), e);
        }
        return users;
    }
}