package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.User;
import com.avaruusstudios.vmdb.model.Role;
import com.avaruusstudios.vmdb.data.UserDataAccess;
import com.avaruusstudios.vmdb.data.GenericDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link UserDataAccess} interface for managing
 * {@link User} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via {@link GenericDataAccess}, along with
 * specific queries for {@code User} entities (e.g., finding by Windows username or role).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>User IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `WindowsUsername` is enforced at the database level via a unique constraint.</li>
 * <li>Deletion of user records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0
 * Created On: 2025-07-14
 * Updated On: 2025-07-14
 *
 * @see UserDataAccess
 * @see User
 * @see Role
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see GenericDataAccess
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 */
public class UserImplementation implements UserDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code UserImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(UserImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new user record. Loaded from `user/insertUser.sql`. */
    private static final String SQL_CREATE_USER_RECORD;
    /** SQL query to select a user record by its unique ID. Loaded from `user/selectUserById.sql`. */
    private static final String SQL_READ_USER_RECORD;
    /** SQL query to select all user records. Loaded from `user/selectAllUsers.sql`. */
    private static final String SQL_READ_ALL_USER_RECORDS;
    /** SQL query to count the total number of user records. Loaded from `user/countUsers.sql`. */
    private static final String SQL_COUNT_USER_RECORDS;
    /** SQL query to check if a user record with a given ID exists. Loaded from `user/existsUserById.sql`. */
    private static final String SQL_EXISTS_USER_BY_ID;
    /** SQL query to update an existing user record. Loaded from `user/updateUser.sql`. */
    private static final String SQL_UPDATE_USER_RECORD;
    /** SQL query to soft-delete a user record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `user/deleteUserSoft.sql`. */
    private static final String SQL_DELETE_USER_SOFT;
    /** SQL query to select a user record by their unique Windows username. Loaded from `user/selectUserByWindowsUsername.sql`. */
    private static final String SQL_SELECT_USER_BY_WINDOWS_USERNAME;
    /** SQL query to select all user records that belong to a specific role. Loaded from `user/selectUsersByRole.sql`. */
    private static final String SQL_SELECT_USERS_BY_ROLE;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            // SQL filenames adhere to the 'lowercaseFirstWordCamelCase.sql' convention
            SQL_CREATE_USER_RECORD = QueryLoader.getQuery("user/insertUser.sql");
            SQL_READ_USER_RECORD = QueryLoader.getQuery("user/selectUserById.sql");
            SQL_READ_ALL_USER_RECORDS = QueryLoader.getQuery("user/selectAllUsers.sql");
            SQL_COUNT_USER_RECORDS = QueryLoader.getQuery("user/countUsers.sql");
            SQL_EXISTS_USER_BY_ID = QueryLoader.getQuery("user/existsUserById.sql");
            SQL_UPDATE_USER_RECORD = QueryLoader.getQuery("user/updateUser.sql");
            SQL_DELETE_USER_SOFT = QueryLoader.getQuery("user/deleteUserSoft.sql");
            SQL_SELECT_USER_BY_WINDOWS_USERNAME = QueryLoader.getQuery("user/selectUserByWindowsUsername.sql");
            SQL_SELECT_USERS_BY_ROLE = QueryLoader.getQuery("user/selectUsersByRole.sql");
            logger.info("All SQL queries for UserImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for UserImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link User} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code User} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `UserID` and setting it via the package-private `_setUserId` method.</li>
     * <li>String fields (e.g., `WindowsUsername`, `FirstName`, `LastName`, `Email`).</li>
     * <li>Conversion of `UserRole` from `TEXT` in DB to the {@link Role} enum.</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` and `DateCreated` `TEXT` fields, parsing them into
     * {@link LocalDateTime} objects using {@link #CUSTOM_DATETIME_FORMATTER} if present.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing user data.
     * @return A fully populated {@link User} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private User mapResultSetToUser(ResultSet rs) throws SQLException {
        // Create a new User object. Its ID is set via a package-private method
        // to comply with its immutability rule after creation.
        User user = new User();
        Integer userId = rs.getInt("UserID");
        if (userId > 0) { // SQLite getInt returns 0 for NULL, check for positive valid ID
            user._setUserId(userId);
        }

        user.setWindowsUsername(rs.getString("WindowsUsername"));
        user.setFirstName(rs.getString("FirstName"));
        user.setMiddleName(rs.getString("MiddleName"));
        user.setLastName(rs.getString("LastName"));
        user.setEmail(rs.getString("Email"));
        // Convert the database string value to the corresponding Role enum.
        user.setRole(Role.fromDbValue(rs.getString("UserRole")));
        // Convert INTEGER (0 or 1) from DB to boolean.
        user.setActive(rs.getInt("IsActive") == 1);

        // Handle nullable DeletedAt timestamp.
        String deletedAtStr = rs.getString("DeletedAt");
        user.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ?
                LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        // Handle nullable DateCreated timestamp (though typically NOT NULL and set by DB).
        String dateCreatedStr = rs.getString("DateCreated");
        user.setDateCreated(dateCreatedStr != null && !dateCreatedStr.isEmpty() ?
                LocalDateTime.parse(dateCreatedStr, CUSTOM_DATETIME_FORMATTER) : null);

        return user;
    }

    /**
     * <p>
     * Inserts a new {@link User} record into the SQLite database.
     * The database's `AUTOINCREMENT` feature automatically assigns a unique `UserID`.
     * </p>
     * <p>
     * This method validates the provided {@code User} object and its mandatory fields
     * (`WindowsUsername`, `FirstName`, `LastName`, `Role`) before attempting the insertion.
     * It handles potential database errors, including unique constraint violations for `WindowsUsername`.
     * Upon successful insertion, the database-generated `UserID` is injected back into the
     * provided `User` object.
     * </p>
     *
     * @param user The {@link User} object to be created. Its `UserID` will be ignored if present,
     * as it's auto-generated by the database.
     * @return The created {@link User} object, updated with its database-assigned `UserID`.
     * @throws DatabaseAccessException  if a database access error occurs during creation,
     * e.g., a unique constraint violation on `WindowsUsername`,
     * or other SQL errors.
     * @throws NullPointerException     if the provided {@code user} object or any of its
     * required `NOT NULL` fields (`WindowsUsername`, `FirstName`,
     * `LastName`, `Role`) are {@code null}.
     * @throws IllegalArgumentException if the `WindowsUsername` is empty after trimming,
     * or if `FirstName` or `LastName` are empty strings.
     * @throws IllegalStateException    if the `User` object's internal state is invalid
     * (e.g., `_setUserId` is called on an already set ID,
     * though this should ideally not happen here).
     */
    @Override
    public User createRecord(User user) throws DatabaseAccessException {
        // Pre-conditions: Validate input object and its essential properties.
        Objects.requireNonNull(user, "User object cannot be null for creation.");
        Objects.requireNonNull(user.getWindowsUsername(), "Windows username cannot be null for user creation.");
        Objects.requireNonNull(user.getFirstName(), "First name cannot be null for user creation.");
        Objects.requireNonNull(user.getLastName(), "Last name cannot be null for user creation.");
        Objects.requireNonNull(user.getRole(), "User role cannot be null for user creation.");

        // Additional validation for non-null but potentially empty strings.
        if (user.getWindowsUsername().trim().isEmpty()) {
            throw new IllegalArgumentException("Windows username cannot be empty for user creation.");
        }
        if (user.getFirstName().trim().isEmpty()) {
            throw new IllegalArgumentException("First name cannot be empty for user creation.");
        }
        if (user.getLastName().trim().isEmpty()) {
            throw new IllegalArgumentException("Last name cannot be empty for user creation.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             // Prepare the statement to return auto-generated keys (the UserID)
             PreparedStatement pstmt = connection.prepareStatement(SQL_CREATE_USER_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            // Set parameters for the PreparedStatement, mapping User object fields to SQL columns.
            pstmt.setString(1, user.getWindowsUsername().trim());
            pstmt.setString(2, user.getFirstName().trim());
            pstmt.setString(3, user.getMiddleName() != null ? user.getMiddleName().trim() : null); // Nullable
            pstmt.setString(4, user.getLastName().trim());
            pstmt.setString(5, user.getEmail() != null ? user.getEmail().trim() : null); // Nullable
            pstmt.setString(6, user.getRole().getDbValue()); // Convert enum to DB string value
            pstmt.setInt(7, user.isActive() ? 1 : 0); // Convert boolean to integer (1 or 0)

            // Handle nullable DateCreated. If null, set SQL NULL. Otherwise, format to string.
            if (user.getDateCreated() != null) {
                pstmt.setString(8, user.getDateCreated().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(8, Types.VARCHAR); // Set NULL for TEXT column
            }

            int affectedRows = pstmt.executeUpdate(); // Execute the insert operation
            if (affectedRows == 0) {
                logger.error("Creating user failed, no rows affected for username: {}.", user.getWindowsUsername());
                throw new DatabaseAccessException("Creating user failed, no rows affected.");
            }

            // Retrieve the auto-generated UserID
            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    user._setUserId(generatedKeys.getInt(1)); // Set the ID back into the user object
                    logger.info("User created successfully with ID: {}.", user.getUserId());
                } else {
                    logger.error("Creating user failed, no ID obtained for username: {}.", user.getWindowsUsername());
                    throw new DatabaseAccessException("Creating user failed, no ID obtained.");
                }
            }
            return user; // Return the updated User object

        } catch (SQLException e) {
            logger.error("Error creating user '{}': {}", user.getWindowsUsername(), e.getMessage(), e);
            // Check for specific SQLite unique constraint violation error code (19)
            if (e.getErrorCode() == 19 && e.getMessage().contains("UNIQUE constraint failed: Users.WindowsUsername")) {
                throw new DatabaseAccessException("User with Windows username '" + user.getWindowsUsername() + "' already exists. Usernames must be unique.", e);
            }
            throw new DatabaseAccessException("Failed to create user: " + e.getMessage(), e);
        } catch (IllegalArgumentException | IllegalStateException e) {
            // Catch validation errors thrown by Objects.requireNonNull or User model setters.
            logger.error("User validation/state error during creation for username '{}': {}", user.getWindowsUsername(), e.getMessage(), e);
            throw new DatabaseAccessException("User data is invalid or in an illegal state for creation: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Retrieves a single {@link User} record from the database by its unique identifier (`UserID`).
     * </p>
     *
     * @param id The unique integer ID of the user to retrieve. Must not be {@code null} and must be positive.
     * @return An {@link Optional} containing the {@link User} object if a user with the given ID is found,
     * or an empty {@link Optional} if no such user exists.
     * @throws DatabaseAccessException  if a database access error occurs during retrieval.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public Optional<User> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for retrieval.");
        if (id <= 0) {
            throw new IllegalArgumentException("User ID must be positive for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_USER_RECORD)) {

            pstmt.setInt(1, id); // Set the UserID parameter for the query
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    // If a record is found, map it to a User object.
                    return Optional.of(mapResultSetToUser(rs));
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving user by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve user by ID " + id + ": " + e.getMessage(), e);
        }
        return Optional.empty(); // No user found with the given ID
    }

    /**
     * <p>
     * Retrieves all {@link User} records currently stored in the database.
     * </p>
     *
     * @return A {@link List} of {@link User} objects. The list will be empty if no users are found.
     * @throws DatabaseAccessException if a database access error occurs during retrieval.
     */
    @Override
    public List<User> readRecordAll() throws DatabaseAccessException {
        List<User> users = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement(); // Using Statement as no parameters for select all
             ResultSet rs = stmt.executeQuery(SQL_READ_ALL_USER_RECORDS)) {

            while (rs.next()) {
                // Iterate through the ResultSet and map each row to a User object.
                users.add(mapResultSetToUser(rs));
            }
        } catch (SQLException e) {
            logger.error("Error retrieving all users: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve all users: " + e.getMessage(), e);
        }
        return users;
    }

    /**
     * <p>
     * Counts the total number of user records in the database.
     * </p>
     *
     * @return The total count of users as a {@code long}. Returns 0 if no users are found
     * or if an error occurs.
     * @throws DatabaseAccessException if a database access error occurs during counting.
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             Statement stmt = connection.createStatement(); // Using Statement as no parameters for count
             ResultSet rs = stmt.executeQuery(SQL_COUNT_USER_RECORDS)) {

            if (rs.next()) {
                return rs.getLong(1); // The count is typically in the first column of the result set.
            }
        } catch (SQLException e) {
            logger.error("Error counting users: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Failed to count users: " + e.getMessage(), e);
        }
        return 0; // Fallback in case ResultSet is empty, though unlikely for COUNT(*)
    }

    /**
     * <p>
     * Checks if a user record with the specified ID exists in the database.
     * </p>
     *
     * @param id The unique integer ID of the user to check for existence. Must not be {@code null} and must be positive.
     * @return {@code true} if a user with the given ID exists, {@code false} otherwise.
     * @throws DatabaseAccessException  if a database access error occurs during the existence check.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for existence check.");
        if (id <= 0) {
            throw new IllegalArgumentException("User ID must be positive for existence check.");
        }
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_EXISTS_USER_BY_ID)) {

            pstmt.setInt(1, id); // Set the UserID parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next(); // If rs.next() returns true, at least one row was found, meaning the record exists.
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of user by ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to check existence of user by ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Updates an existing {@link User} record in the database. The update operation is
     * based on the `UserID` of the provided {@link User} object.
     * </p>
     * <p>
     * This method validates the provided {@code User} object and its mandatory fields
     * (`UserID`, `WindowsUsername`, `FirstName`, `LastName`, `Role`) before execution.
     * It specifically handles unique constraint violations if the updated `WindowsUsername`
     * conflicts with an existing user's username.
     * </p>
     *
     * @param user The {@link User} object containing the updated data.
     * Its `UserID` must not be {@code null} and must be positive to identify the record to update.
     * @throws DatabaseAccessException  if a database access error occurs during the update,
     * e.g., a unique constraint violation on `WindowsUsername`,
     * or other SQL errors.
     * @throws NullPointerException     if the provided {@code user} object itself, its `UserID`,
     * or any of its required `NOT NULL` fields are {@code null}.
     * @throws IllegalArgumentException if the `UserID` is non-positive, or if `WindowsUsername`,
     * `FirstName`, or `LastName` are empty strings after trimming.
     */
    @Override
    public void updateRecord(User user) throws DatabaseAccessException {
        // Pre-conditions: Validate input object and its essential properties.
        Objects.requireNonNull(user, "User object cannot be null for update.");
        Objects.requireNonNull(user.getUserId(), "User ID cannot be null for update.");
        if (user.getUserId() <= 0) {
            throw new IllegalArgumentException("User ID must be positive for update.");
        }
        Objects.requireNonNull(user.getWindowsUsername(), "Windows username cannot be null for user update.");
        Objects.requireNonNull(user.getFirstName(), "First name cannot be null for user update.");
        Objects.requireNonNull(user.getLastName(), "Last name cannot be null for user update.");
        Objects.requireNonNull(user.getRole(), "User role cannot be null for user update.");

        // Additional validation for non-null but potentially empty strings.
        if (user.getWindowsUsername().trim().isEmpty()) {
            throw new IllegalArgumentException("Windows username cannot be empty for user update.");
        }
        if (user.getFirstName().trim().isEmpty()) {
            throw new IllegalArgumentException("First name cannot be empty for user update.");
        }
        if (user.getLastName().trim().isEmpty()) {
            throw new IllegalArgumentException("Last name cannot be empty for user update.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_UPDATE_USER_RECORD)) {

            // Set parameters for the PreparedStatement, mapping User object fields to SQL columns.
            // Parameters are ordered by their position in the SQL_UPDATE_USER_RECORD query.
            pstmt.setString(1, user.getWindowsUsername().trim());
            pstmt.setString(2, user.getFirstName().trim());
            pstmt.setString(3, user.getMiddleName() != null ? user.getMiddleName().trim() : null); // Nullable
            pstmt.setString(4, user.getLastName().trim());
            pstmt.setString(5, user.getEmail() != null ? user.getEmail().trim() : null); // Nullable
            pstmt.setString(6, user.getRole().getDbValue()); // Convert enum to DB string value
            pstmt.setInt(7, user.isActive() ? 1 : 0); // Convert boolean to integer (1 or 0)

            // Handle nullable DeletedAt timestamp. Set SQL NULL if null.
            if (user.getDeletedAt() != null) {
                pstmt.setString(8, user.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER));
            } else {
                pstmt.setNull(8, Types.VARCHAR); // Set NULL for TEXT column
            }

            // Set the UserID for the WHERE clause to identify the record to update.
            pstmt.setInt(9, user.getUserId());

            int affectedRows = pstmt.executeUpdate(); // Execute the update operation
            if (affectedRows == 0) {
                logger.warn("Update user with ID {} affected 0 rows. User might not exist or data was identical.", user.getUserId());
                throw new DatabaseAccessException("User with ID " + user.getUserId() + " not found for update or no changes were made.");
            } else {
                logger.info("User with ID {} updated successfully. Affected rows: {}.", user.getUserId(), affectedRows);
            }

        } catch (SQLException e) {
            logger.error("Error updating user with ID {}: {}", user.getUserId(), e.getMessage(), e);
            // Check for specific SQLite unique constraint violation error code (19)
            if (e.getErrorCode() == 19 && e.getMessage().contains("UNIQUE constraint failed: Users.WindowsUsername")) {
                throw new DatabaseAccessException("Cannot update user: Windows username '" + user.getWindowsUsername() + "' is already in use by another user.", e);
            }
            throw new DatabaseAccessException("Failed to update user with ID " + user.getUserId() + ": " + e.getMessage(), e);
        } catch (IllegalArgumentException e) {
            // Catch validation errors from Objects.requireNonNull or User model setters.
            logger.error("User validation error during update for user ID {}: {}", user.getUserId(), e.getMessage(), e);
            throw new DatabaseAccessException("User data is invalid for update: " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Soft-deletes a {@link User} record from the database by setting its `IsActive` flag
     * to `0` (false) and updating the `DeletedAt` timestamp to the current date and time.
     * This method does not physically remove the record, preserving historical data.
     * </p>
     *
     * @param id The unique integer ID of the user to soft-delete. Must not be {@code null} and must be positive.
     * @throws DatabaseAccessException  if a database access error occurs during the soft-deletion.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "User ID cannot be null for deletion.");
        if (id <= 0) {
            throw new IllegalArgumentException("User ID must be positive for deletion.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_DELETE_USER_SOFT)) {

            // Set parameters for the soft-delete: current timestamp for DeletedAt and the UserID.
            pstmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            pstmt.setInt(2, id); // UserID for the WHERE clause

            int affectedRows = pstmt.executeUpdate(); // Execute the update operation
            if (affectedRows == 0) {
                logger.warn("Soft-delete user with ID {} affected 0 rows. User might not exist or already soft-deleted.", id);
                throw new DatabaseAccessException("User with ID " + id + " not found for soft-deletion or already deleted.");
            } else {
                logger.info("User with ID {} soft-deleted successfully (IsActive=0, DeletedAt={}).", id, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting user with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to soft-delete user with ID " + id + ": " + e.getMessage(), e);
        }
    }

    /**
     * <p>
     * Finds a single {@link User} record by their unique Windows username.
     * </p>
     *
     * @param windowsUsername The unique Windows username string to search for. Must not be {@code null} or empty.
     * @return An {@link Optional} containing the {@link User} object if a user with the given username is found,
     * or an empty {@link Optional} if no such user exists.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code windowsUsername} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code windowsUsername} is an empty string after trimming.
     */
    @Override
    public Optional<User> getUserByWindowsUsername(String windowsUsername) throws DatabaseAccessException {
        Objects.requireNonNull(windowsUsername, "Windows username cannot be null for retrieval.");
        String trimmedUsername = windowsUsername.trim();
        if (trimmedUsername.isEmpty()) {
            throw new IllegalArgumentException("Windows username cannot be empty for retrieval.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_USER_BY_WINDOWS_USERNAME)) {

            pstmt.setString(1, trimmedUsername); // Set the Windows username parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToUser(rs)); // Found the user, map and return.
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving user by Windows username '{}': {}", trimmedUsername, e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve user by Windows username '" + trimmedUsername + "': " + e.getMessage(), e);
        }
        return Optional.empty(); // No user found with the given Windows username.
    }

    /**
     * <p>
     * Finds all {@link User} records that belong to a specified {@link Role}.
     * </p>
     *
     * @param role The {@link Role} enum value to search for. Must not be {@code null}.
     * @return A {@link List} of {@link User} objects matching the specified role.
     * The list will be empty if no users are found for that role.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code role} is {@code null}.
     */
    @Override
    public List<User> getUsersByRole(Role role) throws DatabaseAccessException {
        Objects.requireNonNull(role, "Role cannot be null for retrieval.");
        List<User> users = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SELECT_USERS_BY_ROLE)) {

            pstmt.setString(1, role.getDbValue()); // Set the database string value of the role enum
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    users.add(mapResultSetToUser(rs)); // Add each found user to the list
                }
            }
        } catch (SQLException e) {
            logger.error("Error retrieving users by role '{}': {}", role.name(), e.getMessage(), e);
            throw new DatabaseAccessException("Failed to retrieve users by role '" + role.name() + "': " + e.getMessage(), e);
        }
        return users;
    }
}