package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Vehicle;
import com.avaruusstudios.vmdb.model.VehicleType;
import com.avaruusstudios.vmdb.data.VehicleDataAccess;
import com.avaruusstudios.vmdb.data.DeleteDataAccess;
import com.avaruusstudios.vmdb.data.UpdateDataAccess;
import com.avaruusstudios.vmdb.data.CreateDataAccess;
import com.avaruusstudios.vmdb.data.ReadDataAccess;
import com.avaruusstudios.vmdb.data.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link VehicleDataAccess} interface for managing
 * {@link Vehicle} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Vehicle} entities (e.g., finding by license plate or type).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Vehicle IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `LicensePlate` is enforced at the database level.</li>
 * <li>Deletion of vehicle records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>`VehicleType` enum values are stored as `TEXT` in the SQLite database. Conversion between
 * `String` and `VehicleType` enum uses the robust {@link VehicleType#fromDbValue(String)} method.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0
 * Created On: 2025-07-14
 * Updated On: 2025-07-14
 *
 * @see VehicleDataAccess
 * @see Vehicle
 * @see VehicleType
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class VehicleImplementation implements VehicleDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code VehicleImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(VehicleImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new vehicle record. Loaded from `vehicle/insertVehicle.sql`. */
    private static final String SQL_CREATE_VEHICLE_RECORD;
    /** SQL query to select a vehicle record by its unique ID. Loaded from `vehicle/selectVehicleById.sql`. */
    private static final String SQL_READ_VEHICLE_RECORD;
    /** SQL query to select all vehicle records. Loaded from `vehicle/selectAllVehicles.sql`. */
    private static final String SQL_READ_ALL_VEHICLE_RECORDS;
    /** SQL query to count the total number of vehicle records. Loaded from `vehicle/countVehicles.sql`. */
    private static final String SQL_COUNT_VEHICLE_RECORDS;
    /** SQL query to check if a vehicle record with a given ID exists. Loaded from `vehicle/existsVehicleById.sql`. */
    private static final String SQL_EXISTS_VEHICLE_BY_ID;
    /** SQL query to update an existing vehicle record. Loaded from `vehicle/updateVehicle.sql`. */
    private static final String SQL_UPDATE_VEHICLE_RECORD;
    /** SQL query to soft-delete a vehicle record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `vehicle/deleteVehicleSoft.sql`. */
    private static final String SQL_DELETE_VEHICLE_SOFT;
    /** SQL query to select a vehicle record by its unique license plate. Loaded from `vehicle/selectVehicleByLicensePlate.sql`. */
    private static final String SQL_SELECT_VEHICLE_BY_LICENSE_PLATE;
    /** SQL query to select all vehicle records that are of a specific vehicle type. Loaded from `vehicle/selectVehiclesByType.sql`. */
    private static final String SQL_SELECT_VEHICLES_BY_TYPE;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            // SQL filenames adhere to the 'lowercaseFirstWordCamelCase.sql' convention
            SQL_CREATE_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/insertVehicle.sql");
            SQL_READ_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/selectVehicleById.sql");
            SQL_READ_ALL_VEHICLE_RECORDS = QueryLoader.getQuery("vehicle/selectAllVehicles.sql");
            SQL_COUNT_VEHICLE_RECORDS = QueryLoader.getQuery("vehicle/countVehicles.sql");
            SQL_EXISTS_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/existsVehicleById.sql");
            SQL_UPDATE_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/updateVehicle.sql");
            SQL_DELETE_VEHICLE_SOFT = QueryLoader.getQuery("vehicle/deleteVehicleSoft.sql");
            SQL_SELECT_VEHICLE_BY_LICENSE_PLATE = QueryLoader.getQuery("vehicle/selectVehicleByLicensePlate.sql");
            SQL_SELECT_VEHICLES_BY_TYPE = QueryLoader.getQuery("vehicle/selectVehiclesByType.sql");
            logger.info("All SQL queries for VehicleImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for VehicleImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Vehicle} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code Vehicle} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `VehicleID` and setting it via the package-private `_setVehicleID` method.</li>
     * <li>String fields (e.g., `Make`, `Model`, `LicensePlate`).</li>
     * <li>Integer fields (e.g., `ManufactureYear`, `PassengerCapacity`).</li>
     * <li>Conversion of `VehicleType` from `TEXT` in DB to the {@link VehicleType} enum.</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` `TEXT` fields, parsing them into
     * {@link LocalDateTime} objects using {@link #CUSTOM_DATETIME_FORMATTER} if present.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing vehicle data.
     * @return A fully populated {@link Vehicle} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private Vehicle mapResultSetToVehicle(ResultSet rs) throws SQLException {
        Vehicle vehicle = new Vehicle();
        Integer vehicleId = rs.getInt("VehicleID");
        if (vehicleId > 0) { // SQLite getInt returns 0 for NULL for INTEGER PRIMARY KEY, check for positive valid ID
            vehicle._setVehicleID(vehicleId);
        }

        vehicle.setMake(rs.getString("Make"));
        vehicle.setModel(rs.getString("Model"));
        vehicle.setManufactureYear(rs.getInt("ManufactureYear"));
        vehicle.setLicensePlate(rs.getString("LicensePlate"));
        vehicle.setPassengerCapacity(rs.getInt("PassengerCapacity"));

        // VehicleType Enum
        String vehicleTypeStr = rs.getString("VehicleType");
        vehicle.setVehicleType(vehicleTypeStr != null && !vehicleTypeStr.isEmpty() ? VehicleType.fromDbValue(vehicleTypeStr) : null);

        vehicle.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        vehicle.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ? LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        return vehicle;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vehicle createRecord(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle object cannot be null for creation.");
        if (vehicle.getVehicleID() != null) {
            throw new IllegalArgumentException("Vehicle ID must be null for new vehicle creation (auto-generated).");
        }
        Objects.requireNonNull(vehicle.getMake(), "Make cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getModel(), "Model cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getLicensePlate(), "LicensePlate cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getVehicleType(), "VehicleType cannot be null for vehicle creation.");


        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_CREATE_VEHICLE_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, vehicle.getMake());
            stmt.setString(2, vehicle.getModel());
            stmt.setInt(3, vehicle.getManufactureYear());
            stmt.setString(4, vehicle.getLicensePlate());
            stmt.setInt(5, vehicle.getPassengerCapacity());
            stmt.setString(6, vehicle.getVehicleType().getDbValue()); // Convert enum to string for DB
            stmt.setInt(7, vehicle.getIsActive() ? 1 : 0); // true = 1, false = 0
            stmt.setString(8, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);

            logger.debug("Executing insert vehicle query for license plate: {}", vehicle.getLicensePlate());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.error("Creating vehicle failed, no rows affected for license plate: {}", vehicle.getLicensePlate());
                throw new DatabaseAccessException("Creating vehicle failed, no rows affected.");
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    Integer generatedId = generatedKeys.getInt(1);
                    vehicle._setVehicleID(generatedId); // Set the auto-generated ID
                    logger.info("Successfully created vehicle with ID: {}", generatedId);
                    return vehicle;
                } else {
                    logger.error("Creating vehicle failed, no ID obtained for license plate: {}", vehicle.getLicensePlate());
                    throw new DatabaseAccessException("Creating vehicle failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            logger.error("Error creating vehicle record: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error creating vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For this application, implementations of this method are expected to perform a
     * **soft-delete** rather than physically removing the record from the database.
     * This typically involves updating an `IsActive` flag to `0` and/or setting a
     * `DeletedAt` timestamp to the current time. This strategy preserves data integrity
     * for historical, auditing, and referential purposes, and allows for potential recovery.
     * </p>
     *
     * <p>
     * If no record matches the provided ID, the operation will typically complete
     * without throwing an error, but no rows will be affected. Implementations
     * might log a warning or return a boolean indicating success if desired.
     * </p>
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for deletion.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_DELETE_VEHICLE_SOFT)) {

            stmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // Set DeletedAt
            stmt.setInt(2, id); // Where VehicleID = ?

            logger.debug("Executing soft-delete vehicle query for ID: {}", id);
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No vehicle found with ID: {} for soft-deletion.", id);
            } else {
                logger.info("Successfully soft-deleted vehicle with ID: {}", id);
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error soft-deleting vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The result is wrapped in an {@code Optional<Vehicle>} to clearly indicate whether
     * an entity matching the given ID was found. This prevents {@code NullPointerExceptions}
     * and encourages explicit handling of cases where the record might not exist.
     * </p>
     */
    @Override
    public Optional<Vehicle> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for reading.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_VEHICLE_RECORD)) {

            stmt.setInt(1, id);
            logger.debug("Executing read vehicle query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Vehicle vehicle = mapResultSetToVehicle(rs);
                    logger.info("Found vehicle with ID: {}", id);
                    return Optional.of(vehicle);
                } else {
                    logger.info("No vehicle found with ID: {}", id);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error reading vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error reading vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The order of the returned records is dependent on the underlying database and
     * the SQL query used by the concrete implementation (e.g., if no specific
     * ORDER BY clause is applied, the order might not be guaranteed).
     * </p>
     */
    @Override
    public List<Vehicle> readRecordAll() throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_ALL_VEHICLE_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing read all vehicles query.");
            while (rs.next()) {
                vehicles.add(mapResultSetToVehicle(rs));
            }
            logger.info("Found {} total vehicles.", vehicles.size());
        } catch (SQLException e) {
            logger.error("Error reading all vehicle records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error reading all vehicle records: " + e.getMessage(), e);
        }
        return vehicles;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_VEHICLE_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total vehicle record count: {}", count);
                return count;
            }
            return 0; // Should not happen if query returns 0, but as a safeguard
        } catch (SQLException e) {
            logger.error("Error counting vehicle records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting vehicle records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for existence check.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_EXISTS_VEHICLE_BY_ID)) {

            stmt.setInt(1, id);
            logger.debug("Executing existsById vehicle query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                boolean exists = rs.next();
                logger.info("Vehicle with ID {} exists: {}", id, exists);
                return exists;
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error checking existence of vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For the update operation to succeed, the {@code vehicle} object passed as a parameter
     * *must* have its primary key field set. This ID is used to identify which existing
     * record in the database should be updated. All other fields in the {@code vehicle}
     * object will be used to update the corresponding columns in the database.
     * </p>
     */
    @Override
    public void updateRecord(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle object cannot be null for update.");
        Objects.requireNonNull(vehicle.getVehicleID(), "Vehicle ID must not be null for update.");
        Objects.requireNonNull(vehicle.getMake(), "Make cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getModel(), "Model cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getLicensePlate(), "LicensePlate cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getVehicleType(), "VehicleType cannot be null for vehicle update.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_UPDATE_VEHICLE_RECORD)) {

            stmt.setString(1, vehicle.getMake());
            stmt.setString(2, vehicle.getModel());
            stmt.setInt(3, vehicle.getManufactureYear());
            stmt.setString(4, vehicle.getLicensePlate());
            stmt.setInt(5, vehicle.getPassengerCapacity());
            stmt.setString(6, vehicle.getVehicleType().getDbValue());
            stmt.setInt(7, vehicle.getIsActive() ? 1 : 0);
            stmt.setString(8, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setInt(9, vehicle.getVehicleID()); // WHERE clause

            logger.debug("Executing update vehicle query for ID: {}", vehicle.getVehicleID());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No vehicle found with ID: {} for update. Update operation resulted in 0 affected rows.", vehicle.getVehicleID());
                throw new DatabaseAccessException("Vehicle with ID " + vehicle.getVehicleID() + " not found for update.");
            } else {
                logger.info("Successfully updated vehicle with ID: {}", vehicle.getVehicleID());
            }
        } catch (SQLException e) {
            logger.error("Error updating vehicle record with ID {}: {}", vehicle.getVehicleID(), e.getMessage(), e);
            throw new DatabaseAccessException("Error updating vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Vehicle> findByLicensePlate(String licensePlate) throws DatabaseAccessException {
        Objects.requireNonNull(licensePlate, "License plate cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLE_BY_LICENSE_PLATE)) {

            stmt.setString(1, licensePlate);
            logger.debug("Executing query: {} with license plate: {}", SQL_SELECT_VEHICLE_BY_LICENSE_PLATE, licensePlate);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Vehicle vehicle = mapResultSetToVehicle(rs);
                    logger.info("Found vehicle with license plate: {}", licensePlate);
                    return Optional.of(vehicle);
                } else {
                    logger.info("No vehicle found with license plate: {}", licensePlate);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding vehicle by license plate {}: {}", licensePlate, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicle by license plate: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findVehiclesByType(VehicleType vehicleType) throws DatabaseAccessException {
        Objects.requireNonNull(vehicleType, "Vehicle type cannot be null for finding vehicles by type.");
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLES_BY_TYPE)) {

            stmt.setString(1, vehicleType.getDbValue());
            logger.debug("Executing find vehicles by type query for type: {}", vehicleType.getDbValue());
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            logger.info("Found {} vehicles for type: {}", vehicles.size(), vehicleType.getDbValue());
        } catch (SQLException e) {
            logger.error("Error finding vehicles by type {}: {}", vehicleType.getDbValue(), e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicles by type: " + e.getMessage(), e);
        }
        return vehicles;
    }
}