package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.data.DatabaseAccessException;
import com.avaruusstudios.vmdb.data.VehicleDataAccess;
import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Vehicle; // Ensure this is the updated Vehicle model
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * SQLite implementation of the {@link VehicleDataAccess} interface for the
 * Vanpool Management Database (VMDB) application. This class interacts with
 * an SQLite database to perform CRUD operations and specific queries for
 * {@link Vehicle} entities.
 * </p>
 * <p>
 * This implementation adheres to the generic DAO interfaces and leverages
 * {@link DatabaseManager} for connection handling and {@link QueryLoader}
 * for SQL query management.
 * </p>
 * <ul>
 * <li>Vehicle IDs are auto-generated by the database.</li>
 * <li>`VehicleNumber` uniqueness is enforced by a database unique constraint.</li>
 * <li>Deletion of records is performed as a **soft-delete**, updating the `IsActive`
 * flag and `DeletedAt` timestamp.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0 (Initial SQLite implementation)
 * Created On: 2025-07-13
 * Updated On: 2025-07-13
 *
 * @see VehicleDataAccess
 * @see Vehicle
 * @see DatabaseAccessException
 * @see DatabaseManager
 * @see QueryLoader
 */
public class VehicleImplementation implements VehicleDataAccess {

    private static final Logger logger = LoggerFactory.getLogger(VehicleImplementation.class);

    // Date/Time formatters for converting between LocalDate/LocalDateTime and TEXT in SQLite
    // Using Locale.ENGLISH for consistent month abbreviations (e.g., "Jan", "Feb")
    private static final DateTimeFormatter CUSTOM_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy", Locale.ENGLISH);
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Queries (loaded from external .sql files with lowercase first word + CamelCase filenames)
    private static final String SQL_CREATE_VEHICLE;
    private static final String SQL_READ_VEHICLE_BY_ID;
    private static final String SQL_READ_ALL_VEHICLES;
    private static final String SQL_COUNT_VEHICLES;
    private static final String SQL_EXISTS_VEHICLE_BY_ID;
    private static final String SQL_UPDATE_VEHICLE;
    private static final String SQL_SOFT_DELETE_VEHICLE;
    private static final String SQL_FIND_BY_VEHICLE_NUMBER;
    private static final String SQL_FIND_ACTIVE_VEHICLE;
    private static final String SQL_FIND_BY_MAKE;
    private static final String SQL_FIND_BY_MODEL;
    private static final String SQL_FIND_BY_YEAR;

    // Static block to load SQL queries once when the class is initialized
    static {
        try {
            SQL_CREATE_VEHICLE = QueryLoader.getQuery("vehicle/insertVehicle.sql");
            SQL_READ_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/selectVehicleById.sql");
            SQL_READ_ALL_VEHICLES = QueryLoader.getQuery("vehicle/selectAllVehicles.sql");
            SQL_COUNT_VEHICLES = QueryLoader.getQuery("vehicle/countVehicles.sql");
            SQL_EXISTS_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/existsVehicleById.sql");
            SQL_UPDATE_VEHICLE = QueryLoader.getQuery("vehicle/updateVehicle.sql");
            SQL_SOFT_DELETE_VEHICLE = QueryLoader.getQuery("vehicle/deleteVehicleSoft.sql");
            SQL_FIND_BY_VEHICLE_NUMBER = QueryLoader.getQuery("vehicle/selectVehicleByVehicleNumber.sql");
            SQL_FIND_ACTIVE_VEHICLE = QueryLoader.getQuery("vehicle/selectActiveVehicle.sql");
            SQL_FIND_BY_MAKE = QueryLoader.getQuery("vehicle/selectVehiclesByMake.sql");
            SQL_FIND_BY_MODEL = QueryLoader.getQuery("vehicle/selectVehiclesByModel.sql");
            SQL_FIND_BY_YEAR = QueryLoader.getQuery("vehicle/selectVehiclesByYear.sql");
            logger.info("All SQL queries for VehicleImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for VehicleImplementation. Check .sql files and paths.", e);
            // Re-throw as ExceptionInInitializerError to indicate a critical setup failure
            throw new ExceptionInInitializerError(e);
        }
    }

    /**
     * Maps a {@link ResultSet} row to a {@link Vehicle} object.
     * This private helper method centralizes the logic for creating Vehicle objects from database results.
     * Ensures mapping aligns with schema's nullable and NOT NULL constraints.
     *
     * @param rs The {@link ResultSet} positioned at the current row.
     * @return A {@link Vehicle} object populated with data from the ResultSet.
     * @throws SQLException If a column is not found or other database access errors occur.
     */
    private Vehicle mapResultSetToVehicle(ResultSet rs) throws SQLException {
        // Create a new Vehicle object using a constructor that doesn't require an ID,
        // or a default constructor if available.
        Vehicle vehicle = new Vehicle();

        // Use the _setVehicleID method to set the ID after retrieval.
        Integer vehicleID = rs.getInt("VehicleID");
        if (vehicleID > 0) { // Check if ID is valid (SQLite returns 0 for NULL INT)
            vehicle._setVehicleID(vehicleID);
        }

        // Set other properties using their respective setters
        vehicle.setVehicleNumber(rs.getString("VehicleNumber"));
        vehicle.setMake(rs.getString("Make"));
        vehicle.setModel(rs.getString("Model"));

        // Use getObject for nullable Integer, handling potential nulls
        vehicle.setYear(rs.getObject("Year", Integer.class));

        vehicle.setCapacity(rs.getInt("Capacity"));

        // Handle LeaseStartDate (TEXT in DB, LocalDate in Java, NOT NULL)
        vehicle.setLeaseStartDate(LocalDate.parse(rs.getString("LeaseStartDate"), CUSTOM_DATE_FORMATTER));

        // Handle LeaseEndDate (TEXT in DB, LocalDate in Java, Nullable)
        String leaseEndDateStr = rs.getString("LeaseEndDate");
        vehicle.setLeaseEndDate(leaseEndDateStr != null && !leaseEndDateStr.isEmpty() ? LocalDate.parse(leaseEndDateStr, CUSTOM_DATE_FORMATTER) : null);

        // Handle Discount (NUMERIC/REAL in DB, BigDecimal in Java, Nullable)
        // Use getObject with BigDecimal.class for nullable numeric types
        vehicle.setDiscount(rs.getObject("Discount", BigDecimal.class));

        // CORRECTED: Call setIsActive() method directly
        vehicle.setIsActive(rs.getInt("IsActive") == 1); // NOT NULL

        // Handle DeletedAt (TEXT in DB, LocalDateTime in Java, Nullable)
        String deletedAtStr = rs.getString("DeletedAt");
        vehicle.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ? LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        vehicle.setNotes(rs.getString("Notes")); // Nullable

        return vehicle;
    }

    // --- CreateDataAccess Implementation ---

    /**
     * <p>
     * Inserts a new vehicle record into the SQLite database.
     * The database's AUTOINCREMENT feature assigns a unique `VehicleID`.
     * </p>
     * <p>
     * The `VehicleNumber`, `Capacity`, `LeaseStartDate`, `IsActive` must be provided and are NOT NULL.
     * The service layer is responsible for business rules like "only one active vehicle".
     * </p>
     *
     * @param vehicle The {@link Vehicle} object to be created. Its `VehicleID` will be ignored if present.
     * @return The created {@link Vehicle} object with its database-assigned ID.
     * @throws DatabaseAccessException if a database access error occurs during creation,
     * e.g., if `VehicleNumber` already exists (SQL UNIQUE constraint violation).
     * @throws NullPointerException    if the provided vehicle object or its required `NOT NULL` fields are {@code null}.
     */
    @Override
    public Vehicle createRecord(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle cannot be null for createRecord.");
        Objects.requireNonNull(vehicle.getVehicleNumber(), "Vehicle number cannot be null for createRecord.");
        Objects.requireNonNull(vehicle.getCapacity(), "Vehicle capacity cannot be null for createRecord (NOT NULL constraint).");
        Objects.requireNonNull(vehicle.getLeaseStartDate(), "Vehicle lease start date cannot be null for createRecord (NOT NULL constraint).");
        // IsActive is primitive boolean, so it's never null.

        String vehicleNumber = vehicle.getVehicleNumber().trim();
        if (vehicleNumber.isEmpty()) {
            throw new DatabaseAccessException("Vehicle number cannot be empty for createRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             // RETURN_GENERATED_KEYS is crucial for getting the auto-incremented ID
             PreparedStatement pstmt = connection.prepareStatement(SQL_CREATE_VEHICLE, Statement.RETURN_GENERATED_KEYS)) {

            int paramIndex = 1;
            pstmt.setString(paramIndex++, vehicleNumber);
            pstmt.setString(paramIndex++, vehicle.getMake()); // Nullable
            pstmt.setString(paramIndex++, vehicle.getModel()); // Nullable
            // Use setObject for nullable Integer types, specify SQL type
            if (vehicle.getYear() != null) {
                pstmt.setInt(paramIndex++, vehicle.getYear());
            } else {
                pstmt.setNull(paramIndex++, Types.INTEGER);
            }
            pstmt.setInt(paramIndex++, vehicle.getCapacity()); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseStartDate().format(CUSTOM_DATE_FORMATTER)); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseEndDate() != null ? vehicle.getLeaseEndDate().format(CUSTOM_DATE_FORMATTER) : null); // Nullable
            // Use setBigDecimal for BigDecimal, setNull with Types.NUMERIC/DECIMAL for nulls
            if (vehicle.getDiscount() != null) {
                pstmt.setBigDecimal(paramIndex++, vehicle.getDiscount());
            } else {
                pstmt.setNull(paramIndex++, Types.NUMERIC);
            }
            pstmt.setInt(paramIndex++, vehicle.isActive() ? 1 : 0); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null); // Nullable
            pstmt.setString(paramIndex++, vehicle.getNotes()); // Nullable

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.error("Creating vehicle failed, no rows affected for vehicle number: {}", vehicle.getVehicleNumber());
                throw new DatabaseAccessException("Creating vehicle failed, no rows affected.");
            }

            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    int id = generatedKeys.getInt(1); // Get the auto-generated ID
                    logger.info("Vehicle created with ID: {}", id);
                    // Update the *original* vehicle object with the assigned ID.
                    vehicle._setVehicleID(id);
                    return vehicle; // Return the updated object
                } else {
                    logger.error("Creating vehicle failed, no ID obtained for vehicle number: {}", vehicle.getVehicleNumber());
                    throw new DatabaseAccessException("Creating vehicle failed, no ID obtained.");
                }
            }

        } catch (SQLException e) {
            String errorMsg = "Error creating vehicle '" + vehicle.getVehicleNumber() + "': " + e.getMessage();
            logger.error(errorMsg, e);
            // Check for specific SQL error codes for unique constraint violation (SQLite: 19)
            if (e.getErrorCode() == 19) { // SQLite constraint violation error code
                throw new DatabaseAccessException("Vehicle with number '" + vehicle.getVehicleNumber() + "' already exists.", e);
            }
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- ReadDataAccess Implementation ---

    @Override
    public Optional<Vehicle> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for readRecord.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for readRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_VEHICLE_BY_ID)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToVehicle(rs));
                }
            }
            return Optional.empty(); // Not found
        } catch (SQLException e) {
            String errorMsg = "Error reading vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public List<Vehicle> readRecordAll() throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_ALL_VEHICLES);
             ResultSet rs = pstmt.executeQuery()) {

            while (rs.next()) {
                vehicles.add(mapResultSetToVehicle(rs));
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error reading all vehicles: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_COUNT_VEHICLES);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1); // Get the count
            }
            return 0;
        } catch (SQLException e) {
            String errorMsg = "Error counting vehicles: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for existsById.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for existsById.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_EXISTS_VEHICLE_BY_ID)) {

            pstmt.setInt(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next(); // If there's a row, it exists
            }
        } catch (SQLException e) {
            String errorMsg = "Error checking existence for vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- UpdateDataAccess Implementation ---

    @Override
    public void updateRecord(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle cannot be null for updateRecord.");
        Objects.requireNonNull(vehicle.getVehicleID(), "Vehicle ID cannot be null for updateRecord.");
        if (vehicle.getVehicleID() <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for updateRecord.");
        }
        Objects.requireNonNull(vehicle.getVehicleNumber(), "Vehicle number cannot be null for updateRecord.");
        Objects.requireNonNull(vehicle.getCapacity(), "Vehicle capacity cannot be null for updateRecord (NOT NULL constraint).");
        Objects.requireNonNull(vehicle.getLeaseStartDate(), "Vehicle lease start date cannot be null for updateRecord (NOT NULL constraint).");

        String vehicleNumber = vehicle.getVehicleNumber().trim();
        if (vehicleNumber.isEmpty()) {
            throw new DatabaseAccessException("Vehicle number cannot be empty for updateRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_UPDATE_VEHICLE)) {

            int paramIndex = 1;
            pstmt.setString(paramIndex++, vehicleNumber);
            pstmt.setString(paramIndex++, vehicle.getMake()); // Nullable
            pstmt.setString(paramIndex++, vehicle.getModel()); // Nullable
            // Use setObject for nullable Integer types, specify SQL type
            if (vehicle.getYear() != null) {
                pstmt.setInt(paramIndex++, vehicle.getYear());
            } else {
                pstmt.setNull(paramIndex++, Types.INTEGER);
            }
            pstmt.setInt(paramIndex++, vehicle.getCapacity()); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseStartDate().format(CUSTOM_DATE_FORMATTER)); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseEndDate() != null ? vehicle.getLeaseEndDate().format(CUSTOM_DATE_FORMATTER) : null); // Nullable
            // Use setBigDecimal for BigDecimal, setNull with Types.NUMERIC/DECIMAL for nulls
            if (vehicle.getDiscount() != null) {
                pstmt.setBigDecimal(paramIndex++, vehicle.getDiscount());
            } else {
                pstmt.setNull(paramIndex++, Types.NUMERIC);
            }
            pstmt.setInt(paramIndex++, vehicle.isActive() ? 1 : 0); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null); // Nullable
            pstmt.setString(paramIndex++, vehicle.getNotes()); // Nullable
            pstmt.setInt(paramIndex++, vehicle.getVehicleID()); // WHERE clause parameter

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Update failed: Vehicle with ID {} not found or no changes made.", vehicle.getVehicleID());
                throw new DatabaseAccessException("Vehicle with ID " + vehicle.getVehicleID() + " not found for update.");
            } else {
                logger.info("Vehicle with ID {} updated successfully.", vehicle.getVehicleID());
            }
        } catch (SQLException e) {
            String errorMsg = "Error updating vehicle with ID " + vehicle.getVehicleID() + ": " + e.getMessage();
            logger.error(errorMsg, e);
            if (e.getErrorCode() == 19) { // SQLite constraint violation error code
                throw new DatabaseAccessException("Update failed: Vehicle with number '" + vehicle.getVehicleNumber() + "' already exists for another vehicle.", e);
            }
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- GenericDataAccess Implementation (Soft Delete) ---

    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for deleteRecord.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for deleteRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SOFT_DELETE_VEHICLE)) {

            pstmt.setInt(1, 0); // IsActive = 0 (false)
            pstmt.setString(2, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // DeletedAt = current timestamp
            pstmt.setInt(3, id); // WHERE VehicleID = id

            int affectedRows = pstmt.executeUpdate();
            if (affectedRows == 0) {
                logger.warn("Soft-delete failed: Vehicle with ID {} not found.", id);
                throw new DatabaseAccessException("Vehicle with ID " + id + " not found for soft-deletion.");
            } else {
                logger.info("Vehicle with ID {} soft-deleted successfully.", id);
            }
        } catch (SQLException e) {
            String errorMsg = "Error soft-deleting vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- VehicleDataAccess Specific Implementations ---

    @Override
    public Optional<Vehicle> findByVehicleNumber(String vehicleNumber) throws DatabaseAccessException {
        Objects.requireNonNull(vehicleNumber, "Vehicle number cannot be null for findByVehicleNumber.");
        String trimmedVehicleNumber = vehicleNumber.trim();
        if (trimmedVehicleNumber.isEmpty()) {
            throw new DatabaseAccessException("Vehicle number cannot be empty for findByVehicleNumber.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_VEHICLE_NUMBER)) {

            pstmt.setString(1, trimmedVehicleNumber);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToVehicle(rs));
                }
            }
            return Optional.empty();
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicle by number '" + trimmedVehicleNumber + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public Optional<Vehicle> findActiveVehicle() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_ACTIVE_VEHICLE);
             ResultSet rs = pstmt.executeQuery()) {

            // As per business rule, there should be at most one.
            if (rs.next()) {
                Vehicle activeVehicle = mapResultSetToVehicle(rs);
                if (rs.next()) { // Check if there's a second active vehicle (data integrity issue)
                    String warningMsg = "WARNING: Multiple active vehicles found, violating business rule! " +
                            "First ID: " + activeVehicle.getVehicleID() + ", Second ID: " + rs.getInt("VehicleID") + " and possibly more.";
                    logger.warn(warningMsg);
                    // For now, return the first one found, but this indicates a problem to be addressed at service layer.
                }
                return Optional.of(activeVehicle);
            }
            return Optional.empty();
        } catch (SQLException e) {
            String errorMsg = "Error finding active vehicle: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public List<Vehicle> findByMake(String make) throws DatabaseAccessException {
        Objects.requireNonNull(make, "Make cannot be null for findByMake.");
        String trimmedMake = make.trim();
        if (trimmedMake.isEmpty()) {
            throw new DatabaseAccessException("Make cannot be empty for findByMake.");
        }
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_MAKE)) {

            pstmt.setString(1, trimmedMake);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by make '" + trimmedMake + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public List<Vehicle> findByModel(String model) throws DatabaseAccessException {
        Objects.requireNonNull(model, "Model cannot be null for findByModel.");
        String trimmedModel = model.trim();
        if (trimmedModel.isEmpty()) {
            throw new DatabaseAccessException("Model cannot be empty for findByModel.");
        }
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_MODEL)) {

            pstmt.setString(1, trimmedModel);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by model '" + trimmedModel + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    @Override
    public List<Vehicle> findByYear(int year) throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_YEAR)) {

            pstmt.setInt(1, year);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by year " + year + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }
}