package com.avaruusstudios.vmdb.implementation.sqlite;

import com.avaruusstudios.vmdb.data.DatabaseAccessException;
import com.avaruusstudios.vmdb.data.VehicleDataAccess;
import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Vehicle; // Ensure this is the updated Vehicle model
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * SQLite implementation of the {@link VehicleDataAccess} interface for the
 * Vanpool Management Database (VMDB) application. This class interacts with
 * an SQLite database to perform CRUD operations and specific queries for
 * {@link Vehicle} entities.
 * </p>
 *
 * <p>
 * This implementation adheres to the generic DAO interfaces and leverages
 * {@link DatabaseManager} for connection handling and {@link QueryLoader}
 * for SQL query management. Key characteristics include:
 * </p>
 * <ul>
 * <li>Vehicle IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `VehicleNumber` is enforced at the database level via a unique constraint.</li>
 * <li>Deletion of vehicle records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to {@code 0} (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>Robust null handling for database operations, ensuring correct mapping between
 * Java types (e.g., {@link Integer}, {@link BigDecimal}, {@link LocalDate}, {@link LocalDateTime})
 * and SQLite `TEXT`, `INTEGER`, `NUMERIC` types.</li>
 * <li>SQL queries are loaded dynamically from external `.sql` files via {@link QueryLoader},
 * ensuring separation of concerns and ease of maintenance.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0 (Initial SQLite implementation)
 * Created On: 2025-07-13
 * Updated On: 2025-07-13
 *
 * @see VehicleDataAccess
 * @see Vehicle
 * @see DatabaseAccessException
 * @see DatabaseManager
 * @see QueryLoader
 */
public class VehicleImplementation implements VehicleDataAccess {

    /**
     * SLF4J logger for logging events and errors in the VehicleImplementation class.
     */
    private static final Logger logger = LoggerFactory.getLogger(VehicleImplementation.class);

    /**
     * Date formatter for converting between {@link LocalDate} and `TEXT` representation
     * (e.g., "dd-MMM-yyyy") in the SQLite database. Uses {@link Locale#ENGLISH} for consistency.
     */
    private static final DateTimeFormatter CUSTOM_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy", Locale.ENGLISH);

    /**
     * Date/time formatter for converting between {@link LocalDateTime} and `TEXT` representation
     * (e.g., "dd-MMM-yyyy HH:mm") in the SQLite database. Uses {@link Locale#ENGLISH} for consistency.
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new vehicle record. Loaded from `vehicle/insertVehicle.sql`. */
    private static final String SQL_CREATE_VEHICLE;
    /** SQL query to select a vehicle record by its unique ID. Loaded from `vehicle/selectVehicleById.sql`. */
    private static final String SQL_READ_VEHICLE_BY_ID;
    /** SQL query to select all vehicle records. Loaded from `vehicle/selectAllVehicles.sql`. */
    private static final String SQL_READ_ALL_VEHICLES;
    /** SQL query to count the total number of vehicle records. Loaded from `vehicle/countVehicles.sql`. */
    private static final String SQL_COUNT_VEHICLES;
    /** SQL query to check if a vehicle record with a given ID exists. Loaded from `vehicle/existsVehicleById.sql`. */
    private static final String SQL_EXISTS_VEHICLE_BY_ID;
    /** SQL query to update an existing vehicle record. Loaded from `vehicle/updateVehicle.sql`. */
    private static final String SQL_UPDATE_VEHICLE;
    /** SQL query to soft-delete a vehicle record by setting its `IsActive` flag to false and `DeletedAt` timestamp. Loaded from `vehicle/deleteVehicleSoft.sql`. */
    private static final String SQL_SOFT_DELETE_VEHICLE;
    /** SQL query to find a vehicle by its unique vehicle number. Loaded from `vehicle/selectVehicleByVehicleNumber.sql`. */
    private static final String SQL_FIND_BY_VEHICLE_NUMBER;
    /** SQL query to find the single active vehicle (based on a business rule, though the query might return more if data integrity is compromised). Loaded from `vehicle/selectActiveVehicle.sql`. */
    private static final String SQL_FIND_ACTIVE_VEHICLE;
    /** SQL query to find vehicles by their make. Loaded from `vehicle/selectVehiclesByMake.sql`. */
    private static final String SQL_FIND_BY_MAKE;
    /** SQL query to find vehicles by their model. Loaded from `vehicle/selectVehiclesByModel.sql`. */
    private static final String SQL_FIND_BY_MODEL;
    /** SQL query to find vehicles by their manufacturing year. Loaded from `vehicle/selectVehiclesByYear.sql`. */
    private static final String SQL_FIND_BY_YEAR;

    /**
     * Static initializer block to load all SQL query strings from external files
     * using {@link QueryLoader}. This ensures queries are loaded only once when
     * the class is first accessed. Any {@link IllegalArgumentException} during
     * loading (e.g., file not found) is caught, logged, and re-thrown as an
     * {@link ExceptionInInitializerError} to signal a critical application setup failure.
     */
    static {
        try {
            SQL_CREATE_VEHICLE = QueryLoader.getQuery("vehicle/insertVehicle.sql");
            SQL_READ_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/selectVehicleById.sql");
            SQL_READ_ALL_VEHICLES = QueryLoader.getQuery("vehicle/selectAllVehicles.sql");
            SQL_COUNT_VEHICLES = QueryLoader.getQuery("vehicle/countVehicles.sql");
            SQL_EXISTS_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/existsVehicleById.sql");
            SQL_UPDATE_VEHICLE = QueryLoader.getQuery("vehicle/updateVehicle.sql");
            SQL_SOFT_DELETE_VEHICLE = QueryLoader.getQuery("vehicle/deleteVehicleSoft.sql");
            SQL_FIND_BY_VEHICLE_NUMBER = QueryLoader.getQuery("vehicle/selectVehicleByVehicleNumber.sql");
            SQL_FIND_ACTIVE_VEHICLE = QueryLoader.getQuery("vehicle/selectActiveVehicle.sql");
            SQL_FIND_BY_MAKE = QueryLoader.getQuery("vehicle/selectVehiclesByMake.sql");
            SQL_FIND_BY_MODEL = QueryLoader.getQuery("vehicle/selectVehiclesByModel.sql");
            SQL_FIND_BY_YEAR = QueryLoader.getQuery("vehicle/selectVehiclesByYear.sql");
            logger.info("All SQL queries for VehicleImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for VehicleImplementation. Check .sql files and paths.", e);
            // Re-throw as ExceptionInInitializerError to indicate a critical setup failure
            throw new ExceptionInInitializerError(e);
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Vehicle} object.
     * This private helper method centralizes the logic for creating {@code Vehicle} objects
     * from database results, ensuring consistency in data retrieval.
     * </p>
     * <p>
     * It handles different data types, including nullable numeric ({@link Integer}, {@link BigDecimal}),
     * date ({@link LocalDate}), and datetime ({@link LocalDateTime}) fields,
     * converting them from their SQLite `TEXT`/`INTEGER`/`NUMERIC` representations to appropriate Java types.
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing vehicle data.
     * @return A {@link Vehicle} object populated with data from the {@code ResultSet}.
     * @throws SQLException If a column is not found in the {@code ResultSet}, a data type
     * conversion error occurs, or any other database access error occurs.
     */
    private Vehicle mapResultSetToVehicle(ResultSet rs) throws SQLException {
        // Create a new Vehicle object using its default constructor.
        Vehicle vehicle = new Vehicle();

        // Retrieve and set the VehicleID. SQLite returns 0 for NULL INT columns if using getInt directly,
        // so check for positive value. The _setVehicleID method enforces immutability and validation.
        Integer vehicleID = rs.getInt("VehicleID");
        if (vehicleID > 0) { // Valid IDs are positive
            vehicle._setVehicleID(vehicleID);
        }

        // Set other properties by retrieving values from the ResultSet and using the Vehicle's public setters.
        vehicle.setVehicleNumber(rs.getString("VehicleNumber"));
        vehicle.setMake(rs.getString("Make"));
        vehicle.setModel(rs.getString("Model"));

        // For nullable Integer 'Year', use getObject with Integer.class to correctly handle nulls from DB.
        vehicle.setYear(rs.getObject("Year", Integer.class));

        vehicle.setCapacity(rs.getInt("Capacity")); // NOT NULL, int automatically handles non-null

        // Handle LeaseStartDate (TEXT in DB -> LocalDate in Java, NOT NULL).
        vehicle.setLeaseStartDate(LocalDate.parse(rs.getString("LeaseStartDate"), CUSTOM_DATE_FORMATTER));

        // Handle LeaseEndDate (TEXT in DB -> LocalDate in Java, Nullable).
        String leaseEndDateStr = rs.getString("LeaseEndDate");
        vehicle.setLeaseEndDate(leaseEndDateStr != null && !leaseEndDateStr.isEmpty() ?
                LocalDate.parse(leaseEndDateStr, CUSTOM_DATE_FORMATTER) : null);

        // Handle Discount (NUMERIC/REAL in DB -> BigDecimal in Java, Nullable).
        // Use getObject with BigDecimal.class for robust null handling of numeric types.
        vehicle.setDiscount(rs.getObject("Discount", BigDecimal.class));

        // Handle IsActive (INTEGER in DB -> boolean in Java, NOT NULL). SQLite stores booleans as 0 or 1.
        vehicle.setIsActive(rs.getInt("IsActive") == 1);

        // Handle DeletedAt (TEXT in DB -> LocalDateTime in Java, Nullable).
        String deletedAtStr = rs.getString("DeletedAt");
        vehicle.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ?
                LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        vehicle.setNotes(rs.getString("Notes")); // Nullable, getString returns null for DB NULL

        return vehicle;
    }

    // --- CreateDataAccess Implementation ---

    /**
     * <p>
     * Inserts a new {@link Vehicle} record into the SQLite database.
     * Upon successful insertion, the database-generated `VehicleID` is
     * injected back into the provided {@link Vehicle} object via its
     * package-private `_setVehicleID` method.
     * </p>
     * <p>
     * This method validates essential {@code Vehicle} properties before execution
     * and handles potential SQL exceptions, rethrowing them as {@link DatabaseAccessException}.
     * It also specifically catches unique constraint violations for `VehicleNumber`.
     * </p>
     *
     * @param vehicle The {@link Vehicle} object containing the data to be inserted.
     * Its `VehicleID` should typically be `null` or ignored as it's
     * auto-generated by the database.
     * @return The same {@link Vehicle} object, updated with its new database-assigned `VehicleID`.
     * @throws DatabaseAccessException if a database access error occurs (e.g., connection issues,
     * SQL syntax errors, or a `VehicleNumber` unique constraint violation).
     * @throws NullPointerException    if the provided {@code vehicle} object itself, or any of its
     * mandatory (NOT NULL) fields (`VehicleNumber`, `Capacity`, `LeaseStartDate`), is {@code null}.
     * @throws IllegalArgumentException if `VehicleNumber` is an empty string after trimming.
     */
    @Override
    public Vehicle createRecord(Vehicle vehicle) throws DatabaseAccessException {
        // Pre-conditions: Validate input object and its essential properties.
        Objects.requireNonNull(vehicle, "Vehicle cannot be null for createRecord.");
        Objects.requireNonNull(vehicle.getVehicleNumber(), "Vehicle number cannot be null for createRecord.");
        Objects.requireNonNull(vehicle.getCapacity(), "Vehicle capacity cannot be null for createRecord (NOT NULL constraint).");
        Objects.requireNonNull(vehicle.getLeaseStartDate(), "Vehicle lease start date cannot be null for createRecord (NOT NULL constraint).");
        // vehicle.isActive() is a primitive boolean, so it cannot be null.

        String vehicleNumber = vehicle.getVehicleNumber().trim();
        if (vehicleNumber.isEmpty()) {
            throw new IllegalArgumentException("Vehicle number cannot be empty for createRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             // Prepare the statement to return auto-generated keys (the VehicleID)
             PreparedStatement pstmt = connection.prepareStatement(SQL_CREATE_VEHICLE, Statement.RETURN_GENERATED_KEYS)) {

            int paramIndex = 1;
            // Set parameters for the PreparedStatement, handling nullable fields appropriately.
            pstmt.setString(paramIndex++, vehicleNumber);
            pstmt.setString(paramIndex++, vehicle.getMake()); // Nullable
            pstmt.setString(paramIndex++, vehicle.getModel()); // Nullable
            // Use setInt for non-null year, setNull for null Integer year with Types.INTEGER.
            if (vehicle.getYear() != null) {
                pstmt.setInt(paramIndex++, vehicle.getYear());
            } else {
                pstmt.setNull(paramIndex++, Types.INTEGER);
            }
            pstmt.setInt(paramIndex++, vehicle.getCapacity()); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseStartDate().format(CUSTOM_DATE_FORMATTER)); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseEndDate() != null ? vehicle.getLeaseEndDate().format(CUSTOM_DATE_FORMATTER) : null); // Nullable
            // Use setBigDecimal for BigDecimal, setNull with Types.NUMERIC for nulls.
            if (vehicle.getDiscount() != null) {
                pstmt.setBigDecimal(paramIndex++, vehicle.getDiscount());
            } else {
                pstmt.setNull(paramIndex++, Types.NUMERIC);
            }
            pstmt.setInt(paramIndex++, vehicle.isActive() ? 1 : 0); // NOT NULL (boolean to int)
            pstmt.setString(paramIndex++, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null); // Nullable
            pstmt.setString(paramIndex++, vehicle.getNotes()); // Nullable

            int affectedRows = pstmt.executeUpdate(); // Execute the insert operation
            if (affectedRows == 0) {
                logger.error("Creating vehicle failed, no rows affected for vehicle number: {}.", vehicle.getVehicleNumber());
                throw new DatabaseAccessException("Creating vehicle failed, no rows affected.");
            }

            // Retrieve the auto-generated VehicleID
            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    int id = generatedKeys.getInt(1); // Get the first (and only) generated key
                    logger.info("Vehicle created successfully with ID: {}.", id);
                    // Update the *original* vehicle object with the database-assigned ID.
                    vehicle._setVehicleID(id);
                    return vehicle; // Return the updated object
                } else {
                    logger.error("Creating vehicle failed, no ID obtained for vehicle number: {}.", vehicle.getVehicleNumber());
                    throw new DatabaseAccessException("Creating vehicle failed, no ID obtained.");
                }
            }

        } catch (SQLException e) {
            String errorMsg = "Error creating vehicle '" + vehicle.getVehicleNumber() + "': " + e.getMessage();
            logger.error(errorMsg, e);
            // Check for specific SQL error code for unique constraint violation (SQLite error code 19)
            if (e.getErrorCode() == 19) {
                throw new DatabaseAccessException("Vehicle with number '" + vehicle.getVehicleNumber() + "' already exists. Vehicle numbers must be unique.", e);
            }
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- ReadDataAccess Implementation ---

    /**
     * <p>
     * Retrieves a single {@link Vehicle} record from the database by its unique identifier.
     * </p>
     *
     * @param id The unique integer ID of the vehicle to retrieve. Must not be {@code null} and must be positive.
     * @return An {@link Optional} containing the {@link Vehicle} object if found,
     * or an empty {@link Optional} if no vehicle with the given ID exists.
     * @throws DatabaseAccessException  if a database access error occurs during retrieval.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public Optional<Vehicle> readRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for readRecord.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for readRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_VEHICLE_BY_ID)) {

            pstmt.setInt(1, id); // Set the ID parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    // If a record is found, map it to a Vehicle object.
                    return Optional.of(mapResultSetToVehicle(rs));
                }
            }
            return Optional.empty(); // No record found with the given ID
        } catch (SQLException e) {
            String errorMsg = "Error reading vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Retrieves all {@link Vehicle} records currently stored in the database.
     * </p>
     *
     * @return A {@link List} of {@link Vehicle} objects. The list will be empty if no vehicles are found.
     * @throws DatabaseAccessException if a database access error occurs during retrieval.
     */
    @Override
    public List<Vehicle> readRecordAll() throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_READ_ALL_VEHICLES);
             ResultSet rs = pstmt.executeQuery()) { // Execute query directly since no parameters

            while (rs.next()) {
                // Iterate through the ResultSet and map each row to a Vehicle object.
                vehicles.add(mapResultSetToVehicle(rs));
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error reading all vehicles: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Counts the total number of vehicle records in the database.
     * </p>
     *
     * @return The total count of vehicles as a {@code long}.
     * @throws DatabaseAccessException if a database access error occurs during counting.
     */
    @Override
    public long countRecord() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_COUNT_VEHICLES);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                return rs.getLong(1); // The count is typically in the first column of the result set.
            }
            return 0; // Should not happen for a COUNT(*) query, but as a fallback.
        } catch (SQLException e) {
            String errorMsg = "Error counting vehicles: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Checks if a vehicle record with the specified ID exists in the database.
     * </p>
     *
     * @param id The unique integer ID of the vehicle to check for existence. Must not be {@code null} and must be positive.
     * @return {@code true} if a vehicle with the given ID exists, {@code false} otherwise.
     * @throws DatabaseAccessException  if a database access error occurs during the check.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for existsById.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for existsById.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_EXISTS_VEHICLE_BY_ID)) {

            pstmt.setInt(1, id); // Set the ID parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                return rs.next(); // If rs.next() returns true, a record was found.
            }
        } catch (SQLException e) {
            String errorMsg = "Error checking existence for vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- UpdateDataAccess Implementation ---

    /**
     * <p>
     * Updates an existing {@link Vehicle} record in the database.
     * The update operation is based on the `VehicleID` of the provided {@link Vehicle} object.
     * </p>
     * <p>
     * This method validates essential {@code Vehicle} properties before execution and
     * handles potential SQL exceptions, rethrowing them as {@link DatabaseAccessException}.
     * It also specifically catches unique constraint violations if the updated `VehicleNumber`
     * conflicts with an existing vehicle's number.
     * </p>
     *
     * @param vehicle The {@link Vehicle} object containing the updated data.
     * Its `VehicleID` must not be {@code null} and must be positive.
     * @throws DatabaseAccessException  if a database access error occurs (e.g., connection issues,
     * SQL syntax errors, or a `VehicleNumber` unique constraint violation).
     * @throws NullPointerException     if the provided {@code vehicle} object itself, its `VehicleID`,
     * or any of its mandatory (NOT NULL) fields (`VehicleNumber`, `Capacity`, `LeaseStartDate`),
     * is {@code null}.
     * @throws IllegalArgumentException if the `VehicleID` is non-positive or if `VehicleNumber` is an empty string.
     */
    @Override
    public void updateRecord(Vehicle vehicle) throws DatabaseAccessException {
        // Pre-conditions: Validate input object and its essential properties.
        Objects.requireNonNull(vehicle, "Vehicle cannot be null for updateRecord.");
        Objects.requireNonNull(vehicle.getVehicleID(), "Vehicle ID cannot be null for updateRecord.");
        if (vehicle.getVehicleID() <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for updateRecord.");
        }
        Objects.requireNonNull(vehicle.getVehicleNumber(), "Vehicle number cannot be null for updateRecord.");
        Objects.requireNonNull(vehicle.getCapacity(), "Vehicle capacity cannot be null for updateRecord (NOT NULL constraint).");
        Objects.requireNonNull(vehicle.getLeaseStartDate(), "Vehicle lease start date cannot be null for updateRecord (NOT NULL constraint).");

        String vehicleNumber = vehicle.getVehicleNumber().trim();
        if (vehicleNumber.isEmpty()) {
            throw new IllegalArgumentException("Vehicle number cannot be empty for updateRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_UPDATE_VEHICLE)) {

            int paramIndex = 1;
            // Set parameters for the PreparedStatement, handling nullable fields appropriately.
            pstmt.setString(paramIndex++, vehicleNumber);
            pstmt.setString(paramIndex++, vehicle.getMake()); // Nullable
            pstmt.setString(paramIndex++, vehicle.getModel()); // Nullable
            if (vehicle.getYear() != null) {
                pstmt.setInt(paramIndex++, vehicle.getYear());
            } else {
                pstmt.setNull(paramIndex++, Types.INTEGER);
            }
            pstmt.setInt(paramIndex++, vehicle.getCapacity()); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseStartDate().format(CUSTOM_DATE_FORMATTER)); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getLeaseEndDate() != null ? vehicle.getLeaseEndDate().format(CUSTOM_DATE_FORMATTER) : null); // Nullable
            if (vehicle.getDiscount() != null) {
                pstmt.setBigDecimal(paramIndex++, vehicle.getDiscount());
            } else {
                pstmt.setNull(paramIndex++, Types.NUMERIC);
            }
            pstmt.setInt(paramIndex++, vehicle.isActive() ? 1 : 0); // NOT NULL
            pstmt.setString(paramIndex++, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null); // Nullable
            pstmt.setString(paramIndex++, vehicle.getNotes()); // Nullable
            pstmt.setInt(paramIndex++, vehicle.getVehicleID()); // WHERE clause parameter (unique ID for the record to update)

            int affectedRows = pstmt.executeUpdate(); // Execute the update operation
            if (affectedRows == 0) {
                logger.warn("Update failed: Vehicle with ID {} not found or no changes made.", vehicle.getVehicleID());
                throw new DatabaseAccessException("Vehicle with ID " + vehicle.getVehicleID() + " not found for update.");
            } else {
                logger.info("Vehicle with ID {} updated successfully.", vehicle.getVehicleID());
            }
        } catch (SQLException e) {
            String errorMsg = "Error updating vehicle with ID " + vehicle.getVehicleID() + ": " + e.getMessage();
            logger.error(errorMsg, e);
            // Check for specific SQL error code for unique constraint violation (SQLite error code 19)
            if (e.getErrorCode() == 19) {
                throw new DatabaseAccessException("Update failed: Vehicle with number '" + vehicle.getVehicleNumber() + "' already exists for another vehicle.", e);
            }
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- GenericDataAccess Implementation (Soft Delete) ---

    /**
     * <p>
     * Soft-deletes a {@link Vehicle} record from the database by setting its `IsActive` flag
     * to `0` (false) and updating the `DeletedAt` timestamp to the current date and time.
     * This method does not physically remove the record, preserving historical data.
     * </p>
     *
     * @param id The unique integer ID of the vehicle to soft-delete. Must not be {@code null} and must be positive.
     * @throws DatabaseAccessException  if a database access error occurs during deletion.
     * @throws NullPointerException     if the provided {@code id} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code id} is non-positive.
     */
    @Override
    public void deleteRecord(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for deleteRecord.");
        if (id <= 0) {
            throw new IllegalArgumentException("Vehicle ID must be positive for deleteRecord.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_SOFT_DELETE_VEHICLE)) {

            pstmt.setInt(1, 0); // Set IsActive to false (0)
            pstmt.setString(2, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // Set DeletedAt to current timestamp
            pstmt.setInt(3, id); // WHERE clause parameter (ID of the vehicle to soft-delete)

            int affectedRows = pstmt.executeUpdate(); // Execute the update operation
            if (affectedRows == 0) {
                logger.warn("Soft-delete failed: Vehicle with ID {} not found.", id);
                throw new DatabaseAccessException("Vehicle with ID " + id + " not found for soft-deletion.");
            } else {
                logger.info("Vehicle with ID {} soft-deleted successfully.", id);
            }
        } catch (SQLException e) {
            String errorMsg = "Error soft-deleting vehicle with ID " + id + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    // --- VehicleDataAccess Specific Implementations ---

    /**
     * <p>
     * Finds a {@link Vehicle} record by its unique `VehicleNumber`.
     * </p>
     *
     * @param vehicleNumber The unique string vehicle number to search for. Must not be {@code null} or empty.
     * @return An {@link Optional} containing the {@link Vehicle} object if found,
     * or an empty {@link Optional} if no vehicle with the given number exists.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code vehicleNumber} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code vehicleNumber} is an empty string after trimming.
     */
    @Override
    public Optional<Vehicle> findByVehicleNumber(String vehicleNumber) throws DatabaseAccessException {
        Objects.requireNonNull(vehicleNumber, "Vehicle number cannot be null for findByVehicleNumber.");
        String trimmedVehicleNumber = vehicleNumber.trim();
        if (trimmedVehicleNumber.isEmpty()) {
            throw new IllegalArgumentException("Vehicle number cannot be empty for findByVehicleNumber.");
        }

        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_VEHICLE_NUMBER)) {

            pstmt.setString(1, trimmedVehicleNumber); // Set the vehicle number parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return Optional.of(mapResultSetToVehicle(rs));
                }
            }
            return Optional.empty(); // No record found
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicle by number '" + trimmedVehicleNumber + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Finds the single active {@link Vehicle} record in the database.
     * This method assumes a business rule that there should be at most one
     * active vehicle at any given time.
     * </p>
     * <p>
     * If multiple active vehicles are found (indicating a data integrity issue),
     * a warning is logged, and the first one encountered is returned. The service layer
     * or data maintenance should address such integrity violations.
     * </p>
     *
     * @return An {@link Optional} containing the active {@link Vehicle} object if found,
     * or an empty {@link Optional} if no active vehicle exists.
     * @throws DatabaseAccessException if a database access error occurs during the search.
     */
    @Override
    public Optional<Vehicle> findActiveVehicle() throws DatabaseAccessException {
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_ACTIVE_VEHICLE);
             ResultSet rs = pstmt.executeQuery()) {

            if (rs.next()) {
                Vehicle activeVehicle = mapResultSetToVehicle(rs);
                // Check for additional active vehicles, which would indicate a data integrity problem.
                if (rs.next()) {
                    String warningMsg = String.format(
                            "WARNING: Multiple active vehicles found, violating business rule! " +
                                    "First ID: %d, Second ID: %d and possibly more.",
                            activeVehicle.getVehicleID(), rs.getInt("VehicleID"));
                    logger.warn(warningMsg);
                    // For now, return the first one found, but this indicates a problem to be addressed at service layer.
                }
                return Optional.of(activeVehicle);
            }
            return Optional.empty();
        } catch (SQLException e) {
            String errorMsg = "Error finding active vehicle: " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Finds all {@link Vehicle} records that match the specified make.
     * </p>
     *
     * @param make The string make of the vehicles to search for. Must not be {@code null} or empty.
     * @return A {@link List} of {@link Vehicle} objects matching the specified make.
     * The list will be empty if no vehicles are found.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code make} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code make} is an empty string after trimming.
     */
    @Override
    public List<Vehicle> findByMake(String make) throws DatabaseAccessException {
        Objects.requireNonNull(make, "Make cannot be null for findByMake.");
        String trimmedMake = make.trim();
        if (trimmedMake.isEmpty()) {
            throw new IllegalArgumentException("Make cannot be empty for findByMake.");
        }
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_MAKE)) {

            pstmt.setString(1, trimmedMake); // Set the make parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by make '" + trimmedMake + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Finds all {@link Vehicle} records that match the specified model.
     * </p>
     *
     * @param model The string model of the vehicles to search for. Must not be {@code null} or empty.
     * @return A {@link List} of {@link Vehicle} objects matching the specified model.
     * The list will be empty if no vehicles are found.
     * @throws DatabaseAccessException  if a database access error occurs during the search.
     * @throws NullPointerException     if the provided {@code model} is {@code null}.
     * @throws IllegalArgumentException if the provided {@code model} is an empty string after trimming.
     */
    @Override
    public List<Vehicle> findByModel(String model) throws DatabaseAccessException {
        Objects.requireNonNull(model, "Model cannot be null for findByModel.");
        String trimmedModel = model.trim();
        if (trimmedModel.isEmpty()) {
            throw new IllegalArgumentException("Model cannot be empty for findByModel.");
        }
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_MODEL)) {

            pstmt.setString(1, trimmedModel); // Set the model parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by model '" + trimmedModel + "': " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }

    /**
     * <p>
     * Finds all {@link Vehicle} records that were manufactured in the specified year.
     * </p>
     *
     * @param year The integer year of manufacture to search for.
     * @return A {@link List} of {@link Vehicle} objects matching the specified year.
     * The list will be empty if no vehicles are found.
     * @throws DatabaseAccessException if a database access error occurs during the search.
     */
    @Override
    public List<Vehicle> findByYear(int year) throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection connection = DatabaseManager.getConnection();
             PreparedStatement pstmt = connection.prepareStatement(SQL_FIND_BY_YEAR)) {

            pstmt.setInt(1, year); // Set the year parameter
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            return vehicles;
        } catch (SQLException e) {
            String errorMsg = "Error finding vehicles by year " + year + ": " + e.getMessage();
            logger.error(errorMsg, e);
            throw new DatabaseAccessException(errorMsg, e);
        }
    }
}