package com.avaruusstudios.vmdb.model;

import java.util.Objects;

/**
 * <p>
 * Represents a classification for financial transactions within the Vanpool Management System.
 * Categories help organize and analyze income, expenses, and credits.
 * </p>
 *
 * <p>
 * This class maps directly to the `Categories` table in the database.
 * Each category is uniquely identified by an ID, has a required name,
 * an optional description, and a specific {@link CategoryType} (Income, Expense, or Credit).
 * </p>
 *
 * <p>
 * **Business Rule for Participant Association:**
 * <ul>
 * <li>If {@link #categoryType} is {@link CategoryType#INCOME}, the category MUST be
 * associated with a specific {@link Participant} (i.e., {@link #participant} cannot be {@code null}).
 * This signifies income received from or on behalf of that participant.</li>
 * <li>If {@link #categoryType} is {@link CategoryType#EXPENSE} or {@link CategoryType#CREDIT},
 * the category MUST NOT be associated with a specific {@link Participant}
 * (i.e., {@link #participant} must be {@code null}). These are general vanpool expenses/credits.</li>
 * </ul>
 * </p>
 *
 * @see CategoryType
 * @see Participant
 * @see Transaction
 * @see InvoiceItem
 */
public class Category {
    /**
     * <p>
     * The unique identifier for this category.
     * </p>
     * <p>
     * This field serves as the **primary key** in the database's {@code Categories} table
     * ({@code CategoryID INTEGER PRIMARY KEY AUTOINCREMENT}). It ensures that each category record
     * is uniquely identifiable and allows for efficient retrieval and referencing.
     * This ID is typically auto-generated by the database upon insertion.
     * </p>
     * <p>
     * For a newly created category not yet persisted to the database, this value will be {@code null}.
     * Once assigned by the database, it becomes immutable.
     * </p>
     */
    private final Integer categoryID; // Remains final Integer
    /**
     * <p>
     * The {@link Participant} object this category is tied to, if any.
     * </p>
     * <p>
     * This field represents a **foreign key relationship** to the {@code Participants} table
     * (corresponding to {@code ParticipantID_FK INTEGER} in the database).
     * Its nullability depends on the {@link #categoryType} as per business rules:
     * <ul>
     * <li>**REQUIRED** (non-{@code null}) if {@link #categoryType} is {@link CategoryType#INCOME}.</li>
     * <li>**MUST BE NULL** if {@link #categoryType} is {@link CategoryType#EXPENSE} or {@link CategoryType#CREDIT}.</li>
     * </ul>
     * </p>
     */
    private Participant participant;
    /**
     * <p>
     * The type of the category, restricting values to {@link CategoryType#INCOME},
     * {@link CategoryType#EXPENSE}, or {@link CategoryType#CREDIT}.
     * </p>
     * <p>
     * This enum field provides a strong type-safe way to classify the category's nature,
     * directly mapping to a {@code TEXT NOT NULL} column in the database, where the enum's
     * name (e.g., "INCOME") would be stored. This field is **mutable** and validated via its setter.
     * </p>
     * @see CategoryType
     */
    private CategoryType categoryType; // Changed to mutable (not final)
    /**
     * <p>
     * The user-friendly name of the category (e.g., "Fuel", "Van Rental", "Participant Payment").
     * </p>
     * <p>
     * This string field provides a concise and human-readable label for the category.
     * It maps directly to the {@code CategoryName TEXT NOT NULL UNIQUE} column in the database.
     * This name should be **unique** across all categories, regardless of type or participant,
     * to prevent ambiguity when retrieving categories by name. This field is **mutable**.
     * </p>
     */
    private String categoryName; // Remains mutable
    /**
     * <p>
     * A longer, optional description providing more detailed information about the category's purpose or usage.
     * </p>
     * <p>
     * This field allows for additional context beyond the {@link #categoryName}.
     * It maps to the {@code Description TEXT} column in the database, which is nullable,
     * meaning it can be {@code null} or an empty string if no further details are needed.
     * </p>
     */
    private String description;

    /**
     * <p>
     * Default constructor for creating a new {@code Category} object.
     * </p>
     * <p>
     * This constructor initializes {@code categoryID} to {@code null} and other fields to
     * their default values ({@code null}). It is useful for frameworks (like ORMs or
     * deserializers) that instantiate objects via reflection and then populate them
     * using setters. When used in application code, all required fields
     * ({@link #categoryType} and {@link #categoryName}) and the associated
     * {@link #participant} (if {@link CategoryType#INCOME}) must be set subsequently
     * using the appropriate setters.
     * </p>
     */
    public Category() {
        this.categoryID = null; // Explicitly null for unpersisted entity
        // Other fields will be null/default and set via setters
    }
    /**
     * <p>
     * Full constructor to initialize all fields of a {@code Category} instance.
     * </p>
     * <p>
     * This constructor allows for the comprehensive creation of a category record,
     * aligning with the database schema and object relationships. It's typically used
     * when retrieving an existing category from the database where all values,
     * including the auto-generated {@code categoryID}, are already known.
     * </p>
     *
     * @param categoryID   The unique integer ID for the category. Must not be {@code null} for existing.
     * @param participant  The {@link Participant} object this category is tied to, or {@code null}.
     * @param categoryType The {@link CategoryType} (Income, Expense, Credit). Must not be {@code null}.
     * @param categoryName The name of the category. Must not be {@code null} or empty after trimming.
     * @param description  An optional longer description of the category. Can be {@code null}.
     * @throws NullPointerException     if {@code categoryID}, {@code categoryType} or {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming,
     * or if participant/categoryType business rules are violated.
     */
    public Category(Integer categoryID, Participant participant, CategoryType categoryType, String categoryName, String description) {
        this.categoryID = Objects.requireNonNull(categoryID, "CategoryID cannot be null for an existing category.");
        setCategoryType(categoryType); // Use setter for validation
        setParticipant(participant);   // Use setter for validation (will internally check against this.categoryType)
        setCategoryName(categoryName); // Use setter for validation
        this.description = description; // Can be null
    }
    /**
     * <p>
     * Convenience constructor for creating a new {@code Category} object that doesn't yet have a database ID.
     * </p>
     * <p>
     * This constructor is ideal when preparing a new category record for **insertion** into the database.
     * The {@code categoryID} is omitted as it is typically auto-generated by the database.
     * </p>
     *
     * @param participant  The {@link Participant} object this category is tied to, or {@code null}.
     * @param categoryType The {@link CategoryType} (Income, Expense, Credit). Must not be {@code null}.
     * @param categoryName The name of the category. Must not be {@code null} or empty after trimming.
     * @param description  An optional longer description of the category. Can be {@code null}.
     * @throws NullPointerException     if {@code categoryType} or {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming,
     * or if participant/categoryType business rules are violated.
     */
    public Category(Participant participant, CategoryType categoryType, String categoryName, String description) {
        this.categoryID = null; // New entity, ID will be assigned by DB, so it's null
        setCategoryType(categoryType); // Use setter for validation
        setParticipant(participant);   // Use setter for validation (will internally check against this.categoryType)
        setCategoryName(categoryName); // Use setter for validation
        this.description = description; // Can be null
    }
    /**
     * Internal helper method to validate the coupling between CategoryType and Participant.
     * This method is called by constructors and `setParticipant`.
     *
     * @param type The CategoryType to validate against.
     * @param participant The Participant to validate.
     * @throws IllegalArgumentException if business rules for participant/categoryType coupling are violated.
     */
    private void validateCategoryTypeAndParticipant(CategoryType type, Participant participant) {
        if (type == CategoryType.INCOME) {
            if (participant == null) {
                throw new IllegalArgumentException("An INCOME category must be associated with a Participant.");
            }
        } else if (type == CategoryType.EXPENSE || type == CategoryType.CREDIT) {
            if (participant != null) {
                throw new IllegalArgumentException("An " + type.getDbValue() + " category cannot be associated with a Participant.");
            }
        }
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * <p>
     * Retrieves the unique identifier for this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryID} column in the database.
     * For new, unpersisted categories, this will be {@code null}.
     * </p>
     *
     * @return The {@link Integer} primary key used to identify this category record, or {@code null} if not yet assigned.
     */
    public Integer getCategoryID() {
        return categoryID;
    }

    // setCategoryID is not provided as categoryID is final and set via constructors or by DAO (not via public setter)

    /**
     * <p>
     * Retrieves the {@link Participant} object this category is tied to.
     * </p>
     * <p>
     * This corresponds to the {@code ParticipantID_FK} column in the database.
     * Its nullability depends on the {@link #categoryType}.
     * </p>
     *
     * @return The associated {@link Participant} object, or {@code null} if the category is not participant-specific.
     */
    public Participant getParticipant() {
        return participant;
    }
    /**
     * <p>
     * Sets the {@link Participant} object this category is tied to.
     * </p>
     * <p>
     * This method enforces the business rules regarding participant association:
     * <ul>
     * <li>An `INCOME` category MUST be associated with a non-{@code null} participant.</li>
     * <li>`EXPENSE` and `CREDIT` categories MUST be associated with a {@code null} participant.</li>
     * </ul>
     * </p>
     *
     * @param participant The {@link Participant} object to set, or {@code null}.
     * @throws IllegalArgumentException if the participant assignment violates business rules
     * based on the category's {@link CategoryType}.
     * @throws IllegalStateException if `categoryType` is not yet set when attempting to set participant (e.g., after default constructor).
     */
    public void setParticipant(Participant participant) {
        // Ensure categoryType is set before attempting to validate participant based on it
        if (this.categoryType == null) {
            throw new IllegalStateException("CategoryType must be set before setting a Participant for this category.");
        }
        validateCategoryTypeAndParticipant(this.categoryType, participant);
        this.participant = participant;
    }
    /**
     * <p>
     * Retrieves the type of this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryType} column in the database.
     * </p>
     *
     * @return The {@link CategoryType} enum constant (Income, Expense, or Credit).
     */
    public CategoryType getCategoryType() {
        return categoryType;
    }
    /**
     * <p>
     * Sets the {@link CategoryType} for this category.
     * </p>
     * <p>
     * This field is mapped as {@code NOT NULL} in the database schema,
     * so it's important to ensure a valid {@link CategoryType} is always provided.
     * If a {@code null} value is attempted, a {@link NullPointerException} will be thrown.
     * This setter also triggers validation for {@link #participant} association based on the new type.
     * </p>
     *
     * @param categoryType The {@link CategoryType} to set. Must not be {@code null}.
     * @throws NullPointerException if {@code categoryType} is {@code null}.
     * @throws IllegalArgumentException if the current {@link #participant} association
     * violates business rules for the newly set {@link CategoryType}.
     */
    public void setCategoryType(CategoryType categoryType) {
        Objects.requireNonNull(categoryType, "CategoryType cannot be null.");
        // Validate participant association against the *new* type being set
        validateCategoryTypeAndParticipant(categoryType, this.participant);
        this.categoryType = categoryType;
    }
    /**
     * <p>
     * Retrieves the name of this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryName} column in the database.
     * </p>
     *
     * @return The name of the category.
     */
    public String getCategoryName() {
        return categoryName;
    }
    /**
     * <p>
     * Sets the name of this category.
     * </p>
     * <p>
     * This field is mapped as {@code NOT NULL UNIQUE} in the database schema,
     * so it's important to ensure a non-{@code null} and non-empty name is always provided.
     * Leading/trailing whitespace will be trimmed.
     * </p>
     *
     * @param categoryName The name of the category to set. Must not be {@code null} or empty.
     * @throws NullPointerException if {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming.
     */
    public void setCategoryName(String categoryName) {
        String trimmedName = Objects.requireNonNull(categoryName, "CategoryName cannot be null.").strip();
        if (trimmedName.isEmpty()) {
            throw new IllegalArgumentException("CategoryName cannot be empty.");
        }
        this.categoryName = trimmedName;
    }
    /**
     * <p>
     * Retrieves the description of this category.
     * </p>
     * <p>
     * Corresponds to the {@code Description} column in the database.
     * </p>
     *
     * @return A string containing the description, or {@code null} if no description is present.
     */
    public String getDescription() {
        return description;
    }
    /**
     * <p>
     * Sets the description for this category.
     * </p>
     * <p>
     * This field is nullable in the database schema, so it can be set to {@code null}
     * or an empty string if no detailed description is required.
     * </p>
     *
     * @param description The string containing the description to set. Can be {@code null}.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code Category} object.
     * </p>
     * <p>
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the category's key attributes.
     * The format includes the category ID, name, type, and associated participant ID (if any).
     * </p>
     *
     * @return A string in the format:
     * "Category{ID=..., Name='...', Type=..., ParticipantID=...}"
     */
    @Override
    public String toString() {
        return "Category{" +
                "categoryID=" + categoryID +
                ", categoryName='" + categoryName + '\'' +
                ", categoryType=" + categoryType +
                ", participantID=" + (participant != null ? participant.getParticipantID() : "null") +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * </p>
     * <p>
     * The comparison for {@code Category} objects is based primarily on their
     * unique {@code categoryID}. This ensures that two category objects
     * representing the same database record are considered equal.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections. It correctly handles
     * {@code null} for `categoryID` in unpersisted entities.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        // Equality is based on the primary key (categoryID), safely handling null Integer
        return Objects.equals(categoryID, category.categoryID);
    }
    /**
     * <p>
     * Returns a hash code value for the object.
     * </p>
     * <p>
     * This method is supported for the benefit of hash tables such as those
     * provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * The hash code is generated solely based on the unique {@code categoryID}.
     * </p>
     * <p>
     * This ensures that objects considered equal by {@link #equals(Object)} will
     * have the same hash code, fulfilling the contract between {@code equals} and
     * {@code hashCode}, which is essential for correct behavior in hash-based collections.
     * It correctly handles {@code null} for `categoryID` in unpersisted entities.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(categoryID);
    }
}