package com.avaruusstudios.vmdb.model;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import java.time.LocalDate; // For DeletedAt
import java.util.Objects;

/**
 * <p>
 * Represents a classification for financial transactions within the Vanpool Management System.
 * Categories help organize and analyze income, expenses, and credits.
 * </p>
 *
 * <p>
 * This class maps directly to the `Categories` table in the database.
 * Each category is uniquely identified by an ID, has a required name,
 * an optional description, and a specific {@link CategoryType} (Income, Expense, or Credit).
 * It also includes fields for tracking its active status and soft-deletion.
 * </p>
 *
 * <p>
 * **Business Rule for Participant Association:**
 * <ul>
 * <li>If {@link #categoryTypeProperty()} is {@link CategoryType#INCOME}, the category MUST be
 * associated with a specific {@link Participant} (i.e., {@link #participantProperty()} cannot be {@code null}).
 * This signifies income received from or on behalf of that participant.</li>
 * <li>If {@link #categoryTypeProperty()} is {@link CategoryType#EXPENSE} or {@link CategoryType#CREDIT},
 * the category MUST NOT be associated with a specific {@link Participant}
 * (i.e., {@link #participantProperty()} must be {@code null}). These are general vanpool expenses/credits.</li>
 * </ul>
 * </p>
 *
 * @author AvaruusStudios
 * @version 1.1
 * Created On: 2025-07-11
 * Updated On: 2025-07-11
 *
 * @see CategoryType
 * @see Participant
 * @see Transaction
 * @see LineItem
 */
public class Category {
    /**
     * <p>
     * The unique identifier for this category.
     * </p>
     * <p>
     * This field serves as the **primary key** in the database's {@code Categories} table
     * ({@code CategoryID INTEGER PRIMARY KEY AUTOINCREMENT}). It ensures that each category record
     * is uniquely identifiable and allows for efficient retrieval and referencing.
     * This ID is typically auto-generated by the database upon insertion.
     * </p>
     * <p>
     * For a newly created category not yet persisted to the database, this value will be {@code null}.
     * Once assigned by the database, it becomes immutable and is exposed as a {@link ReadOnlyObjectProperty}.
     * </p>
     */
    private final ReadOnlyObjectProperty<Integer> categoryID;
    /**
     * <p>
     * The {@link Participant} object this category is tied to, if any.
     * </p>
     * <p>
     * This field represents a **foreign key relationship** to the {@code Participants} table
     * (corresponding to {@code ParticipantID_FK INTEGER} in the database). The underlying
     * database column stores the participant's ID, while this POJO directly holds the
     * {@link Participant} object for convenience and to facilitate business rules.
     * </p>
     * <p>
     * Its nullability depends on the {@link #categoryTypeProperty()} as per business rules:
     * <ul>
     * <li>**REQUIRED** (non-{@code null}) if {@link #categoryTypeProperty()} is {@link CategoryType#INCOME}.</li>
     * <li>**MUST BE NULL** if {@link #categoryTypeProperty()} is {@link CategoryType#EXPENSE} or {@link CategoryType#CREDIT}.</li>
     * </ul>
     * This field is exposed as an {@link ObjectProperty} for data binding.
     * </p>
     */
    private final ObjectProperty<Participant> participant;
    /**
     * <p>
     * The type of the category, restricting values to {@link CategoryType#INCOME},
     * {@link CategoryType#EXPENSE}, or {@link CategoryType#CREDIT}.
     * </p>
     * <p>
     * This enum field provides a strong type-safe way to classify the category's nature,
     * directly mapping to a {@code TEXT NOT NULL} column in the database, where the enum's
     * name (e.g., "INCOME") would be stored. This field is exposed as an {@link ObjectProperty}.
     * </p>
     * @see CategoryType
     */
    private final ObjectProperty<CategoryType> categoryType;
    /**
     * <p>
     * The user-friendly name of the category (e.g., "Fuel", "Van Rental", "Participant Payment").
     * </p>
     * <p>
     * This string field provides a concise and human-readable label for the category.
     * It maps directly to the {@code CategoryName TEXT NOT NULL} column in the database.
     * This field is exposed as a {@link StringProperty}.
     * </p>
     */
    private final StringProperty categoryName;
    /**
     * <p>
     * A longer, optional description providing more detailed information about the category's purpose or usage.
     * </p>
     * <p>
     * This field allows for additional context beyond the {@link #categoryNameProperty()}.
     * It maps to the {@code Description TEXT} column in the database, which is nullable,
     * meaning it can be {@code null} or an empty string if no further details are needed.
     * This field is exposed as a {@link StringProperty}.
     * </p>
     */
    private final StringProperty description;
    /**
     * <p>
     * Indicates whether the category record is currently active (1) or inactive (0).
     * </p>
     * <p>
     * This field maps to the {@code IsActive INTEGER NOT NULL DEFAULT 1} column in the database.
     * It is used for soft-deletion and logical filtering of records,
     * allowing data to be marked as inactive without physically removing it from the database.
     * Default value is 1 (active). Exposed as an {@link IntegerProperty}.
     * </p>
     */
    private final IntegerProperty isActive;
    /**
     * <p>
     * The timestamp indicating when this record was logically deleted (soft-deleted).
     * </p>
     * <p>
     * This field maps to the {@code DeletedAt TEXT DEFAULT NULL} column in the database.
     * It stores the date and time in ISO format (e.g., "YYYY-MM-DD HH:MM:SS") when `IsActive`
     * is set to 0. A {@code null} value indicates the record is not deleted.
     * Exposed as an {@link ObjectProperty} of {@link LocalDate}.
     * </p>
     */
    private final ObjectProperty<LocalDate> deletedAt;

    /**
     * <p>
     * Default constructor for creating a new {@code Category} object.
     * </p>
     * <p>
     * This constructor initializes {@code categoryID} to {@code null} and all other fields
     * to their default JavaFX Property values (e.g., {@code null} for ObjectProperties,
     * empty string for StringProperties, 0 for IntegerProperties). It is useful for frameworks (like ORMs or
     * deserializers) that instantiate objects via reflection and then populate them
     * using setters. When used in application code, all required fields
     * ({@link #categoryTypeProperty()} and {@link #categoryNameProperty()}) and the associated
     * {@link #participantProperty()} (if {@link CategoryType#INCOME}) must be set subsequently
     * using the appropriate setters. Defaults {@code isActive} to 1.
     * </p>
     */
    public Category() {
        this.categoryID = new SimpleObjectProperty<>(this, "categoryID", null);
        this.participant = new SimpleObjectProperty<>(this, "participant");
        this.categoryType = new SimpleObjectProperty<>(this, "categoryType");
        this.categoryName = new SimpleStringProperty(this, "categoryName");
        this.description = new SimpleStringProperty(this, "description");
        this.isActive = new SimpleIntegerProperty(this, "isActive", 1); // Default to active
        this.deletedAt = new SimpleObjectProperty<>(this, "deletedAt", null); // Default to not deleted
    }

    /**
     * <p>
     * Full constructor to initialize all fields of a {@code Category} instance.
     * </p>
     * <p>
     * This constructor allows for the comprehensive creation of a category record,
     * aligning with the database schema and object relationships. It's typically used
     * when retrieving an existing category from the database where all values,
     * including the auto-generated {@code categoryID}, are already known.
     * All parameters are validated via their respective setters.
     * </p>
     *
     * @param categoryID   The unique integer ID for the category. Must not be {@code null} for existing.
     * @param participant  The {@link Participant} object this category is tied to, or {@code null}.
     * @param categoryType The {@link CategoryType} (Income, Expense, Credit). Must not be {@code null}.
     * @param categoryName The name of the category. Must not be {@code null} or empty after trimming.
     * @param description  An optional longer description of the category. Can be {@code null}.
     * @param isActive     The active status of the category (1 for active, 0 for inactive).
     * @param deletedAt    The date this category was soft-deleted, or {@code null} if not deleted.
     * @throws NullPointerException     if {@code categoryID}, {@code categoryType} or {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming,
     * or if participant/categoryType business rules are violated, or if `isActive` is not 0 or 1.
     */
    public Category(Integer categoryID, Participant participant, CategoryType categoryType, String categoryName,
                    String description, int isActive, LocalDate deletedAt) {
        this.categoryID = new SimpleObjectProperty<>(this, "categoryID", Objects.requireNonNull(categoryID, "CategoryID cannot be null for an existing category."));
        this.participant = new SimpleObjectProperty<>(this, "participant");
        this.categoryType = new SimpleObjectProperty<>(this, "categoryType");
        this.categoryName = new SimpleStringProperty(this, "categoryName");
        this.description = new SimpleStringProperty(this, "description");
        this.isActive = new SimpleIntegerProperty(this, "isActive");
        this.deletedAt = new SimpleObjectProperty<>(this, "deletedAt");

        // Setters enforce validation and business rules
        setCategoryType(categoryType);
        setParticipant(participant);   // Will internally check against this.categoryType
        setCategoryName(categoryName);
        setDescription(description);
        setIsActive(isActive);
        setDeletedAt(deletedAt);
    }

    /**
     * <p>
     * Convenience constructor for creating a new {@code Category} object that doesn't yet have a database ID.
     * </p>
     * <p>
     * This constructor is ideal when preparing a new category record for **insertion** into the database.
     * The {@code categoryID} is omitted as it is typically auto-generated by the database.
     * {@code isActive} defaults to 1 (active) and {@code deletedAt} defaults to {@code null}.
     * All parameters are validated via their respective setters.
     * </p>
     *
     * @param participant  The {@link Participant} object this category is tied to, or {@code null}.
     * @param categoryType The {@link CategoryType} (Income, Expense, Credit). Must not be {@code null}.
     * @param categoryName The name of the category. Must not be {@code null} or empty after trimming.
     * @param description  An optional longer description of the category. Can be {@code null}.
     * @throws NullPointerException     if {@code categoryType} or {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming,
     * or if participant/categoryType business rules are violated.
     */
    public Category(Participant participant, CategoryType categoryType, String categoryName, String description) {
        // Delegate to the full constructor with null categoryID and default isActive/deletedAt for a new entity
        this(null, participant, categoryType, categoryName, description, 1, null);
    }

    /**
     * Internal helper method to validate the coupling between CategoryType and Participant.
     * This method is called by constructors and `setParticipant`.
     *
     * @param type The CategoryType to validate against.
     * @param participant The Participant to validate.
     * @throws IllegalArgumentException if business rules for participant/categoryType coupling are violated.
     */
    private void validateCategoryTypeAndParticipant(CategoryType type, Participant participant) {
        if (type == CategoryType.INCOME) {
            if (participant == null) {
                throw new IllegalArgumentException("An INCOME category must be associated with a Participant.");
            }
        } else if (type == CategoryType.EXPENSE || type == CategoryType.CREDIT) {
            if (participant != null) {
                throw new IllegalArgumentException("An " + type.getDbValue() + " category cannot be associated with a Participant.");
            }
        }
    }

    // --- JavaFX Property Accessor Methods ---

    /**
     * <p>
     * Retrieves the {@link ReadOnlyObjectProperty} for the unique identifier of this category.
     * </p>
     * <p>
     * This property represents the {@code CategoryID} column in the database.
     * Its value is immutable once set (typically by the database).
     * </p>
     *
     * @return The {@link ReadOnlyObjectProperty} for {@code categoryID}.
     */
    public ReadOnlyObjectProperty<Integer> categoryIDProperty() {
        return categoryID;
    }
    /**
     * <p>
     * Retrieves the {@link ObjectProperty} for the {@link Participant} object this category is tied to.
     * </p>
     * <p>
     * This property represents the {@code ParticipantID_FK} column in the database.
     * Its nullability is governed by the {@link #categoryTypeProperty()} business rules.
     * </p>
     *
     * @return The {@link ObjectProperty} for {@code participant}.
     */
    public ObjectProperty<Participant> participantProperty() {
        return participant;
    }
    /**
     * <p>
     * Retrieves the {@link ObjectProperty} for the type of this category.
     * </p>
     * <p>
     * This property represents the {@code CategoryType} column in the database.
     * Its value must be one of {@link CategoryType#INCOME}, {@link CategoryType#EXPENSE}, or {@link CategoryType#CREDIT}.
     * </p>
     *
     * @return The {@link ObjectProperty} for {@code categoryType}.
     */
    public ObjectProperty<CategoryType> categoryTypeProperty() {
        return categoryType;
    }
    /**
     * <p>
     * Retrieves the {@link StringProperty} for the name of this category.
     * </p>
     * <p>
     * This property represents the {@code CategoryName} column in the database.
     * It holds the user-friendly name of the category.
     * </p>
     *
     * @return The {@link StringProperty} for {@code categoryName}.
     */
    public StringProperty categoryNameProperty() {
        return categoryName;
    }
    /**
     * <p>
     * Retrieves the {@link StringProperty} for the optional description of this category.
     * </p>
     * <p>
     * This property represents the {@code Description} column in the database.
     * </p>
     *
     * @return The {@link StringProperty} for {@code description}.
     */
    public StringProperty descriptionProperty() {
        return description;
    }
    /**
     * <p>
     * Retrieves the {@link IntegerProperty} for the active status of this category.
     * </p>
     * <p>
     * This property represents the {@code IsActive} column in the database (1 for active, 0 for inactive).
     * </p>
     *
     * @return The {@link IntegerProperty} for {@code isActive}.
     */
    public IntegerProperty isActiveProperty() {
        return isActive;
    }
    /**
     * <p>
     * Retrieves the {@link ObjectProperty} for the soft-deletion timestamp of this category.
     * </p>
     * <p>
     * This property represents the {@code DeletedAt} column in the database. A non-null value
     * indicates the record has been soft-deleted.
     * </p>
     *
     * @return The {@link ObjectProperty} for {@code deletedAt}.
     */
    public ObjectProperty<LocalDate> deletedAtProperty() {
        return deletedAt;
    }

    // --- Value Getters and Setters ---

    /**
     * <p>
     * Retrieves the unique identifier for this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryID} column in the database.
     * For new, unpersisted categories, this will be {@code null}.
     * </p>
     *
     * @return The {@link Integer} primary key used to identify this category record, or {@code null} if not yet assigned.
     */
    public Integer getCategoryID() {
        return categoryID.get();
    }
    /**
     * Sets the unique ID for this category. This method is designed to be package-private
     * and is primarily for use by data access objects (DAOs) when an ID is generated
     * by the database upon insertion.
     * <p>
     * It includes a check to prevent the ID from being modified once it has been set,
     * ensuring the immutability of the primary key.
     * </p>
     *
     * @param id The unique integer ID assigned by the database.
     * @throws IllegalStateException if the ID has already been assigned to this object.
     * @throws IllegalArgumentException if the provided ID is {@code null} or non-positive.
     */
    void _setCategoryID(Integer id) { // Package-private for DAO use only
        if (this.categoryID.get() != null) {
            throw new IllegalStateException("Category ID cannot be changed once set.");
        }
        if (id == null || id <= 0) {
            throw new IllegalArgumentException("Category ID cannot be null or non-positive.");
        }
        ((SimpleObjectProperty<Integer>) this.categoryID).set(id);
    }
    /**
     * <p>
     * Retrieves the {@link Participant} object this category is tied to.
     * </p>
     * <p>
     * This corresponds to the {@code ParticipantID_FK} column in the database.
     * Its nullability depends on the {@link #getCategoryType()}.
     * </p>
     *
     * @return The associated {@link Participant} object, or {@code null} if the category is not participant-specific.
     */
    public Participant getParticipant() {
        return participant.get();
    }
    /**
     * <p>
     * Sets the {@link Participant} object this category is tied to.
     * </p>
     * <p>
     * This method enforces the business rules regarding participant association:
     * <ul>
     * <li>An `INCOME` category MUST be associated with a non-{@code null} participant.</li>
     * <li>`EXPENSE` and `CREDIT` categories MUST be associated with a {@code null} participant.</li>
     * </ul>
     * </p>
     *
     * @param participant The {@link Participant} object to set, or {@code null}.
     * @throws IllegalArgumentException if the participant assignment violates business rules
     * based on the category's {@link CategoryType}.
     * @throws IllegalStateException if `categoryType` is not yet set when attempting to set participant (e.g., after default constructor).
     */
    public void setParticipant(Participant participant) {
        // Ensure categoryType is set before attempting to validate participant based on it
        if (getCategoryType() == null) {
            throw new IllegalStateException("CategoryType must be set before setting a Participant for this category.");
        }
        validateCategoryTypeAndParticipant(getCategoryType(), participant); // Validate using current type
        this.participant.set(participant);
    }
    /**
     * <p>
     * Retrieves the type of this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryType} column in the database.
     * </p>
     *
     * @return The {@link CategoryType} enum constant (Income, Expense, or Credit).
     */
    public CategoryType getCategoryType() {
        return categoryType.get();
    }
    /**
     * <p>
     * Sets the {@link CategoryType} for this category.
     * </p>
     * <p>
     * This field is mapped as {@code NOT NULL} in the database schema,
     * so it's important to ensure a valid {@link CategoryType} is always provided.
     * If a {@code null} value is attempted, a {@link NullPointerException} will be thrown.
     * This setter also triggers validation for {@link #getParticipant()} association based on the new type.
     * </p>
     *
     * @param categoryType The {@link CategoryType} to set. Must not be {@code null}.
     * @throws NullPointerException if {@code categoryType} is {@code null}.
     * @throws IllegalArgumentException if the current {@link #getParticipant()} association
     * violates business rules for the newly set {@link CategoryType}.
     */
    public void setCategoryType(CategoryType categoryType) {
        Objects.requireNonNull(categoryType, "CategoryType cannot be null.");
        // Validate participant association against the *new* type being set, using current participant value
        validateCategoryTypeAndParticipant(categoryType, getParticipant());
        this.categoryType.set(categoryType);
    }
    /**
     * <p>
     * Retrieves the name of this category.
     * </p>
     * <p>
     * Corresponds to the {@code CategoryName} column in the database.
     * </p>
     *
     * @return The name of the category.
     */
    public String getCategoryName() {
        return categoryName.get();
    }
    /**
     * <p>
     * Sets the name of this category.
     * </p>
     * <p>
     * This field is mapped as {@code NOT NULL} in the database schema,
     * so it's important to ensure a non-{@code null} and non-empty name is always provided.
     * Leading/trailing whitespace will be trimmed.
     * </p>
     *
     * @param categoryName The name of the category to set. Must not be {@code null} or empty.
     * @throws NullPointerException if {@code categoryName} is {@code null}.
     * @throws IllegalArgumentException if {@code categoryName} is empty after trimming.
     */
    public void setCategoryName(String categoryName) {
        String trimmedName = Objects.requireNonNull(categoryName, "CategoryName cannot be null.").strip();
        if (trimmedName.isEmpty()) {
            throw new IllegalArgumentException("CategoryName cannot be empty.");
        }
        this.categoryName.set(trimmedName);
    }
    /**
     * <p>
     * Retrieves the description of this category.
     * </p>
     * <p>
     * Corresponds to the {@code Description} column in the database.
     * </p>
     *
     * @return A string containing the description, or {@code null} if no description is present.
     */
    public String getDescription() {
        return description.get();
    }
    /**
     * <p>
     * Sets the description for this category.
     * </p>
     * <p>
     * This field is nullable in the database schema, so it can be set to {@code null}
     * or an empty string if no detailed description is required.
     * Leading/trailing whitespace will be trimmed if the value is not {@code null}.
     * </p>
     *
     * @param description The string containing the description to set. Can be {@code null}.
     */
    public void setDescription(String description) {
        this.description.set((description != null) ? description.strip() : null);
    }
    /**
     * <p>
     * Retrieves the active status of this category.
     * </p>
     * <p>
     * Corresponds to the {@code IsActive} column in the database (1 for active, 0 for inactive).
     * </p>
     *
     * @return An integer representing the active status (1 for true, 0 for false).
     */
    public int getIsActive() {
        return isActive.get();
    }
    /**
     * <p>
     * Sets the active status of this category.
     * </p>
     * <p>
     * This method validates that the provided value is either 1 (active) or 0 (inactive).
     * </p>
     *
     * @param isActive An integer representing the active status (1 for true, 0 for false).
     * @throws IllegalArgumentException if `isActive` is not 0 or 1.
     */
    public void setIsActive(int isActive) {
        if (isActive != 0 && isActive != 1) {
            throw new IllegalArgumentException("IsActive must be 0 (false) or 1 (true).");
        }
        this.isActive.set(isActive);
    }
    /**
     * <p>
     * Retrieves the soft-deletion timestamp for this category.
     * </p>
     * <p>
     * Corresponds to the {@code DeletedAt} column in the database.
     * </p>
     *
     * @return The {@link LocalDate} when the category was soft-deleted, or {@code null} if not deleted.
     */
    public LocalDate getDeletedAt() {
        return deletedAt.get();
    }
    /**
     * <p>
     * Sets the soft-deletion timestamp for this category.
     * </p>
     * <p>
     * Setting this field implies a soft-delete operation. This should typically be
     * used in conjunction with setting {@link #setIsActive(int) isActive} to 0.
     * </p>
     *
     * @param deletedAt The {@link LocalDate} to set, or {@code null} to indicate not deleted.
     */
    public void setDeletedAt(LocalDate deletedAt) {
        this.deletedAt.set(deletedAt);
    }

    // --- Utility Methods ---

    /**
     * <p>
     * Returns a string representation of the {@code Category} object.
     * </p>
     * <p>
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the category's key attributes.
     * The format includes the category ID, name, type, associated participant ID (if any),
     * active status, and deletion timestamp.
     * </p>
     *
     * @return A string in the format:
     * "Category{ID=..., Name='...', Type=..., ParticipantID=..., IsActive=..., DeletedAt=...}"
     */
    @Override
    public String toString() {
        return "Category{" +
                "categoryID=" + getCategoryID() +
                ", categoryName='" + getCategoryName() + '\'' +
                ", categoryType=" + getCategoryType() +
                ", participantID=" + (getParticipant() != null ? getParticipant().getParticipantID() : "null") +
                ", isActive=" + getIsActive() +
                ", deletedAt=" + getDeletedAt() +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * </p>
     * <p>
     * The comparison for {@code Category} objects is based primarily on their
     * unique {@code categoryID}. This ensures that two category objects
     * representing the same database record are considered equal.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections. It correctly handles
     * {@code null} for `categoryID` in unpersisted entities.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        // Equality is based on the primary key (categoryID), safely handling null Integer
        return Objects.equals(getCategoryID(), category.getCategoryID());
    }
    /**
     * <p>
     * Returns a hash code value for the object.
     * </p>
     * <p>
     * This method is supported for the benefit of hash tables such as those
     * provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * The hash code is generated solely based on the unique {@code categoryID}.
     * </p>
     * <p>
     * This ensures that objects considered equal by {@link #equals(Object)} will
     * have the same hash code, fulfilling the contract between {@code equals} and
     * {@code hashCode}, which is essential for correct behavior in hash-based collections.
     * It correctly handles {@code null} for `categoryID` in unpersisted entities.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(getCategoryID());
    }
}