package com.avaruusstudios.vmdb.model;

import java.util.Objects;

/**
 * <p>
 * Represents a financial category used for classifying transactions within the Vanpool Management System.
 * Categories help organize income, expenses, and credits.
 * </p>
 *
 * <p>
 * Each category has a unique identifier, a name, a type (Income, Expense, Credit),
 * an optional link to a specific {@link Participant}, and a descriptive text.
 * This class directly maps to the `Categories` table in the SQLite database.
 * </p>
 *
 * @see CategoryType
 * @see Participant
 * @see Transaction
 */
public class Category {
    /**
     * Unique identifier for the category. This serves as the primary key
     * in the database for category records ({@code CategoryID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int categoryID;
    /**
     * The {@link Participant} object this category is tied to, if any.
     * Corresponds to {@code ParticipantID_FK INTEGER} in the database, which is nullable.
     * A null value indicates a general category not specific to one participant.
     */
    private Participant participant;
    /**
     * The type of the category, restricting values to {@link CategoryType#INCOME},
     * {@link CategoryType#EXPENSE}, or {@link CategoryType#CREDIT}.
     * Corresponds to {@code CategoryType TEXT NOT NULL} in the database.
     */
    private CategoryType categoryType;
    /**
     * The name of the category (e.g., "Fuel", "Rent", "Participant Payment").
     * Corresponds to {@code CategoryName TEXT NOT NULL} in the database.
     */
    private String categoryName;
    /**
     * A longer description providing more detail about the category's purpose.
     * Corresponds to {@code Description TEXT} in the database, which is nullable.
     */
    private String description;

    /**
     * Default constructor for creating an empty {@code Category} object.
     * Initializes fields to their default or null values.
     */
    public Category() {
    }
    /**
     * Full constructor to initialize all fields of a {@code Category} instance.
     * This constructor allows for the comprehensive creation of a category record,
     * aligning with the database schema and object relationships.
     *
     * @param categoryID   The unique integer ID for the category, typically auto-generated by the database.
     * @param participant  The {@link Participant} object this category is tied to, or {@code null} if it's a general category.
     * @param categoryType The {@link CategoryType} (Income, Expense, Credit). Must not be {@code null}.
     * @param categoryName The name of the category. Must not be {@code null}.
     * @param description  An optional longer description of the category. Can be {@code null}.
     */
    public Category(int categoryID, Participant participant, CategoryType categoryType, String categoryName, String description) {
        this.categoryID = categoryID;
        this.participant = participant;
        this.categoryType = categoryType;
        this.categoryName = categoryName;
        this.description = description;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for this category.
     * Corresponds to the {@code CategoryID} column in the database.
     *
     * @return The integer primary key used to identify this category record.
     */
    public int getCategoryID() {
        return categoryID;
    }
    /**
     * Sets the unique identifier for this category.
     *
     * @param categoryID The unique integer ID for the category.
     */
    public void setCategoryID(int categoryID) {
        this.categoryID = categoryID;
    }
    /**
     * Retrieves the {@link Participant} object this category is tied to.
     * Corresponds to the {@code ParticipantID_FK} column in the database.
     *
     * @return The associated {@link Participant} object, or {@code null} if the category is not participant-specific.
     */
    public Participant getParticipant() {
        return participant;
    }
    /**
     * Sets the {@link Participant} object this category is tied to.
     *
     * @param participant The {@link Participant} object to set, or {@code null}.
     */
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    /**
     * Retrieves the type of this category.
     * Corresponds to the {@code CategoryType} column in the database.
     *
     * @return The {@link CategoryType} enum constant (Income, Expense, or Credit).
     */
    public CategoryType getCategoryType() {
        return categoryType;
    }
    /**
     * Sets the type of this category.
     *
     * @param categoryType The {@link CategoryType} to set. Must not be {@code null} as per schema.
     */
    public void setCategoryType(CategoryType categoryType) {
        this.categoryType = categoryType;
    }
    /**
     * Retrieves the name of this category.
     * Corresponds to the {@code CategoryName} column in the database.
     *
     * @return The name of the category.
     */
    public String getCategoryName() {
        return categoryName;
    }
    /**
     * Sets the name of this category.
     *
     * @param categoryName The name of the category to set. Must not be {@code null} as per schema.
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    /**
     * Retrieves the description of this category.
     * Corresponds to the {@code Description} column in the database.
     *
     * @return A string containing the description, or {@code null} if no description is present.
     */
    public String getDescription() {
        return description;
    }
    /**
     * Sets the description for this category.
     *
     * @param description The string containing the description to set. Can be {@code null}.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code Category} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the category's key attributes.
     * </p>
     * <p>
     * The format includes the category ID, name, type, and associated participant ID (if any).
     * </p>
     *
     * @return A string in the format:
     * "Category{ID=..., Name='...', Type=..., ParticipantID=...}"
     */
    @Override
    public String toString() {
        return "Category{" +
                "categoryID=" + categoryID +
                ", categoryName='" + categoryName + '\'' +
                ", categoryType=" + categoryType +
                ", participantID=" + (participant != null ? participant.getParticipantID() : "null") +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is based primarily on the unique {@code categoryID}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        // Equality is based on the primary key (categoryID)
        return categoryID == category.categoryID;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code categoryID}, ensuring that
     * objects considered equal by {@link #equals(Object)} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(categoryID);
    }
}