package com.avaruusstudios.vmdb.model;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * <p>
 * Represents a log entry capturing significant system events within the Vanpool Management System.
 * These logs are crucial for auditing, debugging, and understanding system activity.
 * </p>
 *
 * <p>
 * Each log entry records who performed an action (via a {@link User} reference),
 * when it occurred, the type of event (e.g., CREATE, READ, UPDATE, DELETE, ERROR),
 * the affected database table and optionally a specific record ID within that table.
 * It also captures error codes and a general description of the event.
 * </p>
 *
 * @see User
 * @see EventType
 */
public class EventLog {
    /**
     * Unique identifier for the event log entry. This serves as the primary key
     * in the database ({@code EventID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int eventID;
    /**
     * The {@link User} who initiated or is associated with this event.
     * This field is mandatory and cannot be null.
     * Corresponds to {@code UserID_FK INTEGER NOT NULL} in the database.
     */
    private User user;
    /**
     * The date and time when the event occurred.
     * Corresponds to {@code EventDate TEXT NOT NULL} in the database.
     */
    private LocalDateTime eventDate;
    /**
     * The {@link EventType} indicating the nature of the event (e.g., CREATE, READ, UPDATE, DELETE, ERROR).
     * This field is mandatory and cannot be null.
     * Corresponds to {@code EventType TEXT NOT NULL} in the database.
     */
    private EventType eventType;
    /**
     * The name of the database table where the event occurred or which was affected.
     * This field is mandatory and cannot be null.
     * Corresponds to {@code TableName TEXT NOT NULL} in the database.
     */
    private String tableName;
    /**
     * The ID of the specific record within the {@code tableName} that was affected by the event.
     * This field is optional and can be null if the event doesn't pertain to a single record (e.g., an error during a batch operation).
     * Corresponds to {@code RecordID INTEGER} in the database.
     */
    private Integer recordID;
    /**
     * An optional error code associated with the event, particularly relevant for `ERROR` type events.
     * Can be null if no error code applies.
     * Corresponds to {@code ErrorCode INTEGER} in the database.
     */
    private Integer errorCode;
    /**
     * A detailed description of the event, providing more context or specifics.
     * This field is optional and can be null.
     * Corresponds to {@code Description TEXT} in the database.
     */
    private String description;

    /**
     * Default constructor for creating an empty {@code EventLog} object.
     * Initializes fields to their default or null values.
     */
    public EventLog() {
    }
    /**
     * Full constructor to initialize all fields of an {@code EventLog} instance.
     * This constructor allows for the comprehensive creation of an event log record,
     * aligning with the database schema and established object relationships.
     *
     * @param eventID    The unique integer ID for the event, typically auto-generated by the database.
     * @param user       The {@link User} associated with this event. Must not be {@code null}.
     * @param eventDate  The {@link LocalDateTime} when the event occurred. Must not be {@code null}.
     * @param eventType  The {@link EventType} of the event. Must not be {@code null}.
     * @param tableName  The name of the affected database table. Must not be {@code null}.
     * @param recordID   The ID of the affected record, or {@code null} if not applicable.
     * @param errorCode  An optional error code, or {@code null}.
     * @param description A detailed description of the event. Can be {@code null}.
     */
    public EventLog(int eventID, User user, LocalDateTime eventDate, EventType eventType,
                    String tableName, Integer recordID, Integer errorCode, String description) {
        this.eventID = eventID;
        this.user = user;
        this.eventDate = eventDate;
        this.eventType = eventType;
        this.tableName = tableName;
        this.recordID = recordID;
        this.errorCode = errorCode;
        this.description = description;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for this event log entry.
     * Corresponds to the {@code EventID} column in the database.
     *
     * @return The integer primary key used to identify this event log record.
     */
    public int getEventID() {
        return eventID;
    }
    /**
     * Sets the unique identifier for this event log entry.
     *
     * @param eventID The event ID to set.
     */
    public void setEventID(int eventID) {
        this.eventID = eventID;
    }
    /**
     * Retrieves the {@link User} who initiated or is associated with this event.
     * Corresponds to the {@code UserID_FK} column in the database.
     *
     * @return The associated {@link User} object. Will not be {@code null} as per schema.
     */
    public User getUser() {
        return user;
    }
    /**
     * Sets the {@link User} who initiated or is associated with this event.
     *
     * @param user The {@link User} object to set. Must not be {@code null} as per schema.
     */
    public void setUser(User user) {
        this.user = user;
    }
    /**
     * Retrieves the date and time when this event occurred.
     * Corresponds to the {@code EventDate} column in the database.
     *
     * @return The event date and time.
     */
    public LocalDateTime getEventDate() {
        return eventDate;
    }
    /**
     * Sets the date and time when this event occurred.
     *
     * @param eventDate The event date and time to set. Must not be {@code null}.
     */
    public void setEventDate(LocalDateTime eventDate) {
        this.eventDate = eventDate;
    }
    /**
     * Retrieves the {@link EventType} of this event.
     * Corresponds to the {@code EventType} column in the database.
     *
     * @return The {@link EventType} enum constant (CREATE, READ, UPDATE, DELETE, or ERROR).
     */
    public EventType getEventType() {
        return eventType;
    }
    /**
     * Sets the {@link EventType} of this event.
     *
     * @param eventType The {@link EventType} to set. Must not be {@code null} as per schema.
     */
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }
    /**
     * Retrieves the name of the database table affected by this event.
     * Corresponds to the {@code TableName} column in the database.
     *
     * @return The name of the affected table.
     */
    public String getTableName() {
        return tableName;
    }
    /**
     * Sets the name of the database table affected by this event.
     *
     * @param tableName The table name to set. Must not be {@code null}.
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    /**
     * Retrieves the ID of the specific record within the affected table.
     * Corresponds to the {@code RecordID} column in the database.
     *
     * @return The record ID, or {@code null} if not applicable.
     */
    public Integer getRecordID() {
        return recordID;
    }
    /**
     * Sets the ID of the specific record within the affected table.
     *
     * @param recordID The record ID to set. Can be {@code null}.
     */
    public void setRecordID(Integer recordID) {
        this.recordID = recordID;
    }
    /**
     * Retrieves an optional error code associated with the event.
     * Corresponds to the {@code ErrorCode} column in the database.
     *
     * @return The error code, or {@code null} if no error code applies.
     */
    public Integer getErrorCode() {
        return errorCode;
    }
    /**
     * Sets an optional error code associated with the event.
     *
     * @param errorCode The error code to set. Can be {@code null}.
     */
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }
    /**
     * Retrieves the detailed description of the event.
     * Corresponds to the {@code Description} column in the database.
     *
     * @return The event description, or {@code null} if no description is present.
     */
    public String getDescription() {
        return description;
    }
    /**
     * Sets a detailed description for this event.
     *
     * @param description The description to set. Can be {@code null}.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code EventLog} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the event's key attributes.
     * </p>
     * <p>
     * The format includes the event ID, associated user's ID, event date,
     * type, affected table, and optionally record ID and error code.
     * </p>
     *
     * @return A string in the format:
     * "EventLog{ID=..., UserID=..., Date=..., Type=..., Table='...', RecordID=..., ErrorCode=...}"
     */
    @Override
    public String toString() {
        return "EventLog{" +
                "eventID=" + eventID +
                ", userID=" + (user != null ? user.getUserId() : "null") +
                ", eventDate=" + eventDate +
                ", eventType=" + eventType +
                ", tableName='" + tableName + '\'' +
                ", recordID=" + recordID +
                ", errorCode=" + errorCode +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is based primarily on the unique {@code eventID}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EventLog eventLog = (EventLog) o;
        // Equality is based on the primary key (eventID)
        return eventID == eventLog.eventID;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code eventID}, ensuring that
     * objects considered equal by {@code equals} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(eventID);
    }
}