package com.avaruusstudios.vmdb.model;

import java.util.Objects;

/**
 * <p>
 * Represents an individual line item within an {@link Invoice} in the Vanpool Management System.
 * Each invoice item details a specific charge or payment associated with a particular participant
 * for a given invoice.
 * </p>
 *
 * <p>
 * This class encapsulates the unique identifier for the item, references to its parent invoice
 * and the involved participant, the composite {@link Amount} representing benefit and personal payments,
 * a flag indicating the official payment status, and any relevant notes.
 * The payment status (`isPaid`) is determined by external transaction matching logic,
 * rather than a stored `paidAmount` field.
 * </p>
 *
 * @see Invoice
 * @see Participant
 * @see Amount
 */
public class InvoiceItem {
    /**
     * Unique identifier for the invoice item. This serves as the primary key
     * in the database for invoice item records ({@code InvoiceItemID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int invoiceItemID;
    /**
     * The {@link Invoice} object to which this invoice item belongs.
     * This represents the foreign key relationship to the {@code Invoices} table
     * (corresponds to {@code InvoiceID_FK INTEGER NOT NULL} in the database).
     */
    private Invoice invoice;
    /**
     * The {@link Participant} object for whom this invoice item is generated.
     * This represents the foreign key relationship to the {@code Participants} table
     * (corresponds to {@code ParticipantID_FK INTEGER NOT NULL} in the database).
     */
    private Participant participant;
    /**
     * A composite {@link Amount} object encapsulating the required benefit payment
     * and personal payment for this invoice item.
     * Corresponds to {@code BenefitPayment REAL NOT NULL} and {@code PersonalPayment REAL NOT NULL} in the database.
     */
    private Amount amountDue;
    /**
     * A boolean flag indicating whether the participant has officially paid for this invoice item.
     * This status is typically updated by external business logic that matches transactions
     * to the required payments for this item.
     * Corresponds to {@code IsPaid INTEGER NOT NULL DEFAULT 0} in the database (where 1=true, 0=false).
     */
    private boolean isPaid;
    /**
     * Optional notes or contextual information about the invoice item.
     * Corresponds to {@code Notes TEXT} in the database.
     */
    private String notes;

    /**
     * Default constructor for creating an empty {@code InvoiceItem} object.
     * This constructor initializes the {@code amountDue} field with a default {@link Amount} object.
     */
    public InvoiceItem() {
        this.amountDue = new Amount();
    }
    /**
     * Full constructor to initialize all fields of an {@code InvoiceItem} instance.
     * This constructor allows for the comprehensive creation of an invoice item record,
     * aligning with the database schema and established object relationships.
     * The `isPaid` status is explicitly set during construction.
     *
     * @param invoiceItemID     The unique integer ID for the invoice item, typically auto-generated by the database.
     * @param invoice           The {@link Invoice} object to which this item belongs. Must not be {@code null}.
     * @param participant       The {@link Participant} object for whom this item is generated. Must not be {@code null}.
     * @param amountDue         The {@link Amount} object representing the required benefit and personal payments. Must not be {@code null}.
     * @param isPaid            A boolean indicating if the full amount due for this item has been officially paid.
     * @param notes             Any optional notes or additional information about the invoice item. Can be {@code null}.
     */
    public InvoiceItem(int invoiceItemID, Invoice invoice, Participant participant,
                       Amount amountDue, boolean isPaid, String notes) {
        this.invoiceItemID = invoiceItemID;
        this.invoice = invoice;
        this.participant = participant;
        this.amountDue = amountDue;
        this.isPaid = isPaid;
        this.notes = notes;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for this invoice item.
     * Corresponds to the {@code InvoiceItemID} column in the database.
     *
     * @return The integer primary key used to identify this invoice item record.
     */
    public int getInvoiceItemID() {
        return invoiceItemID;
    }
    /**
     * Sets the unique identifier for this invoice item.
     *
     * @param invoiceItemID The unique integer ID for the invoice item.
     */
    public void setInvoiceItemID(int invoiceItemID) {
        this.invoiceItemID = invoiceItemID;
    }
    /**
     * Retrieves the {@link Invoice} object to which this invoice item belongs.
     * Corresponds to the {@code InvoiceID_FK} column in the database.
     *
     * @return The associated {@link Invoice} object. Will not be {@code null} as per schema.
     */
    public Invoice getInvoice() {
        return invoice;
    }
    /**
     * Sets the {@link Invoice} object to which this invoice item belongs.
     *
     * @param invoice The {@link Invoice} object to set. Must not be {@code null} as per schema.
     */
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    /**
     * Retrieves the {@link Participant} object for whom this invoice item is generated.
     * Corresponds to the {@code ParticipantID_FK} column in the database.
     *
     * @return The associated {@link Participant} object. Will not be {@code null} as per schema.
     */
    public Participant getParticipant() {
        return participant;
    }
    /**
     * Sets the {@link Participant} object for whom this invoice item is generated.
     *
     * @param participant The {@link Participant} object to set. Must not be {@code null} as per schema.
     */
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    /**
     * Retrieves the {@link Amount} object representing the required benefit and personal payments.
     * Corresponds to {@code BenefitPayment} and {@code PersonalPayment} columns in the database.
     *
     * @return The {@link Amount} object containing the due payment components.
     */
    public Amount getAmountDue() {
        return amountDue;
    }
    /**
     * Sets the {@link Amount} object representing the required benefit and personal payments.
     *
     * @param amountDue The {@link Amount} object to set. Must not be {@code null}.
     */
    public void setAmountDue(Amount amountDue) {
        this.amountDue = amountDue;
    }
    /**
     * Checks if the participant has officially paid for this invoice item based on the stored flag.
     * Corresponds to the {@code IsPaid} column in the database.
     *
     * @return {@code true} if the item is marked as paid; {@code false} otherwise.
     */
    public boolean getIsPaid() {
        return isPaid;
    }
    /**
     * Sets whether the participant has officially paid for this invoice item.
     * Corresponds to the {@code IsPaid} column in the database.
     *
     * @param paid {@code true} to mark as paid; {@code false} to mark as unpaid.
     */
    public void setIsPaid(boolean paid) {
        isPaid = paid;
    }
    /**
     * Retrieves any optional notes or contextual information about the invoice item.
     * Corresponds to the {@code Notes} column in the database.
     *
     * @return A string containing the notes, or {@code null} if no notes are present.
     */
    public String getNotes() {
        return notes;
    }
    /**
     * Sets additional notes or contextual information for this invoice item.
     *
     * @param notes The string containing notes to set. Can be {@code null}.
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    // ---------------------
    // Computed Properties
    // ---------------------

    /**
     * Calculates the total amount that is currently due for this invoice item,
     * which is the sum of the benefit payment and personal payment components
     * encapsulated within the {@link Amount} object.
     *
     * @return The combined total amount due for this invoice item, or 0.0 if {@code amountDue} is null.
     */
    public double getTotalDue() {
        return amountDue != null ? amountDue.getTotal() : 0.0;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code InvoiceItem} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the invoice item's key attributes.
     * </p>
     * <p>
     * The format includes the invoice item ID, the parent invoice's ID,
     * the associated participant's ID, the total amount due, and the official paid status.
     * </p>
     *
     * @return A string in the format:
     * "InvoiceItem{ID=..., InvoiceID=..., ParticipantID=..., AmountDue=..., IsPaid=...}"
     */
    @Override
    public String toString() {
        return "InvoiceItem{" +
                "invoiceItemID=" + invoiceItemID +
                ", invoiceID=" + (invoice != null ? invoice.getInvoiceID() : "null") +
                ", participantID=" + (participant != null ? participant.getParticipantID() : "null") +
                ", amountDue=" + (amountDue != null ? amountDue.toString() : "null") +
                ", isPaid=" + isPaid +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is based primarily on the unique {@code invoiceItemID}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        InvoiceItem that = (InvoiceItem) o;
        // Equality is based on the primary key (invoiceItemID)
        return invoiceItemID == that.invoiceItemID;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code invoiceItemID}, ensuring that
     * objects considered equal by {@link #equals(Object)} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(invoiceItemID);
    }
}