package com.avaruusstudios.vmdb.model;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Objects;

/**
 * <p>
 * Represents a financial invoice generated within the Vanpool Management System.
 * Each invoice details billing information for a specific period and is associated with a particular vehicle.
 * </p>
 *
 * <p>
 * A singular invoice contains metadata such as its unique identifier, the date it was prepared,
 * its due date, the billing period it covers, the associated {@link Vehicle} object,
 * and any relevant notes. This object structure directly reflects the schema used for the
 * {@code Invoices} table in the SQLite database to track billing records, where
 * {@code VehicleID_FK} is now represented by an embedded {@code Vehicle} object.
 * </p>
 *
 * @see Vehicle
 * @see InvoiceItem
 * @see Transaction
 */
public class Invoice {
    /**
     * Unique identifier for the invoice. This serves as the primary key
     * in the database for invoice records ({@code InvoiceID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int invoiceID;

    /**
     * The {@link LocalDate} when the invoice was officially prepared or generated
     * (corresponds to {@code InvoiceDate TEXT NOT NULL} in the database).
     */
    private LocalDate invoiceDate;

    /**
     * The {@link LocalDate} by which the invoice payment is expected
     * (corresponds to {@code DueDate TEXT NOT NULL} in the database).
     */
    private LocalDate dueDate;

    /**
     * The billing period of the invoice, represented as a {@link YearMonth} object.
     * This indicates the month and year for which the charges apply (e.g., "JUN-2025")
     * and corresponds to {@code PeriodLabel TEXT NOT NULL} in the database.
     */
    private YearMonth periodLabel;

    /**
     * The {@link Vehicle} object with which this invoice is associated.
     * This represents the foreign key relationship to the {@code Vehicles} table
     * (corresponds to {@code VehicleID_FK INTEGER NOT NULL} in the database).
     */
    private Vehicle vehicle;

    /**
     * Optional notes or comments regarding the invoice.
     * This field can contain administrative remarks, specific payment instructions,
     * or a summary of the invoice's purpose (corresponds to {@code Notes TEXT} in the database).
     */
    private String notes;

    /**
     * Default constructor for creating an empty {@code Invoice} object.
     * This constructor is primarily used by frameworks that instantiate objects
     * via reflection (e.g., ORMs, JSON deserializers) before populating their fields.
     */
    public Invoice() {}

    /**
     * Full constructor to initialize all fields of an {@code Invoice} instance.
     * This constructor allows for the comprehensive creation of an invoice record
     * with all necessary details upon instantiation, reflecting the database schema
     * and the object-oriented relationship with a {@link Vehicle}.
     *
     * @param invoiceID     The unique integer ID for the invoice, typically auto-generated by the database.
     * @param invoiceDate   The {@link LocalDate} when the invoice was generated (e.g., {@code 2024-05-15}).
     * @param dueDate       The {@link LocalDate} by which the invoice is to be paid (e.g., {@code 2024-05-31}).
     * @param periodLabel   The {@link YearMonth} representing the billing period of the invoice (e.g., {@code YearMonth.of(2024, 5)} for May 2024).
     * @param vehicle       The {@link Vehicle} object associated with this invoice. Must not be {@code null} as per schema's foreign key constraint.
     * @param notes         Any optional notes or additional information about the invoice. Can be {@code null}.
     */
    public Invoice(int invoiceID, LocalDate invoiceDate, LocalDate dueDate, YearMonth periodLabel, Vehicle vehicle, String notes) {
        this.invoiceID = invoiceID;
        this.invoiceDate = invoiceDate;
        this.dueDate = dueDate;
        this.periodLabel = periodLabel;
        this.vehicle = vehicle;
        this.notes = notes;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for this invoice.
     * Corresponds to the {@code InvoiceID} column in the database.
     *
     * @return The integer primary key used to identify this invoice record.
     */
    public int getInvoiceID() {
        return invoiceID;
    }
    /**
     * Sets the unique identifier for this invoice.
     * This method is typically used when populating an invoice object from a persisted source
     * or before inserting a new record where the ID is pre-determined (though often auto-generated).
     *
     * @param invoiceID The unique integer ID for the invoice.
     */
    public void setInvoiceID(int invoiceID) {
        this.invoiceID = invoiceID;
    }
    /**
     * Retrieves the {@link LocalDate} when the invoice was generated.
     * Corresponds to the {@code InvoiceDate} column in the database.
     *
     * @return The {@link LocalDate} representing the invoice generation date.
     */
    public LocalDate getInvoiceDate() {
        return invoiceDate;
    }
    /**
     * Sets the {@link LocalDate} when the invoice was generated.
     *
     * @param invoiceDate The {@link LocalDate} to set as the invoice generation date. Must not be {@code null} as per schema.
     */
    public void setInvoiceDate(LocalDate invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    /**
     * Retrieves the {@link LocalDate} representing the due date of the invoice.
     * Corresponds to the {@code DueDate} column in the database.
     *
     * @return The {@link LocalDate} by which the invoice payment is expected.
     */
    public LocalDate getDueDate() {
        return dueDate;
    }
    /**
     * Sets the {@link LocalDate} for the invoice's due date.
     * This indicates the date by which participants are required to pay their share.
     * Corresponds to the {@code DueDate} column in the database.
     *
     * @param dueDate The {@link LocalDate} to set as the invoice due date. Must not be {@code null} as per schema.
     */
    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }
    /**
     * Retrieves the billing period of the invoice as a {@link YearMonth} object.
     * Corresponds to the {@code PeriodLabel} column in the database.
     *
     * @return The {@link YearMonth} representing the billing period (e.g., June 2025).
     */
    public YearMonth getPeriodLabel() {
        return periodLabel;
    }
    /**
     * Sets the billing period of the invoice.
     * This {@link YearMonth} indicates the specific month and year for which the invoice's charges apply.
     * Corresponds to the {@code PeriodLabel} column in the database.
     *
     * @param periodLabel The {@link YearMonth} to set as the billing period. Must not be {@code null} as per schema.
     */
    public void setPeriodLabel(YearMonth periodLabel) {
        this.periodLabel = periodLabel;
    }
    /**
     * Retrieves the {@link Vehicle} object associated with this invoice.
     * This represents the foreign key relationship to the {@code Vehicles} table.
     *
     * @return The associated {@link Vehicle} object, which will not be {@code null} if loaded correctly from the database.
     */
    public Vehicle getVehicle() {
        return vehicle;
    }
    /**
     * Sets the {@link Vehicle} object associated with this invoice.
     * This links the invoice to a specific vehicle.
     *
     * @param vehicle The {@link Vehicle} object to associate with this invoice. Must not be {@code null} as per schema.
     */
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    /**
     * Retrieves any optional notes or remarks associated with this invoice.
     * This might include details about special charges, payment instructions, or administrative comments.
     * Corresponds to the {@code Notes} column in the database.
     *
     * @return A string containing the notes, or {@code null} if no notes are present.
     */
    public String getNotes() {
        return notes;
    }
    /**
     * Sets additional notes or internal comments for this invoice.
     * Corresponds to the {@code Notes} column in the database.
     *
     * @param notes The string containing notes to set. Can be {@code null}.
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a formatted string representation of the invoice's billing period.
     * This method uses a specific date format ("MMM-yyyy") to display the period
     * in a user-friendly manner (e.g., "Jun-2025").
     * </p>
     * <p>
     * If the {@code periodLabel} is {@code null}, this method will return {@code null}.
     * </p>
     *
     * @return A formatted string representing the invoice's billing period, or {@code null} if {@code periodLabel} is {@code null}.
     */
    public String getFormattedPeriodLabel() {
        if (periodLabel == null) {
            return null;
        }
        return periodLabel.format(DateTimeFormatter.ofPattern("MMM-yyyy"));
    }
    /**
     * <p>
     * Returns a string representation of the {@code Invoice} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the invoice's key attributes.
     * </p>
     * <p>
     * The format includes the invoice ID, invoice date, due date,
     * formatted billing period, and the associated vehicle's ID (if available).
     * </p>
     *
     * @return A string in the format:
     * "Invoice{invoiceID=..., invoiceDate=..., dueDate=..., periodLabel=..., vehicleID=...}"
     */
    @Override
    public String toString() {
        return "Invoice{" +
                "invoiceID=" + invoiceID +
                ", invoiceDate=" + invoiceDate +
                ", dueDate=" + dueDate +
                ", periodLabel=" + getFormattedPeriodLabel() +
                ", vehicleID=" + (vehicle != null ? vehicle.getVehicleID() : "null") + // Safely get vehicle ID
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is based primarily on the unique {@code invoiceID}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Invoice invoice = (Invoice) o;
        // Equality is based on the primary key (invoiceID)
        return invoiceID == invoice.invoiceID;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code invoiceID}, ensuring that
     * objects considered equal by {@link #equals(Object)} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(invoiceID);
    }
}