package com.avaruusstudios.vmdb.model;

import java.time.LocalDate;
import java.util.Objects;

/**
 * <p>
 * Represents a single financial transaction within the Vanpool Management System.
 * Transactions record financial movements, such as expenses (fuel, maintenance),
 * income (participant payments), or credits.
 * </p>
 *
 * <p>
 * Each transaction is uniquely identified and includes details about the date,
 * the associated vehicle, the category it falls under (linking to participants if an income category),
 * the monetary amount, payment method, and an optional link to an invoice.
 * This class directly maps to the `Transactions` table in the SQLite database,
 * reflecting the updated schema where `ParticipantID_FK` is no longer directly present in this table.
 * </p>
 *
 * @see Vehicle
 * @see Category
 * @see Invoice
 */
public class Transaction {
    /**
     * Unique identifier for the transaction. This serves as the primary key
     * in the database for transaction records ({@code TransactionID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int transactionID;
    /**
     * The date on which the transaction occurred.
     * Corresponds to {@code TransactionDate TEXT NOT NULL} in the database.
     */
    private LocalDate transactionDate;
    /**
     * The {@link Vehicle} object associated with this transaction.
     * Corresponds to {@code VehicleID_FK INTEGER NOT NULL} in the database.
     */
    private Vehicle vehicle;
    /**
     * The {@link Category} object that classifies this transaction.
     * This link is crucial for determining if the transaction is income, expense, or credit,
     * and indirectly linking to a participant if it's an income category.
     * Corresponds to {@code CategoryID_FK INTEGER NOT NULL} in the database.
     */
    private Category category;
    /**
     * The monetary amount of the transaction.
     * Corresponds to {@code Amount REAL NOT NULL} in the database.
     */
    private double amount;
    /**
     * The method of payment used for this transaction (e.g., "Cash", "Credit Card", "Bank Transfer").
     * Corresponds to {@code PaymentMethod TEXT} in the database, which is nullable.
     */
    private String paymentMethod;
    /**
     * The {@link Invoice} object this transaction is associated with, if any.
     * This field is nullable (corresponds to {@code InvoiceID_FK INTEGER} in the database),
     * meaning not all transactions are linked to an invoice.
     */
    private Invoice invoice;
    /**
     * Optional notes or contextual information about the transaction.
     * Corresponds to {@code Notes TEXT} in the database, which is nullable.
     */
    private String notes;

    /**
     * Default constructor for creating an empty {@code Transaction} object.
     * Initializes fields to their default or null values.
     */
    public Transaction() {
    }
    /**
     * Full constructor to initialize all fields of a {@code Transaction} instance.
     * This constructor allows for the comprehensive creation of a transaction record,
     * aligning with the database schema and established object relationships.
     *
     * @param transactionID   The unique integer ID for the transaction, typically auto-generated by the database.
     * @param transactionDate The date of the transaction. Must not be {@code null}.
     * @param vehicle         The {@link Vehicle} object associated with this transaction. Must not be {@code null}.
     * @param category        The {@link Category} object that classifies this transaction. Must not be {@code null}.
     * @param amount          The monetary amount of the transaction.
     * @param paymentMethod   The method of payment, e.g., "Cash", "Credit Card". Can be {@code null}.
     * @param invoice         The {@link Invoice} object linked to this transaction, or {@code null} if none.
     * @param notes           Any optional notes or additional information about the transaction. Can be {@code null}.
     */
    public Transaction(int transactionID, LocalDate transactionDate, Vehicle vehicle, Category category,
                       double amount, String paymentMethod, Invoice invoice, String notes) {
        this.transactionID = transactionID;
        this.transactionDate = transactionDate;
        this.vehicle = vehicle;
        this.category = category;
        this.amount = amount;
        this.paymentMethod = paymentMethod;
        this.invoice = invoice;
        this.notes = notes;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for this transaction.
     * Corresponds to the {@code TransactionID} column in the database.
     *
     * @return The integer primary key used to identify this transaction record.
     */
    public int getTransactionID() {
        return transactionID;
    }
    /**
     * Sets the unique identifier for this transaction.
     *
     * @param transactionID The unique integer ID for the transaction.
     */
    public void setTransactionID(int transactionID) {
        this.transactionID = transactionID;
    }
    /**
     * Retrieves the date on which this transaction occurred.
     * Corresponds to the {@code TransactionDate} column in the database.
     *
     * @return The transaction date.
     */
    public LocalDate getTransactionDate() {
        return transactionDate;
    }
    /**
     * Sets the date on which this transaction occurred.
     *
     * @param transactionDate The transaction date to set. Must not be {@code null}.
     */
    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }
    /**
     * Retrieves the {@link Vehicle} object associated with this transaction.
     * Corresponds to the {@code VehicleID_FK} column in the database.
     *
     * @return The associated {@link Vehicle} object. Will not be {@code null} as per schema.
     */
    public Vehicle getVehicle() {
        return vehicle;
    }
    /**
     * Sets the {@link Vehicle} object associated with this transaction.
     *
     * @param vehicle The {@link Vehicle} object to set. Must not be {@code null} as per schema.
     */
    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
    /**
     * Retrieves the {@link Category} object that classifies this transaction.
     * Corresponds to the {@code CategoryID_FK} column in the database.
     *
     * @return The associated {@link Category} object. Will not be {@code null} as per schema.
     */
    public Category getCategory() {
        return category;
    }
    /**
     * Sets the {@link Category} object that classifies this transaction.
     *
     * @param category The {@link Category} object to set. Must not be {@code null} as per schema.
     */
    public void setCategory(Category category) {
        this.category = category;
    }
    /**
     * Retrieves the monetary amount of this transaction.
     * Corresponds to the {@code Amount} column in the database.
     *
     * @return The transaction amount as a double.
     */
    public double getAmount() {
        return amount;
    }
    /**
     * Sets the monetary amount of this transaction.
     *
     * @param amount The transaction amount to set.
     */
    public void setAmount(double amount) {
        this.amount = amount;
    }
    /**
     * Retrieves the payment method used for this transaction.
     * Corresponds to the {@code PaymentMethod} column in the database.
     *
     * @return A string representing the payment method, or {@code null} if not specified.
     */
    public String getPaymentMethod() {
        return paymentMethod;
    }
    /**
     * Sets the payment method used for this transaction.
     *
     * @param paymentMethod The payment method to set. Can be {@code null}.
     */
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    /**
     * Retrieves the {@link Invoice} object this transaction is associated with.
     * Corresponds to the {@code InvoiceID_FK} column in the database.
     *
     * @return The associated {@link Invoice} object, or {@code null} if no invoice is linked.
     */
    public Invoice getInvoice() {
        return invoice;
    }
    /**
     * Sets the {@link Invoice} object this transaction is associated with.
     *
     * @param invoice The {@link Invoice} object to set. Can be {@code null}.
     */
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    /**
     * Retrieves any optional notes or contextual information about the transaction.
     * Corresponds to the {@code Notes} column in the database.
     *
     * @return A string containing the notes, or {@code null} if no notes are present.
     */
    public String getNotes() {
        return notes;
    }
    /**
     * Sets additional notes or contextual information for this transaction.
     *
     * @param notes The string containing notes to set. Can be {@code null}.
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code Transaction} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the transaction's key attributes.
     * </p>
     * <p>
     * The format includes the transaction ID, date, associated vehicle and category IDs,
     * amount, and invoice ID (if any).
     * </p>
     *
     * @return A string in the format:
     * "Transaction{ID=..., Date=..., VehicleID=..., CategoryID=..., Amount=..., InvoiceID=...}"
     */
    @Override
    public String toString() {
        return "Transaction{" +
                "transactionID=" + transactionID +
                ", transactionDate=" + transactionDate +
                ", vehicleID=" + (vehicle != null ? vehicle.getVehicleID() : "null") +
                ", categoryID=" + (category != null ? category.getCategoryID() : "null") +
                ", amount=" + amount +
                ", invoiceID=" + (invoice != null ? invoice.getInvoiceID() : "null") +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is based primarily on the unique {@code transactionID}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Transaction that = (Transaction) o;
        // Equality is based on the primary key (transactionID)
        return transactionID == that.transactionID;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code transactionID}, ensuring that
     * objects considered equal by {@code equals} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(transactionID);
    }
}