package com.avaruusstudios.vmdb.model;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * <p>
 * Represents a user within the Vanpool Management Database application.
 * This class maps directly to the `Users` table in the SQLite database,
 * storing information about individual users, their authentication details,
 * personal information, roles, and account status.
 * </p>
 *
 * <p>
 * User accounts are identified by a unique ID and a Windows username.
 * Each user has a defined {@link UserRole} and an active status.
 * Creation timestamp is automatically managed by the database.
 * </p>
 *
 * @see UserRole
 * @see EventLog
 */
public class User {
    /**
     * Unique identifier for the user. This serves as the primary key
     * in the database for user records ({@code UserID INTEGER PRIMARY KEY AUTOINCREMENT}).
     */
    private int userId;
    /**
     * The Windows username associated with the user account.
     * This field is unique and cannot be null, serving as an important identifier.
     * Corresponds to {@code WindowsUsername VARCHAR(255) UNIQUE NOT NULL} in the database.
     */
    private String windowsUsername;
    /**
     * The first name of the user.
     * Corresponds to {@code FirstName VARCHAR(255)} in the database, which is nullable.
     */
    private String firstName;
    /**
     * The middle name of the user.
     * Corresponds to {@code MiddleName VARCHAR(255)} in the database, which is nullable.
     */
    private String middleName;
    /**
     * The last name of the user.
     * Corresponds to {@code LastName VARCHAR(255)} in the database, which is nullable.
     */
    private String lastName;
    /**
     * The email address of the user.
     * Corresponds to {@code Email VARCHAR(255)} in the database, which is nullable.
     */
    private String email;
    /**
     * The {@link UserRole} assigned to the user within the application (e.g., ADMIN, TREASURER, USER, COORDINATOR).
     * This field is mandatory and cannot be null.
     * Corresponds to {@code UserRole VARCHAR(50) NOT NULL} in the database.
     */
    private UserRole userRole;
    /**
     * A boolean flag indicating whether the user account is currently active.
     * Corresponds to {@code IsActive INTEGER NOT NULL DEFAULT 1} in the database (where 1=true, 0=false).
     */
    private boolean isActive;
    /**
     * The timestamp indicating when the user account was created.
     * This field is often automatically set by the database using `CURRENT_TIMESTAMP`.
     * Corresponds to {@code DateCreated TEXT DEFAULT CURRENT_TIMESTAMP} in the database.
     */
    private LocalDateTime dateCreated;

    /**
     * Default constructor for creating an empty {@code User} object.
     * Initializes fields to their default or null values.
     */
    public User() {
    }
    /**
     * Full constructor to initialize all fields of a {@code User} instance.
     * This constructor allows for the comprehensive creation of a user record,
     * aligning with the database schema.
     *
     * @param userId          The unique integer ID for the user, typically auto-generated by the database.
     * @param windowsUsername The unique Windows username of the user. Must not be {@code null}.
     * @param firstName       The first name of the user. Can be {@code null}.
     * @param middleName      The middle name of the user. Can be {@code null}.
     * @param lastName        The last name of the user. Can be {@code null}.
     * @param email           The email address of the user. Can be {@code null}.
     * @param userRole        The {@link UserRole} of the user. Must not be {@code null}.
     * @param isActive        A boolean indicating whether the user account is active.
     * @param dateCreated     The {@link LocalDateTime} timestamp indicating when the user account was created. Can be {@code null} if database handles default.
     */
    public User(int userId, String windowsUsername, String firstName, String middleName, String lastName,
                String email, UserRole userRole, boolean isActive, LocalDateTime dateCreated) {
        this.userId = userId;
        this.windowsUsername = windowsUsername;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.email = email;
        this.userRole = userRole;
        this.isActive = isActive;
        this.dateCreated = dateCreated;
    }

    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for the user.
     * Corresponds to the {@code UserID} column in the database.
     *
     * @return The integer primary key used to identify this user record.
     */
    public int getUserId() {
        return userId;
    }
    /**
     * Sets the unique identifier for the user.
     *
     * @param userId The user ID to set.
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }
    /**
     * Retrieves the Windows username of the user.
     * Corresponds to the {@code WindowsUsername} column in the database.
     *
     * @return The Windows username. Will not be {@code null} as per schema.
     */
    public String getWindowsUsername() {
        return windowsUsername;
    }
    /**
     * Sets the Windows username of the user.
     *
     * @param windowsUsername The Windows username to set. Must not be {@code null} as per schema.
     */
    public void setWindowsUsername(String windowsUsername) {
        this.windowsUsername = windowsUsername;
    }
    /**
     * Retrieves the first name of the user.
     * Corresponds to the {@code FirstName} column in the database.
     *
     * @return The first name, or {@code null} if not specified.
     */
    public String getFirstName() {
        return firstName;
    }
    /**
     * Sets the first name of the user.
     *
     * @param firstName The first name to set. Can be {@code null}.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    /**
     * Retrieves the middle name of the user.
     * Corresponds to the {@code MiddleName} column in the database.
     *
     * @return The middle name, or {@code null} if not present.
     */
    public String getMiddleName() {
        return middleName;
    }
    /**
     * Sets the middle name of the user.
     *
     * @param middleName The middle name to set. Can be {@code null}.
     */
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    /**
     * Retrieves the last name of the user.
     * Corresponds to the {@code LastName} column in the database.
     *
     * @return The last name, or {@code null} if not specified.
     */
    public String getLastName() {
        return lastName;
    }
    /**
     * Sets the last name of the user.
     *
     * @param lastName The last name to set. Can be {@code null}.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    /**
     * Retrieves the email address of the user.
     * Corresponds to the {@code Email} column in the database.
     *
     * @return The email address, or {@code null} if not specified.
     */
    public String getEmail() {
        return email;
    }
    /**
     * Sets the email address of the user.
     *
     * @param email The email address to set. Can be {@code null}.
     */
    public void setEmail(String email) {
        this.email = email;
    }
    /**
     * Retrieves the {@link UserRole} of the user within the application.
     * Corresponds to the {@code UserRole} column in the database.
     *
     * @return The {@link UserRole} enum constant. Will not be {@code null} as per schema.
     */
    public UserRole getUserRole() {
        return userRole;
    }
    /**
     * Sets the {@link UserRole} of the user within the application.
     *
     * @param userRole The {@link UserRole} to set. Must not be {@code null} as per schema.
     */
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    /**
     * Checks if the user account is currently active.
     * Corresponds to the {@code IsActive} column in the database.
     *
     * @return {@code true} if the account is active, {@code false} otherwise.
     */
    public boolean isActive() {
        return isActive;
    }
    /**
     * Sets the active status of the user account.
     *
     * @param active {@code true} to activate the account, {@code false} to deactivate.
     */
    public void setActive(boolean active) {
        isActive = active;
    }
    /**
     * Retrieves the timestamp indicating when the user account was created.
     * Corresponds to the {@code DateCreated} column in the database.
     *
     * @return The creation date and time, or {@code null} if not set (e.g., by DB default).
     */
    public LocalDateTime getDateCreated() {
        return dateCreated;
    }
    /**
     * Sets the timestamp indicating when the user account was created.
     *
     * @param dateCreated The creation date and time to set. Can be {@code null}.
     */
    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code User} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the user's key attributes.
     * </p>
     * <p>
     * The format includes the user ID, Windows username, full name, email,
     * user role, and active status.
     * </p>
     *
     * @return A string in the format:
     * "User{ID=..., Username='...', Name='...', Email='...', Role=..., Active=...}"
     */
    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", windowsUsername='" + windowsUsername + '\'' +
                ", firstName='" + firstName + '\'' +
                ", middleName='" + (middleName != null ? middleName : "null") + '\'' + // Handle null middle name
                ", lastName='" + lastName + '\'' +
                ", email='" + (email != null ? email : "null") + '\'' + // Handle null email
                ", userRole=" + userRole +
                ", isActive=" + isActive +
                ", dateCreated=" + (dateCreated != null ? dateCreated : "null") + // Handle null dateCreated
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is primarily based on the unique {@code userId}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        // Equality is based on the primary key (userId)
        return userId == user.userId;
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code userId}, ensuring that
     * objects considered equal by {@code equals} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(userId);
    }
}