package com.avaruusstudios.vmdb.model;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * <p>
 * Represents a user within the Vanpool Management Database application.
 * This class maps directly to the `Users` table in the SQLite database,
 * storing information about individual users, their authentication details,
 * personal information, roles, and account status.
 * </p>
 *
 * <p>
 * User accounts are identified by a unique ID and a Windows username.
 * Each user has a defined {@link Role} and an active status.
 * Creation timestamp is automatically managed by the database.
 * </p>
 *
 * @see Role
 * @see EventLog
 */
public class User {
    /**
     * Unique identifier for the user. This serves as the primary key
     * in the database for user records ({@code UserID INTEGER PRIMARY KEY AUTOINCREMENT}).
     * <p>
     * For a newly created user not yet persisted to the database, this value will be {@code null}.
     * Once assigned by the database, it becomes immutable.
     * </p>
     */
    private final Integer userId; // Changed to final Integer

    /**
     * The Windows username associated with the user account.
     * This field is unique and cannot be null, serving as an important identifier.
     * Corresponds to {@code WindowsUsername VARCHAR(255) UNIQUE NOT NULL} in the database.
     */
    private String windowsUsername;
    /**
     * The first name of the user.
     * Corresponds to {@code FirstName VARCHAR(255)} in the database, which is nullable.
     */
    private String firstName;
    /**
     * The middle name of the user.
     * Corresponds to {@code MiddleName VARCHAR(255)} in the database, which is nullable.
     */
    private String middleName;
    /**
     * The last name of the user.
     * Corresponds to {@code LastName VARCHAR(255)} in the database, which is nullable.
     */
    private String lastName;
    /**
     * The email address of the user.
     * Corresponds to {@code Email VARCHAR(255)} in the database, which is nullable.
     */
    private String email;
    /**
     * The {@link Role} assigned to the user within the application (e.g., ADMIN, TREASURER, USER, COORDINATOR).
     * This field is mandatory and cannot be null.
     * Corresponds to {@code UserRole VARCHAR(50) NOT NULL} in the database.
     */
    private Role role;
    /**
     * A boolean flag indicating whether the user account is currently active.
     * Corresponds to {@code IsActive INTEGER NOT NULL DEFAULT 1} in the database (where 1=true, 0=false).
     */
    private boolean isActive;
    /**
     * The timestamp indicating when the user account was created.
     * This field is often automatically set by the database using `CURRENT_TIMESTAMP`.
     * Corresponds to {@code DateCreated TEXT DEFAULT CURRENT_TIMESTAMP} in the database.
     */
    private LocalDateTime dateCreated;

    /**
     * Default constructor for creating an empty {@code User} object.
     * The {@code userId} is set to {@code null} to explicitly indicate that
     * this user entry has not yet been assigned a unique ID by the database.
     * Initializes other fields to their default or null values.
     */
    public User() {
        this.userId = null; // Explicitly null for unpersisted entity
    }

    /**
     * Full constructor to initialize all fields of a {@code User} instance.
     * This constructor allows for the comprehensive creation of a user record,
     * aligning with the database schema. It is typically used when loading an
     * *existing* user record from the database, where {@code userId} has already been assigned.
     * All mandatory parameters are validated.
     *
     * @param userId          The unique integer ID for the user, typically auto-generated by the database. Must not be {@code null}.
     * @param windowsUsername The unique Windows username of the user. Must not be {@code null}.
     * @param firstName       The first name of the user. Can be {@code null}.
     * @param middleName      The middle name of the user. Can be {@code null}.
     * @param lastName        The last name of the user. Can be {@code null}.
     * @param email           The email address of the user. Can be {@code null}.
     * @param role        The {@link Role} of the user. Must not be {@code null}.
     * @param isActive        A boolean indicating whether the user account is active.
     * @param dateCreated     The {@link LocalDateTime} timestamp indicating when the user account was created. Can be {@code null} if database handles default.
     * @throws NullPointerException if `userId`, `windowsUsername`, or `role` are {@code null}.
     */
    public User(Integer userId, String windowsUsername, String firstName, String middleName, String lastName,
                String email, Role role, boolean isActive, LocalDateTime dateCreated) {
        this.userId = Objects.requireNonNull(userId, "User ID cannot be null for an existing user."); // Null check for ID
        setWindowsUsername(windowsUsername);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setEmail(email);
        setUserRole(role);
        setActive(isActive);
        setDateCreated(dateCreated);
    }

    /**
     * Convenience constructor for creating a new {@code User} object that doesn't yet have a database ID.
     * This constructor is ideal when preparing a new user record for **insertion** into the database.
     * The {@code userId} is omitted as it is typically auto-generated by the database.
     * All mandatory parameters are validated.
     *
     * @param windowsUsername The unique Windows username of the user. Must not be {@code null}.
     * @param firstName       The first name of the user. Can be {@code null}.
     * @param middleName      The middle name of the user. Can be {@code null}.
     * @param lastName        The last name of the user. Can be {@code null}.
     * @param email           The email address of the user. Can be {@code null}.
     * @param role        The {@link Role} of the user. Must not be {@code null}.
     * @param isActive        A boolean indicating whether the user account is active.
     * @param dateCreated     The {@link LocalDateTime} timestamp indicating when the user account was created. Can be {@code null} if database handles default.
     * @throws NullPointerException if `windowsUsername` or `role` are {@code null}.
     */
    public User(String windowsUsername, String firstName, String middleName, String lastName,
                String email, Role role, boolean isActive, LocalDateTime dateCreated) {
        this.userId = null; // New entity, ID will be assigned by DB
        setWindowsUsername(windowsUsername);
        setFirstName(firstName);
        setMiddleName(middleName);
        setLastName(lastName);
        setEmail(email);
        setUserRole(role);
        setActive(isActive);
        setDateCreated(dateCreated);
    }


    // ---------------------
    // Getters and Setters
    // ---------------------

    /**
     * Retrieves the unique identifier for the user.
     * For new, unpersisted entries, this will be {@code null}.
     * Corresponds to the {@code UserID} column in the database.
     *
     * @return The {@link Integer} primary key used to identify this user record, or {@code null} if not yet assigned.
     */
    public Integer getUserId() { // Changed return type to Integer
        return userId;
    }

    // setUserId method removed as userId is now final and set only via constructors

    /**
     * Retrieves the Windows username of the user.
     * Corresponds to the {@code WindowsUsername} column in the database.
     *
     * @return The Windows username. Will not be {@code null} as per schema.
     */
    public String getWindowsUsername() {
        return windowsUsername;
    }
    /**
     * Sets the Windows username of the user.
     *
     * @param windowsUsername The Windows username to set. Must not be {@code null} as per schema.
     * @throws NullPointerException if {@code windowsUsername} is {@code null}.
     */
    public void setWindowsUsername(String windowsUsername) {
        this.windowsUsername = Objects.requireNonNull(windowsUsername, "Windows username cannot be null.").strip(); // Enforce non-null and strip whitespace
    }
    /**
     * Retrieves the first name of the user.
     * Corresponds to the {@code FirstName} column in the database.
     *
     * @return The first name, or {@code null} if not specified.
     */
    public String getFirstName() {
        return firstName;
    }
    /**
     * Sets the first name of the user.
     *
     * @param firstName The first name to set. Can be {@code null}.
     */
    public void setFirstName(String firstName) {
        this.firstName = (firstName != null) ? firstName.strip() : null; // Strip whitespace
    }
    /**
     * Retrieves the middle name of the user.
     * Corresponds to the {@code MiddleName} column in the database.
     *
     * @return The middle name, or {@code null} if not present.
     */
    public String getMiddleName() {
        return middleName;
    }
    /**
     * Sets the middle name of the user.
     *
     * @param middleName The middle name to set. Can be {@code null}.
     */
    public void setMiddleName(String middleName) {
        this.middleName = (middleName != null) ? middleName.strip() : null; // Strip whitespace
    }
    /**
     * Retrieves the last name of the user.
     * Corresponds to the {@code LastName} column in the database.
     *
     * @return The last name, or {@code null} if not specified.
     */
    public String getLastName() {
        return lastName;
    }
    /**
     * Sets the last name of the user.
     *
     * @param lastName The last name to set. Can be {@code null}.
     */
    public void setLastName(String lastName) {
        this.lastName = (lastName != null) ? lastName.strip() : null; // Strip whitespace
    }
    /**
     * Retrieves the email address of the user.
     * Corresponds to the {@code Email} column in the database.
     *
     * @return The email address, or {@code null} if not specified.
     */
    public String getEmail() {
        return email;
    }
    /**
     * Sets the email address of the user.
     *
     * @param email The email address to set. Can be {@code null}.
     */
    public void setEmail(String email) {
        this.email = (email != null) ? email.strip() : null; // Strip whitespace
    }
    /**
     * Retrieves the {@link Role} of the user within the application.
     * Corresponds to the {@code UserRole} column in the database.
     *
     * @return The {@link Role} enum constant. Will not be {@code null} as per schema.
     */
    public Role getUserRole() {
        return role;
    }
    /**
     * Sets the {@link Role} of the user within the application.
     *
     * @param role The {@link Role} to set. Must not be {@code null} as per schema.
     * @throws NullPointerException if {@code role} is {@code null}.
     */
    public void setUserRole(Role role) {
        this.role = Objects.requireNonNull(role, "User role cannot be null."); // Enforce non-null
    }
    /**
     * Checks if the user account is currently active.
     * Corresponds to the {@code IsActive} column in the database.
     *
     * @return {@code true} if the account is active, {@code false} otherwise.
     */
    public boolean isActive() {
        return isActive;
    }
    /**
     * Sets the active status of the user account.
     *
     * @param active {@code true} to activate the account, {@code false} to deactivate.
     */
    public void setActive(boolean active) {
        isActive = active;
    }
    /**
     * Retrieves the timestamp indicating when the user account was created.
     * Corresponds to the {@code DateCreated} column in the database.
     *
     * @return The creation date and time, or {@code null} if not set (e.g., by DB default).
     */
    public LocalDateTime getDateCreated() {
        return dateCreated;
    }
    /**
     * Sets the timestamp indicating when the user account was created.
     *
     * @param dateCreated The creation date and time to set. Can be {@code null}.
     */
    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    // ---------------------
    // Utility Methods
    // ---------------------

    /**
     * <p>
     * Returns a string representation of the {@code User} object.
     * This method is primarily used for debugging and logging, providing
     * a concise summary of the user's key attributes.
     * </p>
     * <p>
     * The format includes the user ID, Windows username, full name, email,
     * user role, and active status.
     * </p>
     *
     * @return A string in the format:
     * "User{ID=..., Username='...', Name='...', Email='...', Role=..., Active=..., DateCreated=...}"
     */
    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", windowsUsername='" + windowsUsername + '\'' +
                ", firstName='" + firstName + '\'' +
                ", middleName='" + (middleName != null ? middleName : "null") + '\'' +
                ", lastName='" + lastName + '\'' +
                ", email='" + (email != null ? email : "null") + '\'' +
                ", role=" + role + // Changed from userRole to role to match field name
                ", isActive=" + isActive +
                ", dateCreated=" + (dateCreated != null ? dateCreated : "null") +
                '}';
    }
    /**
     * <p>
     * Indicates whether some other object is "equal to" this one.
     * The comparison is primarily based on the unique {@code userId}.
     * </p>
     * <p>
     * This method adheres to the general contract of the {@link Object#equals(Object)} method,
     * ensuring consistency with hash-based collections. It correctly handles cases where
     * {@code userId} might be {@code null} for unpersisted entities.
     * </p>
     *
     * @param o The reference object with which to compare.
     * @return {@code true} if this object is the same as the obj argument; {@code false} otherwise.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        // Equality is based on the primary key (userId), safely handling null Integer
        return Objects.equals(userId, user.userId);
    }
    /**
     * <p>
     * Returns a hash code value for the object. This method is supported for the benefit of
     * hash tables such as those provided by {@link java.util.HashMap} and {@link java.util.HashSet}.
     * </p>
     * <p>
     * The hash code is generated based on the unique {@code userId}. If {@code userId}
     * is {@code null} (for unpersisted entities), its hash code will be 0, as per {@link Objects#hash(Object...)}.
     * This ensures that objects considered equal by {@code equals} will have the same hash code,
     * fulfilling the contract between {@code equals} and {@code hashCode}.
     * </p>
     *
     * @return A hash code value for this object.
     */
    @Override
    public int hashCode() {
        return Objects.hash(userId);
    }
}