package com.avaruusstudios.vmdb.data;

/**
 * <p>
 * This interface defines the contract for Data Access Objects (DAOs) that provide
 * **creation (write) operations** on entities within the Vanpool Management Database (VMDB) application.
 * </p>
 *
 * <p>
 * This interface specifically adds a method for persisting new entities. It is suitable
 * for entities where new records need to be stored in the underlying data storage.
 * It focuses solely on the creation aspect, allowing for flexible composition with
 * other data access capabilities (e.g., read, update, delete).
 * </p>
 *
 * <p>
 * Implementations are responsible for handling the insertion of new records into
 * the underlying data storage and ensuring data integrity during this process.
 * </p>
 *
 * @param <T> The type of the entity (e.g., {@code com.avaruusstudios.vmdb.model.EventLog}).
 * This represents the domain model object that the DAO will persist and retrieve.
 *
 * @author AvaruusStudios
 * @version 1.0 // This version refers to the state of this specific interface's public contract
 * Created On: 2025-07-14 // Assuming original creation date for the content of this file
 * Updated On: 2025-07-20 // Current date of modification
 */
public interface CreateDataAccess<T> {

    /**
     * <p>
     * Inserts a new record of the specified entity into the database.
     * This method is used to persist a new instance of an entity.
     * </p>
     *
     * <p>
     * If the primary key of the entity is auto-generated by the database (e.g.,
     * an auto-incrementing ID), the {@code entity} object passed as a parameter
     * typically should *not* have its primary key field set beforehand. Upon successful
     * insertion, the returned entity object will include the newly generated primary key.
     * </p>
     *
     * @param entity The entity object (instance of type {@code T}) to be created and persisted.
     * Its non-primary key fields should contain the data to be stored.
     * @return The created entity object, which may include a database-generated primary key
     * if applicable. This object represents the state of the entity as stored.
     * @throws DatabaseAccessException if a database access error occurs during the insertion process,
     * if constraints are violated (e.g., unique key violation),
     * or if the creation operation otherwise fails. The underlying
     * {@code SQLException} will be wrapped within this custom exception.
     */
    T createRecord(T entity) throws DatabaseAccessException;
}