package com.avaruusstudios.vmdb.data;

/**
 * <p>
 * This interface defines the contract for Data Access Objects (DAOs) that **introduce
 * creation (write) operations** on entities within the Vanpool Management Database (VMDB) application.
 * </p>
 *
 * <p>
 * By extending {@link ReadDataAccess}, this interface inherits all methods for retrieving
 * and counting entities. Its primary distinguishing feature is the addition of a method
 * specifically for persisting new entities. This interface is particularly suitable for
 * entities that are designed to be created once and then read, but are not intended to
 * be updated or deleted through the application's standard data access layer (e.g., audit logs,
 * certain types of historical records where modifications are disallowed).
 * </p>
 *
 * <p>
 * Implementations are responsible for handling the insertion of new records into
 * the underlying data storage and ensuring data integrity during this process.
 * </p>
 *
 * @param <T> The type of the entity (e.g., {@code com.avaruusstudios.vmdb.model.EventLog}).
 * This represents the domain model object that the DAO will persist and retrieve.
 * @param <K> The type of the primary key for the entity {@code T}. Typically {@code java.lang.Integer}.
 *
 * @author [Your Name/AvaruusStudios]
 * @version 1.2 // Incremented version for JavaDoc clarification
 * @since 2025-07-11
 * @see ReadDataAccess
 */
public interface CreateDataAccess<T, K> extends ReadDataAccess<T, K> {

    /**
     * <p>
     * Inserts a new record of the specified entity into the database.
     * This method is used to persist a new instance of an entity.
     * </p>
     *
     * <p>
     * If the primary key of the entity is auto-generated by the database (e.g.,
     * an auto-incrementing ID), the {@code entity} object passed as a parameter
     * typically should *not* have its primary key field set beforehand. Upon successful
     * insertion, the returned entity object will include the newly generated primary key.
     * </p>
     *
     * @param entity The entity object (instance of type {@code T}) to be created and persisted.
     * Its non-primary key fields should contain the data to be stored.
     * @return The created entity object, which may include a database-generated primary key
     * if applicable. This object represents the state of the entity as stored.
     * @throws DatabaseAccessException if a database access error occurs during the insertion process,
     * if constraints are violated (e.g., unique key violation),
     * or if the creation operation otherwise fails. The underlying
     * {@code SQLException} will be wrapped within this custom exception.
     */
    T createRecord(T entity) throws DatabaseAccessException;

}