package com.avaruusstudios.vmdb.data;

import java.util.List;
import java.util.Optional;

/**
 * <p>
 * This interface defines the contract for a Generic Data Access Object (DAO) within the
 * Vanpool Management Database (VMDB) application. It provides a standardized set of
 * fundamental Create, Read, Update, Delete (CRUD) operations, along with a record
 * counting mechanism, for any given entity type.
 * </p>
 *
 * <p>
 * By using this generic interface, concrete DAO implementations (e.g., for Participants,
 * Vehicles, Transactions) can adhere to a consistent API, promoting code reusability,
 * maintainability, and testability across the data access layer.
 * </p>
 *
 * <p>
 * Implementations of this interface are responsible for interacting directly with the
 * underlying data storage (e.g., a relational database via JDBC) and translating
 * between the application's entity objects and the database's data structures.
 * </p>
 *
 * @param <T> The type of the entity (e.g., {@code com.avaruusstudios.vmdb.model.Participant},
 * {@code com.avaruusstudios.vmdb.model.Vehicle},
 * {@code com.avaruusstudios.vmdb.model.Transaction}). This represents the
 * domain model object that the DAO will persist and retrieve.
 * @param <K> The type of the primary key for the entity {@code T}. Based on your project's
 * design, this is typically {@code java.lang.Integer} for all tables.
 * This type parameter ensures type safety when performing operations
 * that rely on the entity's unique identifier.
 *
 * @author [Your Name/AvaruusStudios] // Consider adding author details
 * @version 1.0 // Initial version or current version
 * @since 2025-07-04 // Date of creation or last significant update
 */
public interface GenericDAO<T, K> {
    /**
     * <p>
     * Inserts a new record of the specified entity into the database.
     * This method is used to persist a new instance of an entity.
     * </p>
     *
     * <p>
     * If the primary key of the entity is auto-generated by the database (e.g.,
     * an auto-incrementing ID), the {@code entity} object passed as a parameter
     * typically should *not* have its primary key field set beforehand. Upon successful
     * insertion, the returned entity object will include the newly generated primary key.
     * </p>
     *
     * @param entity The entity object (instance of type {@code T}) to be created and persisted.
     * Its non-primary key fields should contain the data to be stored.
     * @return The created entity object, which may include a database-generated primary key
     * if applicable. This object represents the state of the entity as stored.
     * @throws DatabaseAccessObjectException if a database access error occurs during the insertion process,
     * if constraints are violated (e.g., unique key violation),
     * or if the creation operation otherwise fails. The underlying
     * {@code SQLException} will be wrapped within this custom exception.
     */
    T createRecord(T entity) throws DatabaseAccessObjectException;
    /**
     * <p>
     * Retrieves a single record of the entity from the database based on its primary key.
     * This method provides a way to fetch a specific entity instance.
     * </p>
     *
     * <p>
     * The result is wrapped in an {@code Optional<T>} to clearly indicate whether
     * an entity matching the given ID was found. This prevents {@code NullPointerExceptions}
     * and encourages explicit handling of cases where the record might not exist.
     * </p>
     *
     * @param id The primary key (of type {@code K}, typically {@code Integer}) of the
     * entity record to retrieve. This uniquely identifies the record in the database.
     * @return An {@code Optional<T>} containing the entity object if a record with the
     * specified ID is found in the database; otherwise, an empty {@code Optional}.
     * @throws DatabaseAccessObjectException if a database access error occurs during the retrieval process.
     * The underlying {@code SQLException} will be wrapped.
     */
    Optional<T> readRecord(K id) throws DatabaseAccessObjectException;
    /**
     * <p>
     * Retrieves all records of the entity from the database.
     * This method is used to fetch a complete list of all instances of a given entity type.
     * </p>
     *
     * <p>
     * The order of the returned records is dependent on the underlying database and
     * the SQL query used by the concrete implementation (e.g., if no specific
     * ORDER BY clause is applied, the order might not be guaranteed).
     * </p>
     *
     * @return A {@code List<T>} containing all entity objects found in the corresponding
     * database table. Returns an empty list if no records are present.
     * The list will not be {@code null}.
     * @throws DatabaseAccessObjectException if a database access error occurs during the retrieval process.
     * The underlying {@code SQLException} will be wrapped.
     */
    List<T> readRecordAll() throws DatabaseAccessObjectException;
    /**
     * <p>
     * Updates an existing record of the entity in the database.
     * This method is used to modify the persistent state of an entity.
     * </p>
     *
     * <p>
     * For the update operation to succeed, the {@code entity} object passed as a parameter
     * *must* have its primary key field set. This ID is used to identify which existing
     * record in the database should be updated. All other fields in the {@code entity}
     * object will be used to update the corresponding columns in the database.
     * </p>
     *
     * @param entity The entity object (instance of type {@code T}) with its primary key
     * set and updated values for other fields.
     * @throws DatabaseAccessObjectException if a database access error occurs during the update process,
     * if no record with the given primary key is found to update,
     * or if the update operation otherwise fails (e.g., due to constraints).
     * The underlying {@code SQLException} will be wrapped.
     */
    void updateRecord(T entity) throws DatabaseAccessObjectException;
    /**
     * <p>
     * Deletes a record of the entity from the database based on its primary key.
     * This method permanently removes an entity instance from the persistent storage.
     * </p>
     *
     * <p>
     * If no record matches the provided ID, the operation will typically complete
     * without throwing an error, but no rows will be affected. Implementations
     * might log a warning or return a boolean indicating success if desired.
     * </p>
     *
     * @param id The primary key (of type {@code K}, typically {@code Integer}) of the
     * entity record to delete. This uniquely identifies the record to be removed.
     * @throws DatabaseAccessObjectException if a database access error occurs during the deletion process.
     * The underlying {@code SQLException} will be wrapped.
     */
    void deleteRecord(K id) throws DatabaseAccessObjectException;
    /**
     * <p>
     * Counts the total number of records for the specific entity type in the database.
     * This method provides a quick way to determine the size of the dataset.
     * </p>
     *
     * @return The total count of records (rows) present in the database table
     * corresponding to the entity type {@code T}. Returns {@code 0} if no
     * records are found.
     * @throws DatabaseAccessObjectException if a database access error occurs during the counting process.
     * The underlying {@code SQLException} will be wrapped.
     */
    long countRecord() throws DatabaseAccessObjectException;
}