INSERT INTO Roles (Role) VALUES ('ADMIN');
INSERT INTO Roles (Role) VALUES ('COORDINATOR');
INSERT INTO Roles (Role) VALUES ('ASSISTANT');
INSERT INTO Roles (Role) VALUES ('TREASURER');
INSERT INTO Roles (Role) VALUES ('USER');
INSERT INTO Roles (Role) VALUES ('PARTICIPANT');