package com.avaruusstudios.vmdb.dao.impl.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Location;
import com.avaruusstudios.vmdb.dao.LocationDataAccess;
import com.avaruusstudios.vmdb.dao.DeleteDataAccess;
import com.avaruusstudios.vmdb.dao.UpdateDataAccess;
import com.avaruusstudios.vmdb.dao.CreateDataAccess;
import com.avaruusstudios.vmdb.dao.ReadDataAccess;
import com.avaruusstudios.vmdb.dao.DatabaseAccessException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link LocationDataAccess} interface for managing
 * {@link Location} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Location} entities (e.g., finding by unique location name
 * or by address components).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Location IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of a location is enforced through a combination of `LocationName`, `Address`,
 * `City`, `State`, and `ZipCode` at the database level.</li>
 * <li>Deletion of location records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.0
 * Created On: 2025-07-20
 * Updated On: 2025-07-22
 *
 * @see LocationDataAccess
 * @see Location
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class LocationImplementation implements LocationDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code LocationImplementation} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(LocationImplementation.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new location record. Loaded from `location/insertLocation.sql`. */
    private static final String SQL_CREATE_LOCATION_RECORD;
    /** SQL query to select a location record by its unique ID. Loaded from `location/selectLocationById.sql`. */
    private static final String SQL_READ_LOCATION_RECORD;
    /** SQL query to select all location records. Loaded from `location/selectAllLocations.sql`. */
    private static final String SQL_READ_ALL_LOCATION_RECORDS;
    /** SQL query to count the total number of location records. Loaded from `location/countLocations.sql`. */
    private static final String SQL_COUNT_LOCATION_RECORDS;
    /** SQL query to check if a location record with a given ID exists. Loaded from `location/existsLocationById.sql`. */
    private static final String SQL_EXISTS_LOCATION_BY_ID;
    /** SQL query to update an existing location record. Loaded from `location/updateLocation.sql`. */
    private static final String SQL_UPDATE_LOCATION_RECORD;
    /** SQL query to soft-delete a location record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `location/deleteLocationSoft.sql`. */
    private static final String SQL_DELETE_LOCATION_SOFT;
    /** SQL query to select a location record by its unique name. Loaded from `location/selectLocationByName.sql`. */
    private static final String SQL_SELECT_LOCATION_BY_NAME;
    /** SQL query to select a location record by a combination of street address, city, state, and zip code. Loaded from `location/selectLocationByAddress.sql`. */
    private static final String SQL_SELECT_LOCATION_BY_ADDRESS;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}. This block executes only once when the class is first loaded,
     * ensuring that all necessary SQL queries are available before any database operations are attempted.
     * <p>
     * If any query file cannot be found or loaded, an {@link IllegalArgumentException} is caught,
     * logged as an error, and re-thrown as an {@link ExceptionInInitializerError} to indicate
     * a critical application setup failure that prevents the DAO from functioning correctly.
     * </p>
     */
    static {
        try {
            SQL_CREATE_LOCATION_RECORD = QueryLoader.getQuery("location/insertLocation.sql");
            SQL_READ_LOCATION_RECORD = QueryLoader.getQuery("location/selectLocationById.sql");
            SQL_READ_ALL_LOCATION_RECORDS = QueryLoader.getQuery("location/selectAllLocations.sql");
            SQL_COUNT_LOCATION_RECORDS = QueryLoader.getQuery("location/countLocations.sql");
            SQL_EXISTS_LOCATION_BY_ID = QueryLoader.getQuery("location/existsLocationById.sql");
            SQL_UPDATE_LOCATION_RECORD = QueryLoader.getQuery("location/updateLocation.sql");
            SQL_DELETE_LOCATION_SOFT = QueryLoader.getQuery("location/deleteLocationSoft.sql");
            SQL_SELECT_LOCATION_BY_NAME = QueryLoader.getQuery("location/selectLocationByName.sql");
            SQL_SELECT_LOCATION_BY_ADDRESS = QueryLoader.getQuery("location/selectLocationByAddress.sql");
            logger.info("All SQL queries for LocationImplementation loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for LocationImplementation. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Location} object.
     * This private helper method centralizes the logic for converting raw database
     * column values into a populated {@code Location} model object, ensuring data consistency
     * and type safety across all read operations.
     * </p>
     * <p>
     * It handles:
     * <ul>
     * <li>Retrieval of the auto-generated `LocationID` and setting it via the package-private `_setLocationID` method.</li>
     * <li>String fields (e.g., `LocationName`, `Address`, `City`, `State`, `ZipCode`, `Notes`).</li>
     * <li>Double fields (e.g., `Latitude`, `Longitude`).</li>
     * <li>Conversion of `IsActive` from `INTEGER` (0 or 1) to `boolean`.</li>
     * <li>Handling of nullable `DeletedAt` `TEXT` field, parsing it into
     * {@link LocalDateTime} objects using {@link #CUSTOM_DATETIME_FORMATTER} if present.</li>
     * </ul>
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing location data.
     * @return A fully populated {@link Location} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs (e.g., a column name is not found,
     * or there is a data type mismatch during retrieval).
     */
    private Location mapResultSetToLocation(ResultSet rs) throws SQLException {
        Location location = new Location();

        Integer locationId = rs.getInt("LocationID");
        if (locationId > 0) { // SQLite getInt returns 0 for NULL, check for positive valid ID
            location._setLocationID(locationId);
        }

        location.setLocationName(rs.getString("LocationName"));
        location.setAddress(rs.getString("Address"));
        location.setCity(rs.getString("City"));
        location.setState(rs.getString("State"));
        location.setZipCode(rs.getString("ZipCode"));

        Double latitude = rs.getObject("Latitude", Double.class);
        location.setLatitude(latitude);

        Double longitude = rs.getObject("Longitude", Double.class);
        location.setLongitude(longitude);

        location.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        location.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ?
                LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        location.setNotes(rs.getString("Notes"));

        return location;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Location> findByName(String locationName) throws DatabaseAccessException {
        Objects.requireNonNull(locationName, "Location name cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_LOCATION_BY_NAME)) {

            stmt.setString(1, locationName);
            logger.debug("Executing query: {} with location name: {}", SQL_SELECT_LOCATION_BY_NAME, locationName);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Location location = mapResultSetToLocation(rs);
                    logger.info("Found location with name: {}", locationName);
                    return Optional.of(location);
                } else {
                    logger.info("No location found with name: {}", locationName);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding location by name {}: {}", locationName, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding location by name: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Location> findByAddress(String address, String city, String state, String zipCode) throws DatabaseAccessException {
        Objects.requireNonNull(address, "Address cannot be null for lookup.");
        Objects.requireNonNull(city, "City cannot be null for lookup.");
        Objects.requireNonNull(state, "State cannot be null for lookup.");
        Objects.requireNonNull(zipCode, "Zip Code cannot be null for lookup.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_LOCATION_BY_ADDRESS)) {

            stmt.setString(1, address);
            stmt.setString(2, city);
            stmt.setString(3, state);
            stmt.setString(4, zipCode);

            logger.debug("Executing query: {} with address: {}, city: {}, state: {}, zip: {}",
                    SQL_SELECT_LOCATION_BY_ADDRESS, address, city, state, zipCode);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Location location = mapResultSetToLocation(rs);
                    logger.info("Found location by address: {}, {}, {}, {}", address, city, state, zipCode);
                    return Optional.of(location);
                } else {
                    logger.info("No location found by address: {}, {}, {}, {}", address, city, state, zipCode);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding location by address components ({}, {}, {}, {}): {}",
                    address, city, state, zipCode, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding location by address: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Location create(Location location) throws DatabaseAccessException {
        Objects.requireNonNull(location, "Location object cannot be null for creation.");
        if (location.getLocationID() != null) {
            throw new IllegalArgumentException("Location ID must be null for new location creation (auto-generated).");
        }

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_CREATE_LOCATION_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, location.getLocationName());
            stmt.setString(2, location.getAddress());
            stmt.setString(3, location.getCity());
            stmt.setString(4, location.getState());
            stmt.setString(5, location.getZipCode());

            if (location.getLatitude() != null) {
                stmt.setDouble(6, location.getLatitude());
            } else {
                stmt.setNull(6, Types.DOUBLE);
            }

            if (location.getLongitude() != null) {
                stmt.setDouble(7, location.getLongitude());
            } else {
                stmt.setNull(7, Types.DOUBLE);
            }

            stmt.setInt(8, location.getIsActive() ? 1 : 0); // true = 1, false = 0
            stmt.setString(9, location.getDeletedAt() != null ? location.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(10, location.getNotes());

            logger.debug("Executing insert location query for location: {}", location.getLocationName());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.error("Creating location failed, no rows affected for location: {}", location.getLocationName());
                throw new DatabaseAccessException("Creating location failed, no rows affected.");
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    Integer generatedId = generatedKeys.getInt(1);
                    location._setLocationID(generatedId); // Set the auto-generated ID
                    logger.info("Successfully created location with ID: {}", generatedId);
                    return location;
                } else {
                    logger.error("Creating location failed, no ID obtained for location: {}", location.getLocationName());
                    throw new DatabaseAccessException("Creating location failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            logger.error("Error creating location record: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error creating location record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For this application, implementations of this method are expected to perform a
     * **soft-delete** rather than physically removing the record from the database.
     * This typically involves updating an `IsActive` flag to `0` and/or setting a
     * `DeletedAt` timestamp to the current time. This strategy preserves data integrity
     * for historical, auditing, and referential purposes, and allows for potential recovery.
     * </p>
     *
     * <p>
     * If no record matches the provided ID, the operation will typically complete
     * without throwing an error, but no rows will be affected. Implementations
     * might log a warning or return a boolean indicating success if desired.
     * </p>
     */
    @Override
    public void delete(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for deletion.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_DELETE_LOCATION_SOFT)) {

            stmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER)); // Set DeletedAt
            stmt.setInt(2, id); // Where LocationID = ?

            logger.debug("Executing soft-delete location query for ID: {}", id);
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No location found with ID: {} for soft-deletion.", id);
            } else {
                logger.info("Successfully soft-deleted location with ID: {}", id);
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting location record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error soft-deleting location record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The result is wrapped in an {@code Optional<Location>} to clearly indicate whether
     * an entity matching the given ID was found. This prevents {@code NullPointerExceptions}
     * and encourages explicit handling of cases where the record might not exist.
     * </p>
     */
    @Override
    public Optional<Location> read(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for reading.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_LOCATION_RECORD)) {

            stmt.setInt(1, id);
            logger.debug("Executing read location query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Location location = mapResultSetToLocation(rs);
                    logger.info("Found location with ID: {}", id);
                    return Optional.of(location);
                } else {
                    logger.info("No location found with ID: {}", id);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error reading location record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error reading location record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * The order of the returned records is dependent on the underlying database and
     * the SQL query used by the concrete implementation (e.g., if no specific
     * ORDER BY clause is applied, the order might not be guaranteed).
     * </p>
     */
    @Override
    public List<Location> readAll() throws DatabaseAccessException {
        List<Location> locations = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_ALL_LOCATION_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing read all locations query.");
            while (rs.next()) {
                locations.add(mapResultSetToLocation(rs));
            }
            logger.info("Found {} total locations.", locations.size());
        } catch (SQLException e) {
            logger.error("Error reading all location records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error reading all location records: " + e.getMessage(), e);
        }
        return locations;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long count() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_LOCATION_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total location record count: {}", count);
                return count;
            }
            return 0; // Should not happen if query returns 0, but as a safeguard
        } catch (SQLException e) {
            logger.error("Error counting location records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting location records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Location ID cannot be null for existence check.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_EXISTS_LOCATION_BY_ID)) {

            stmt.setInt(1, id);
            logger.debug("Executing existsById location query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                boolean exists = rs.next();
                logger.info("Location with ID {} exists: {}", id, exists);
                return exists;
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of location record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error checking existence of location record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     *
     * <p>
     * For the update operation to succeed, the {@code location} object passed as a parameter
     * *must* have its primary key field set. This ID is used to identify which existing
     * record in the database should be updated. All other fields in the {@code location}
     * object will be used to update the corresponding columns in the database.
     * </p>
     */
    @Override
    public void update(Location location) throws DatabaseAccessException {
        Objects.requireNonNull(location, "Location object cannot be null for update.");
        Objects.requireNonNull(location.getLocationID(), "Location ID must not be null for update.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_UPDATE_LOCATION_RECORD)) {

            stmt.setString(1, location.getLocationName());
            stmt.setString(2, location.getAddress());
            stmt.setString(3, location.getCity());
            stmt.setString(4, location.getState());
            stmt.setString(5, location.getZipCode());

            if (location.getLatitude() != null) {
                stmt.setDouble(6, location.getLatitude());
            } else {
                stmt.setNull(6, Types.DOUBLE);
            }

            if (location.getLongitude() != null) {
                stmt.setDouble(7, location.getLongitude());
            } else {
                stmt.setNull(7, Types.DOUBLE);
            }

            stmt.setInt(8, location.getIsActive() ? 1 : 0);
            stmt.setString(9, location.getDeletedAt() != null ? location.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(10, location.getNotes());
            stmt.setInt(11, location.getLocationID()); // WHERE clause

            logger.debug("Executing update location query for ID: {}", location.getLocationID());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No location found with ID: {} for update. Update operation resulted in 0 affected rows.", location.getLocationID());
                throw new DatabaseAccessException("Location with ID " + location.getLocationID() + " not found for update.");
            } else {
                logger.info("Successfully updated location with ID: {}", location.getLocationID());
            }
        } catch (SQLException e) {
            logger.error("Error updating location record with ID {}: {}", location.getLocationID(), e.getMessage(), e);
            throw new DatabaseAccessException("Error updating location record: " + e.getMessage(), e);
        }
    }
}