package com.avaruusstudios.vmdb.dao.impl.sqlite;

import com.avaruusstudios.vmdb.db.DatabaseManager;
import com.avaruusstudios.vmdb.db.QueryLoader;
import com.avaruusstudios.vmdb.model.Vehicle;
import com.avaruusstudios.vmdb.dao.VehicleDataAccess;
import com.avaruusstudios.vmdb.dao.DeleteDataAccess;
import com.avaruusstudios.vmdb.dao.UpdateDataAccess;
import com.avaruusstudios.vmdb.dao.CreateDataAccess;
import com.avaruusstudios.vmdb.dao.ReadDataAccess;
import com.avaruusstudios.vmdb.dao.DatabaseAccessException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>
 * Concrete implementation of the {@link VehicleDataAccess} interface for managing
 * {@link Vehicle} data in an SQLite database. This class fully implements all generic
 * CRUD and read operations inherited via the decoupled data access interfaces, along with
 * specific queries for {@code Vehicle} entities (e.g., finding by license plate or type).
 * </p>
 *
 * <p>
 * This implementation leverages {@link DatabaseManager} to obtain and manage database
 * connections, and {@link QueryLoader} to dynamically load SQL queries from external
 * `.sql` files. This design promotes separation of concerns and facilitates easier
 * maintenance of SQL statements.
 * </p>
 *
 * <p>
 * Key characteristics of this implementation include:
 * </p>
 * <ul>
 * <li>Vehicle IDs are auto-generated by the database upon insertion.</li>
 * <li>Uniqueness of `LicensePlate` is enforced at the database level.</li>
 * <li>Deletion of vehicle records is implemented as a **soft-delete**, meaning records are
 * deactivated by updating their `IsActive` flag to `0` (false) and setting the
 * `DeletedAt` timestamp, rather than physically removing them from the database.</li>
 * <li>`LocalDateTime` objects are persisted as `TEXT` in the SQLite database using a
 * custom format ("dd-MMM-yyyy HH:mm") and parsed back from this format.</li>
 * <li>`boolean` values (e.g., for `IsActive`) are stored as `INTEGER` (`1` for true, `0` for false)
 * in the SQLite database.</li>
 * <li>All {@link SQLException}s originating from database interactions are
 * wrapped into custom {@link DatabaseAccessException}s, providing a consistent
 * layer for error handling across the DAO.</li>
 * </ul>
 *
 * @author AvaruusStudios
 * @version 1.1
 * Created On: 2025-07-14
 * Updated On: 2025-09-22
 *
 * @see VehicleDataAccess
 * @see Vehicle
 * @see DatabaseManager
 * @see QueryLoader
 * @see DatabaseAccessException
 * @see CreateDataAccess
 * @see ReadDataAccess
 * @see UpdateDataAccess
 * @see DeleteDataAccess
 */
public class VehicleDataAccessImpl implements VehicleDataAccess {

    /**
     * SLF4J logger for logging informational messages, warnings, and errors within the {@code VehicleDataAccessImpl} class.
     */
    private static final Logger logger = LoggerFactory.getLogger(VehicleDataAccessImpl.class);

    /**
     * <p>
     * Date/time formatter for converting between {@link LocalDateTime} objects in Java
     * and `TEXT` representation in the SQLite database.
     * </p>
     * <p>
     * The pattern "dd-MMM-yyyy HH:mm" ensures a consistent format (e.g., "14-Jul-2025 10:30").
     * {@link Locale#ENGLISH} is used to guarantee consistent month abbreviations (e.g., "Jan", "Feb")
     * regardless of the default locale of the JVM.
     * </p>
     */
    private static final DateTimeFormatter CUSTOM_DATETIME_FORMATTER = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm", Locale.ENGLISH);

    // SQL Query Constants
    /** SQL query to insert a new vehicle record. Loaded from `vehicle/insertVehicle.sql`. */
    private static final String SQL_CREATE_VEHICLE_RECORD;
    /** SQL query to select a vehicle record by its unique ID. Loaded from `vehicle/selectVehicleById.sql`. */
    private static final String SQL_READ_VEHICLE_RECORD;
    /** SQL query to select all vehicle records. Loaded from `vehicle/selectAllVehicles.sql`. */
    private static final String SQL_READ_ALL_VEHICLE_RECORDS;
    /** SQL query to count the total number of vehicle records. Loaded from `vehicle/countVehicles.sql`. */
    private static final String SQL_COUNT_VEHICLE_RECORDS;
    /** SQL query to check if a vehicle record with a given ID exists. Loaded from `vehicle/existsVehicleById.sql`. */
    private static final String SQL_EXISTS_VEHICLE_BY_ID;
    /** SQL query to update an existing vehicle record. Loaded from `vehicle/updateVehicle.sql`. */
    private static final String SQL_UPDATE_VEHICLE_RECORD;
    /** SQL query to soft-delete a vehicle record by updating its `IsActive` flag and `DeletedAt` timestamp. Loaded from `vehicle/deleteVehicleSoft.sql`. */
    private static final String SQL_DELETE_VEHICLE_SOFT;
    /** SQL query to select a vehicle record by its unique vehicle number (asset number). Loaded from `vehicle/selectVehicleByVehicleNumber.sql`. */
    private static final String SQL_SELECT_VEHICLE_BY_VEHICLE_NUMBER;
    /** SQL query to select a vehicle record by its unique license plate. Loaded from `vehicle/selectVehicleByLicensePlate.sql`. */
    private static final String SQL_SELECT_VEHICLE_BY_LICENSE_PLATE;
    /** SQL query to select the active vehicle. Loaded from `vehicle/selectActiveVehicle.sql`. */
    private static final String SQL_SELECT_ACTIVE_VEHICLE;
    /** SQL query to select vehicles by make. Loaded from `vehicle/selectVehiclesByMake.sql`. */
    private static final String SQL_SELECT_VEHICLES_BY_MAKE;
    /** SQL query to select vehicles by model. Loaded from `vehicle/selectVehiclesByModel.sql`. */
    private static final String SQL_SELECT_VEHICLES_BY_MODEL;
    /** SQL query to select vehicles by year. Loaded from `vehicle/selectVehiclesByYear.sql`. */
    private static final String SQL_SELECT_VEHICLES_BY_YEAR;
    /** SQL query to count the total number of active vehicle records. */
    private static final String SQL_COUNT_ACTIVE_VEHICLE_RECORDS;

    /**
     * Static initializer block to load all SQL query strings from external `.sql` files
     * using the {@link QueryLoader}.
     */
    static {
        try {
            // SQL filenames adhere to the 'lowercaseFirstWordCamelCase.sql' convention
            SQL_CREATE_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/insertVehicle.sql");
            SQL_READ_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/selectVehicleById.sql");
            SQL_READ_ALL_VEHICLE_RECORDS = QueryLoader.getQuery("vehicle/selectAllVehicles.sql");
            SQL_COUNT_VEHICLE_RECORDS = QueryLoader.getQuery("vehicle/countVehicles.sql");
            SQL_EXISTS_VEHICLE_BY_ID = QueryLoader.getQuery("vehicle/existsVehicleById.sql");
            SQL_UPDATE_VEHICLE_RECORD = QueryLoader.getQuery("vehicle/updateVehicle.sql");
            SQL_DELETE_VEHICLE_SOFT = QueryLoader.getQuery("vehicle/deleteVehicleSoft.sql");
            SQL_SELECT_VEHICLE_BY_LICENSE_PLATE = QueryLoader.getQuery("vehicle/selectVehicleByLicensePlate.sql");
            SQL_SELECT_VEHICLE_BY_VEHICLE_NUMBER = QueryLoader.getQuery("vehicle/selectVehicleByVehicleNumber.sql");
            SQL_SELECT_ACTIVE_VEHICLE = "SELECT * FROM Vehicles WHERE IsActive = 1"; // This has been moved out of QueryLoader to support returning a List
            SQL_SELECT_VEHICLES_BY_MAKE = QueryLoader.getQuery("vehicle/selectVehiclesByMake.sql");
            SQL_SELECT_VEHICLES_BY_MODEL = QueryLoader.getQuery("vehicle/selectVehiclesByModel.sql");
            SQL_SELECT_VEHICLES_BY_YEAR = QueryLoader.getQuery("vehicle/selectVehiclesByYear.sql");
            SQL_COUNT_ACTIVE_VEHICLE_RECORDS = "SELECT COUNT(*) FROM Vehicles WHERE IsActive = 1";
            logger.info("All SQL queries for VehicleDataAccessImpl loaded successfully.");
        } catch (IllegalArgumentException e) {
            logger.error("Failed to load one or more SQL queries for VehicleDataAccessImpl. Check .sql files and paths.", e);
            throw new ExceptionInInitializerError(e); // Indicate a critical initialization failure
        }
    }

    /**
     * <p>
     * Maps a row from a {@link ResultSet} to a {@link Vehicle} object.
     * </p>
     *
     * @param rs The {@link ResultSet} positioned at the current row containing vehicle data.
     * @return A fully populated {@link Vehicle} object with data retrieved from the {@code ResultSet}.
     * @throws SQLException If a database access error occurs.
     */
    private Vehicle mapResultSetToVehicle(ResultSet rs) throws SQLException {
        Vehicle vehicle = new Vehicle();
        Integer vehicleId = rs.getInt("VehicleID");
        if (vehicleId > 0) {
            vehicle._setVehicleID(vehicleId);
        }

        vehicle.setMake(rs.getString("Make"));
        vehicle.setModel(rs.getString("Model"));
        vehicle.setManufactureYear(rs.getInt("ManufactureYear"));
        vehicle.setLicensePlate(rs.getString("LicensePlate"));
        vehicle.setPassengerCapacity(rs.getInt("PassengerCapacity"));
        vehicle.setVehicleNumber(rs.getString("VehicleNumber"));

        vehicle.setIsActive(rs.getInt("IsActive") == 1);

        String deletedAtStr = rs.getString("DeletedAt");
        vehicle.setDeletedAt(deletedAtStr != null && !deletedAtStr.isEmpty() ? LocalDateTime.parse(deletedAtStr, CUSTOM_DATETIME_FORMATTER) : null);

        return vehicle;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vehicle create(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle object cannot be null for creation.");
        if (vehicle.getVehicleID() != null) {
            throw new IllegalArgumentException("Vehicle ID must be null for new vehicle creation (auto-generated).");
        }
        Objects.requireNonNull(vehicle.getMake(), "Make cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getModel(), "Model cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getLicensePlate(), "LicensePlate cannot be null for vehicle creation.");
        Objects.requireNonNull(vehicle.getVehicleNumber(), "VehicleNumber cannot be null for vehicle creation.");


        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_CREATE_VEHICLE_RECORD, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, vehicle.getMake());
            stmt.setString(2, vehicle.getModel());
            stmt.setInt(3, vehicle.getManufactureYear());
            stmt.setString(4, vehicle.getLicensePlate());
            stmt.setInt(5, vehicle.getPassengerCapacity());
            stmt.setInt(7, vehicle.isActive() ? 1 : 0);
            stmt.setString(8, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(9, vehicle.getVehicleNumber());

            logger.debug("Executing insert vehicle query for license plate: {}", vehicle.getLicensePlate());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.error("Creating vehicle failed, no rows affected for license plate: {}", vehicle.getLicensePlate());
                throw new DatabaseAccessException("Creating vehicle failed, no rows affected.");
            }

            try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    Integer generatedId = generatedKeys.getInt(1);
                    vehicle._setVehicleID(generatedId);
                    logger.info("Successfully created vehicle with ID: {}", generatedId);
                    return vehicle;
                } else {
                    logger.error("Creating vehicle failed, no ID obtained for license plate: {}", vehicle.getLicensePlate());
                    throw new DatabaseAccessException("Creating vehicle failed, no ID obtained.");
                }
            }
        } catch (SQLException e) {
            logger.error("Error creating vehicle record: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error creating vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean delete(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for deletion.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_DELETE_VEHICLE_SOFT)) {

            stmt.setString(1, LocalDateTime.now().format(CUSTOM_DATETIME_FORMATTER));
            stmt.setInt(2, id);

            logger.debug("Executing soft-delete vehicle query for ID: {}", id);
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No vehicle found with ID: {} for soft-deletion.", id);
                return false;
            } else {
                logger.info("Successfully soft-deleted vehicle with ID: {}", id);
                return true;
            }
        } catch (SQLException e) {
            logger.error("Error soft-deleting vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error soft-deleting vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Vehicle> find(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for reading.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_VEHICLE_RECORD)) {

            stmt.setInt(1, id);
            logger.debug("Executing read vehicle query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Vehicle vehicle = mapResultSetToVehicle(rs);
                    logger.info("Found vehicle with ID: {}", id);
                    return Optional.of(vehicle);
                } else {
                    logger.info("No vehicle found with ID: {}", id);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error reading vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error reading vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findAll() throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_READ_ALL_VEHICLE_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing read all vehicles query.");
            while (rs.next()) {
                vehicles.add(mapResultSetToVehicle(rs));
            }
            logger.info("Found {} total vehicles.", vehicles.size());
        } catch (SQLException e) {
            logger.error("Error reading all vehicle records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error reading all vehicle records: " + e.getMessage(), e);
        }
        return vehicles;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findActive() throws DatabaseAccessException {
        List<Vehicle> activeVehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_ACTIVE_VEHICLE);
             ResultSet rs = stmt.executeQuery()) {

            logger.debug("Executing find active vehicles query.");
            while (rs.next()) {
                activeVehicles.add(mapResultSetToVehicle(rs));
            }
            logger.info("Found {} active vehicles.", activeVehicles.size());

            // A business rule violation would be more than one active vehicle, which is handled in the application logic.
            // The method signature requires a list, so we return all found.
            return activeVehicles;

        } catch (SQLException e) {
            logger.error("Error finding active vehicles: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error finding active vehicles: " + e.getMessage(), e);
        }
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public long count() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_VEHICLE_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total vehicle record count: {}", count);
                return count;
            }
            return 0;
        } catch (SQLException e) {
            logger.error("Error counting vehicle records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting vehicle records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public long countActive() throws DatabaseAccessException {
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_COUNT_ACTIVE_VEHICLE_RECORDS);
             ResultSet rs = stmt.executeQuery()) {

            if (rs.next()) {
                long count = rs.getLong(1);
                logger.info("Total active vehicle record count: {}", count);
                return count;
            }
            return 0;
        } catch (SQLException e) {
            logger.error("Error counting active vehicle records: {}", e.getMessage(), e);
            throw new DatabaseAccessException("Error counting active vehicle records: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean existsById(Integer id) throws DatabaseAccessException {
        Objects.requireNonNull(id, "Vehicle ID cannot be null for existence check.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_EXISTS_VEHICLE_BY_ID)) {

            stmt.setInt(1, id);
            logger.debug("Executing existsById vehicle query for ID: {}", id);
            try (ResultSet rs = stmt.executeQuery()) {
                boolean exists = rs.next();
                logger.info("Vehicle with ID {} exists: {}", id, exists);
                return exists;
            }
        } catch (SQLException e) {
            logger.error("Error checking existence of vehicle record with ID {}: {}", id, e.getMessage(), e);
            throw new DatabaseAccessException("Error checking existence of vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Vehicle update(Vehicle vehicle) throws DatabaseAccessException {
        Objects.requireNonNull(vehicle, "Vehicle object cannot be null for update.");
        Objects.requireNonNull(vehicle.getVehicleID(), "Vehicle ID must not be null for update.");
        Objects.requireNonNull(vehicle.getMake(), "Make cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getModel(), "Model cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getLicensePlate(), "LicensePlate cannot be null for vehicle update.");
        Objects.requireNonNull(vehicle.getVehicleNumber(), "VehicleNumber cannot be null for vehicle update.");

        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_UPDATE_VEHICLE_RECORD)) {

            stmt.setString(1, vehicle.getMake());
            stmt.setString(2, vehicle.getModel());
            stmt.setInt(3, vehicle.getManufactureYear());
            stmt.setString(4, vehicle.getLicensePlate());
            stmt.setInt(5, vehicle.getPassengerCapacity());
            stmt.setInt(7, vehicle.isActive() ? 1 : 0);
            stmt.setString(8, vehicle.getDeletedAt() != null ? vehicle.getDeletedAt().format(CUSTOM_DATETIME_FORMATTER) : null);
            stmt.setString(9, vehicle.getVehicleNumber());
            stmt.setInt(10, vehicle.getVehicleID()); // WHERE clause

            logger.debug("Executing update vehicle query for ID: {}", vehicle.getVehicleID());
            int affectedRows = stmt.executeUpdate();

            if (affectedRows == 0) {
                logger.warn("No vehicle found with ID: {} for update. Update operation resulted in 0 affected rows.", vehicle.getVehicleID());
                throw new DatabaseAccessException("Vehicle with ID " + vehicle.getVehicleID() + " not found for update.");
            } else {
                logger.info("Successfully updated vehicle with ID: {}", vehicle.getVehicleID());
                return vehicle;
            }
        } catch (SQLException e) {
            logger.error("Error updating vehicle record with ID {}: {}", vehicle.getVehicleID(), e.getMessage(), e);
            throw new DatabaseAccessException("Error updating vehicle record: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Vehicle> findByNumber(String vehicleNumber) throws DatabaseAccessException {
        Objects.requireNonNull(vehicleNumber, "Vehicle number cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLE_BY_VEHICLE_NUMBER)) {

            stmt.setString(1, vehicleNumber);
            logger.debug("Executing query: {} with vehicle number: {}", SQL_SELECT_VEHICLE_BY_VEHICLE_NUMBER, vehicleNumber);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Vehicle vehicle = mapResultSetToVehicle(rs);
                    logger.info("Found vehicle with vehicle number: {}", vehicleNumber);
                    return Optional.of(vehicle);
                } else {
                    logger.info("No vehicle found with vehicle number: {}", vehicleNumber);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding vehicle by vehicle number {}: {}", vehicleNumber, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicle by vehicle number: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Optional<Vehicle> findByPlate(String licensePlate) throws DatabaseAccessException {
        Objects.requireNonNull(licensePlate, "License plate cannot be null for lookup.");
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLE_BY_LICENSE_PLATE)) {

            stmt.setString(1, licensePlate);
            logger.debug("Executing query: {} with license plate: {}", SQL_SELECT_VEHICLE_BY_LICENSE_PLATE, licensePlate);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Vehicle vehicle = mapResultSetToVehicle(rs);
                    logger.info("Found vehicle with license plate: {}", licensePlate);
                    return Optional.of(vehicle);
                } else {
                    logger.info("No vehicle found with license plate: {}", licensePlate);
                    return Optional.empty();
                }
            }
        } catch (SQLException e) {
            logger.error("Error finding vehicle by license plate {}: {}", licensePlate, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicle by license plate: " + e.getMessage(), e);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findByMake(String make) throws DatabaseAccessException {
        Objects.requireNonNull(make, "Make cannot be null for finding vehicles by make.");
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLES_BY_MAKE)) {

            stmt.setString(1, make);
            logger.debug("Executing find vehicles by make query for make: {}", make);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            logger.info("Found {} vehicles for make: {}", vehicles.size(), make);
        } catch (SQLException e) {
            logger.error("Error finding vehicles by make {}: {}", make, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicles by make: " + e.getMessage(), e);
        }
        return vehicles;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findByModel(String model) throws DatabaseAccessException {
        Objects.requireNonNull(model, "Model cannot be null for finding vehicles by model.");
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLES_BY_MODEL)) {

            stmt.setString(1, model);
            logger.debug("Executing find vehicles by model query for model: {}", model);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            logger.info("Found {} vehicles for model: {}", vehicles.size(), model);
        } catch (SQLException e) {
            logger.error("Error finding vehicles by model {}: {}", model, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicles by model: " + e.getMessage(), e);
        }
        return vehicles;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Vehicle> findByYear(int year) throws DatabaseAccessException {
        List<Vehicle> vehicles = new ArrayList<>();
        try (Connection conn = DatabaseManager.getConnection();
             PreparedStatement stmt = conn.prepareStatement(SQL_SELECT_VEHICLES_BY_YEAR)) {

            stmt.setInt(1, year);
            logger.debug("Executing find vehicles by year query for year: {}", year);
            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    vehicles.add(mapResultSetToVehicle(rs));
                }
            }
            logger.info("Found {} vehicles for year: {}", vehicles.size(), year);
        } catch (SQLException e) {
            logger.error("Error finding vehicles by year {}: {}", year, e.getMessage(), e);
            throw new DatabaseAccessException("Error finding vehicles by year: " + e.getMessage(), e);
        }
        return vehicles;
    }
}